// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysApiFieldNames          = builder.RawFieldNames(&SysApi{})
	sysApiRows                = strings.Join(sysApiFieldNames, ",")
	sysApiRowsExpectAutoSet   = strings.Join(stringx.Remove(sysApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysApiRowsWithPlaceHolder = strings.Join(stringx.Remove(sysApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysApiIdPrefix         = "cache:sysApi:id:"
	cacheSysApiPathMethodPrefix = "cache:sysApi:path:method:"
)

type (
	sysApiModel interface {
		Insert(ctx context.Context, data *SysApi) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysApi, error)
		FindOneByPathMethod(ctx context.Context, path string, method string) (*SysApi, error)
		Update(ctx context.Context, data *SysApi) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysApiModel struct {
		sqlc.CachedConn
		table string
	}

	SysApi struct {
		Id         int64     `db:"id"`
		ApiGroup   string    `db:"api_group"`
		Title      string    `db:"title"`
		Path       string    `db:"path"`
		Method     string    `db:"method"`
		IsAutoSync int64     `db:"is_auto_sync"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newSysApiModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysApiModel {
	return &defaultSysApiModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_api`",
	}
}

func (m *defaultSysApiModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysApiIdKey := fmt.Sprintf("%s%v", cacheSysApiIdPrefix, id)
	sysApiPathMethodKey := fmt.Sprintf("%s%v:%v", cacheSysApiPathMethodPrefix, data.Path, data.Method)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysApiIdKey, sysApiPathMethodKey)
	return err
}

func (m *defaultSysApiModel) FindOne(ctx context.Context, id int64) (*SysApi, error) {
	sysApiIdKey := fmt.Sprintf("%s%v", cacheSysApiIdPrefix, id)
	var resp SysApi
	err := m.QueryRowCtx(ctx, &resp, sysApiIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysApiRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysApiModel) FindOneByPathMethod(ctx context.Context, path string, method string) (*SysApi, error) {
	sysApiPathMethodKey := fmt.Sprintf("%s%v:%v", cacheSysApiPathMethodPrefix, path, method)
	var resp SysApi
	err := m.QueryRowIndexCtx(ctx, &resp, sysApiPathMethodKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `path` = ? and `method` = ? limit 1", sysApiRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, path, method); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysApiModel) Insert(ctx context.Context, data *SysApi) (sql.Result, error) {
	sysApiIdKey := fmt.Sprintf("%s%v", cacheSysApiIdPrefix, data.Id)
	sysApiPathMethodKey := fmt.Sprintf("%s%v:%v", cacheSysApiPathMethodPrefix, data.Path, data.Method)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sysApiRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ApiGroup, data.Title, data.Path, data.Method, data.IsAutoSync)
	}, sysApiIdKey, sysApiPathMethodKey)
	return ret, err
}

func (m *defaultSysApiModel) Update(ctx context.Context, newData *SysApi) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysApiIdKey := fmt.Sprintf("%s%v", cacheSysApiIdPrefix, data.Id)
	sysApiPathMethodKey := fmt.Sprintf("%s%v:%v", cacheSysApiPathMethodPrefix, data.Path, data.Method)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysApiRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ApiGroup, newData.Title, newData.Path, newData.Method, newData.IsAutoSync, newData.Id)
	}, sysApiIdKey, sysApiPathMethodKey)
	return err
}

func (m *defaultSysApiModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysApiIdPrefix, primary)
}

func (m *defaultSysApiModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysApiRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysApiModel) tableName() string {
	return m.table
}
