// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictTypeFieldNames          = builder.RawFieldNames(&SysDictType{})
	sysDictTypeRows                = strings.Join(sysDictTypeFieldNames, ",")
	sysDictTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDictTypeRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysDictTypeIdPrefix       = "cache:sysDictType:id:"
	cacheSysDictTypeDictTypePrefix = "cache:sysDictType:dictType:"
)

type (
	sysDictTypeModel interface {
		Insert(ctx context.Context, data *SysDictType) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysDictType, error)
		FindOneByDictType(ctx context.Context, dictType string) (*SysDictType, error)
		Update(ctx context.Context, data *SysDictType) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysDictTypeModel struct {
		sqlc.CachedConn
		table string
	}

	SysDictType struct {
		Id         int64     `db:"id"`
		DictName   string    `db:"dict_name"`
		DictType   string    `db:"dict_type"`
		Status     int64     `db:"status"`
		Remark     string    `db:"remark"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newSysDictTypeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysDictTypeModel {
	return &defaultSysDictTypeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_dict_type`",
	}
}

func (m *defaultSysDictTypeModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysDictTypeDictTypeKey := fmt.Sprintf("%s%v", cacheSysDictTypeDictTypePrefix, data.DictType)
	sysDictTypeIdKey := fmt.Sprintf("%s%v", cacheSysDictTypeIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysDictTypeDictTypeKey, sysDictTypeIdKey)
	return err
}

func (m *defaultSysDictTypeModel) FindOne(ctx context.Context, id int64) (*SysDictType, error) {
	sysDictTypeIdKey := fmt.Sprintf("%s%v", cacheSysDictTypeIdPrefix, id)
	var resp SysDictType
	err := m.QueryRowCtx(ctx, &resp, sysDictTypeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictTypeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) FindOneByDictType(ctx context.Context, dictType string) (*SysDictType, error) {
	sysDictTypeDictTypeKey := fmt.Sprintf("%s%v", cacheSysDictTypeDictTypePrefix, dictType)
	var resp SysDictType
	err := m.QueryRowIndexCtx(ctx, &resp, sysDictTypeDictTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `dict_type` = ? limit 1", sysDictTypeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, dictType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) Insert(ctx context.Context, data *SysDictType) (sql.Result, error) {
	sysDictTypeDictTypeKey := fmt.Sprintf("%s%v", cacheSysDictTypeDictTypePrefix, data.DictType)
	sysDictTypeIdKey := fmt.Sprintf("%s%v", cacheSysDictTypeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, sysDictTypeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DictName, data.DictType, data.Status, data.Remark)
	}, sysDictTypeDictTypeKey, sysDictTypeIdKey)
	return ret, err
}

func (m *defaultSysDictTypeModel) Update(ctx context.Context, newData *SysDictType) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysDictTypeDictTypeKey := fmt.Sprintf("%s%v", cacheSysDictTypeDictTypePrefix, data.DictType)
	sysDictTypeIdKey := fmt.Sprintf("%s%v", cacheSysDictTypeIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDictTypeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DictName, newData.DictType, newData.Status, newData.Remark, newData.Id)
	}, sysDictTypeDictTypeKey, sysDictTypeIdKey)
	return err
}

func (m *defaultSysDictTypeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysDictTypeIdPrefix, primary)
}

func (m *defaultSysDictTypeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictTypeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDictTypeModel) tableName() string {
	return m.table
}
