// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleApiFieldNames          = builder.RawFieldNames(&SysRoleApi{})
	sysRoleApiRows                = strings.Join(sysRoleApiFieldNames, ",")
	sysRoleApiRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRoleApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysRoleApiRowsWithPlaceHolder = strings.Join(stringx.Remove(sysRoleApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysRoleApiIdPrefix          = "cache:sysRoleApi:id:"
	cacheSysRoleApiRoleIdApiIdPrefix = "cache:sysRoleApi:roleId:apiId:"
)

type (
	sysRoleApiModel interface {
		Insert(ctx context.Context, data *SysRoleApi) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysRoleApi, error)
		FindOneByRoleIdApiId(ctx context.Context, roleId int64, apiId int64) (*SysRoleApi, error)
		Update(ctx context.Context, data *SysRoleApi) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysRoleApiModel struct {
		sqlc.CachedConn
		table string
	}

	SysRoleApi struct {
		Id     int64 `db:"id"`
		RoleId int64 `db:"role_id"`
		ApiId  int64 `db:"api_id"`
	}
)

func newSysRoleApiModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysRoleApiModel {
	return &defaultSysRoleApiModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_role_api`",
	}
}

func (m *defaultSysRoleApiModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysRoleApiIdKey := fmt.Sprintf("%s%v", cacheSysRoleApiIdPrefix, id)
	sysRoleApiRoleIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysRoleApiRoleIdApiIdPrefix, data.RoleId, data.ApiId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysRoleApiIdKey, sysRoleApiRoleIdApiIdKey)
	return err
}

func (m *defaultSysRoleApiModel) FindOne(ctx context.Context, id int64) (*SysRoleApi, error) {
	sysRoleApiIdKey := fmt.Sprintf("%s%v", cacheSysRoleApiIdPrefix, id)
	var resp SysRoleApi
	err := m.QueryRowCtx(ctx, &resp, sysRoleApiIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysRoleApiRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleApiModel) FindOneByRoleIdApiId(ctx context.Context, roleId int64, apiId int64) (*SysRoleApi, error) {
	sysRoleApiRoleIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysRoleApiRoleIdApiIdPrefix, roleId, apiId)
	var resp SysRoleApi
	err := m.QueryRowIndexCtx(ctx, &resp, sysRoleApiRoleIdApiIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `role_id` = ? and `api_id` = ? limit 1", sysRoleApiRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, roleId, apiId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleApiModel) Insert(ctx context.Context, data *SysRoleApi) (sql.Result, error) {
	sysRoleApiIdKey := fmt.Sprintf("%s%v", cacheSysRoleApiIdPrefix, data.Id)
	sysRoleApiRoleIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysRoleApiRoleIdApiIdPrefix, data.RoleId, data.ApiId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysRoleApiRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RoleId, data.ApiId)
	}, sysRoleApiIdKey, sysRoleApiRoleIdApiIdKey)
	return ret, err
}

func (m *defaultSysRoleApiModel) Update(ctx context.Context, newData *SysRoleApi) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysRoleApiIdKey := fmt.Sprintf("%s%v", cacheSysRoleApiIdPrefix, data.Id)
	sysRoleApiRoleIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysRoleApiRoleIdApiIdPrefix, data.RoleId, data.ApiId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysRoleApiRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RoleId, newData.ApiId, newData.Id)
	}, sysRoleApiIdKey, sysRoleApiRoleIdApiIdKey)
	return err
}

func (m *defaultSysRoleApiModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysRoleApiIdPrefix, primary)
}

func (m *defaultSysRoleApiModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysRoleApiRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysRoleApiModel) tableName() string {
	return m.table
}
