// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysMenuApiFieldNames          = builder.RawFieldNames(&SysMenuApi{})
	sysMenuApiRows                = strings.Join(sysMenuApiFieldNames, ",")
	sysMenuApiRowsExpectAutoSet   = strings.Join(stringx.Remove(sysMenuApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysMenuApiRowsWithPlaceHolder = strings.Join(stringx.Remove(sysMenuApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysMenuApiIdPrefix          = "cache:sysMenuApi:id:"
	cacheSysMenuApiMenuIdApiIdPrefix = "cache:sysMenuApi:menuId:apiId:"
)

type (
	sysMenuApiModel interface {
		Insert(ctx context.Context, data *SysMenuApi) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysMenuApi, error)
		FindOneByMenuIdApiId(ctx context.Context, menuId int64, apiId int64) (*SysMenuApi, error)
		Update(ctx context.Context, data *SysMenuApi) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysMenuApiModel struct {
		sqlc.CachedConn
		table string
	}

	SysMenuApi struct {
		Id     int64 `db:"id"`
		MenuId int64 `db:"menu_id"`
		ApiId  int64 `db:"api_id"`
	}
)

func newSysMenuApiModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysMenuApiModel {
	return &defaultSysMenuApiModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_menu_api`",
	}
}

func (m *defaultSysMenuApiModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysMenuApiIdKey := fmt.Sprintf("%s%v", cacheSysMenuApiIdPrefix, id)
	sysMenuApiMenuIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysMenuApiMenuIdApiIdPrefix, data.MenuId, data.ApiId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysMenuApiIdKey, sysMenuApiMenuIdApiIdKey)
	return err
}

func (m *defaultSysMenuApiModel) FindOne(ctx context.Context, id int64) (*SysMenuApi, error) {
	sysMenuApiIdKey := fmt.Sprintf("%s%v", cacheSysMenuApiIdPrefix, id)
	var resp SysMenuApi
	err := m.QueryRowCtx(ctx, &resp, sysMenuApiIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysMenuApiRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuApiModel) FindOneByMenuIdApiId(ctx context.Context, menuId int64, apiId int64) (*SysMenuApi, error) {
	sysMenuApiMenuIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysMenuApiMenuIdApiIdPrefix, menuId, apiId)
	var resp SysMenuApi
	err := m.QueryRowIndexCtx(ctx, &resp, sysMenuApiMenuIdApiIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `menu_id` = ? and `api_id` = ? limit 1", sysMenuApiRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, menuId, apiId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuApiModel) Insert(ctx context.Context, data *SysMenuApi) (sql.Result, error) {
	sysMenuApiIdKey := fmt.Sprintf("%s%v", cacheSysMenuApiIdPrefix, data.Id)
	sysMenuApiMenuIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysMenuApiMenuIdApiIdPrefix, data.MenuId, data.ApiId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysMenuApiRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MenuId, data.ApiId)
	}, sysMenuApiIdKey, sysMenuApiMenuIdApiIdKey)
	return ret, err
}

func (m *defaultSysMenuApiModel) Update(ctx context.Context, newData *SysMenuApi) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysMenuApiIdKey := fmt.Sprintf("%s%v", cacheSysMenuApiIdPrefix, data.Id)
	sysMenuApiMenuIdApiIdKey := fmt.Sprintf("%s%v:%v", cacheSysMenuApiMenuIdApiIdPrefix, data.MenuId, data.ApiId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysMenuApiRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MenuId, newData.ApiId, newData.Id)
	}, sysMenuApiIdKey, sysMenuApiMenuIdApiIdKey)
	return err
}

func (m *defaultSysMenuApiModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysMenuApiIdPrefix, primary)
}

func (m *defaultSysMenuApiModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysMenuApiRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysMenuApiModel) tableName() string {
	return m.table
}
