// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysConfigFieldNames          = builder.RawFieldNames(&SysConfig{})
	sysConfigRows                = strings.Join(sysConfigFieldNames, ",")
	sysConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(sysConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(sysConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoZeroBoilerplateSysConfigIdPrefix        = "cache:goZeroBoilerplate:sysConfig:id:"
	cacheGoZeroBoilerplateSysConfigConfigKeyPrefix = "cache:goZeroBoilerplate:sysConfig:configKey:"
)

type (
	sysConfigModel interface {
		Insert(ctx context.Context, data *SysConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysConfig, error)
		FindOneByConfigKey(ctx context.Context, configKey string) (*SysConfig, error)
		Update(ctx context.Context, data *SysConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysConfigModel struct {
		sqlc.CachedConn
		table string
	}

	SysConfig struct {
		Id          int64     `db:"id"`           // 参数主键
		ConfigName  string    `db:"config_name"`  // 参数名称
		ConfigKey   string    `db:"config_key"`   // 参数键名
		ConfigValue string    `db:"config_value"` // 参数键值
		ConfigType  string    `db:"config_type"`  // 系统内置（Y是 N否）
		Remark      string    `db:"remark"`       // 备注说明
		CreateTime  time.Time `db:"create_time"`  // 创建时间
		UpdateTime  time.Time `db:"update_time"`  // 更新时间
	}
)

func newSysConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysConfigModel {
	return &defaultSysConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_config`",
	}
}

func (m *defaultSysConfigModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	goZeroBoilerplateSysConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigConfigKeyPrefix, data.ConfigKey)
	goZeroBoilerplateSysConfigIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goZeroBoilerplateSysConfigConfigKeyKey, goZeroBoilerplateSysConfigIdKey)
	return err
}

func (m *defaultSysConfigModel) FindOne(ctx context.Context, id int64) (*SysConfig, error) {
	goZeroBoilerplateSysConfigIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigIdPrefix, id)
	var resp SysConfig
	err := m.QueryRowCtx(ctx, &resp, goZeroBoilerplateSysConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysConfigModel) FindOneByConfigKey(ctx context.Context, configKey string) (*SysConfig, error) {
	goZeroBoilerplateSysConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigConfigKeyPrefix, configKey)
	var resp SysConfig
	err := m.QueryRowIndexCtx(ctx, &resp, goZeroBoilerplateSysConfigConfigKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `config_key` = ? limit 1", sysConfigRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, configKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysConfigModel) Insert(ctx context.Context, data *SysConfig) (sql.Result, error) {
	goZeroBoilerplateSysConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigConfigKeyPrefix, data.ConfigKey)
	goZeroBoilerplateSysConfigIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sysConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ConfigName, data.ConfigKey, data.ConfigValue, data.ConfigType, data.Remark)
	}, goZeroBoilerplateSysConfigConfigKeyKey, goZeroBoilerplateSysConfigIdKey)
	return ret, err
}

func (m *defaultSysConfigModel) Update(ctx context.Context, newData *SysConfig) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	goZeroBoilerplateSysConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigConfigKeyPrefix, data.ConfigKey)
	goZeroBoilerplateSysConfigIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ConfigName, newData.ConfigKey, newData.ConfigValue, newData.ConfigType, newData.Remark, newData.Id)
	}, goZeroBoilerplateSysConfigConfigKeyKey, goZeroBoilerplateSysConfigIdKey)
	return err
}

func (m *defaultSysConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoZeroBoilerplateSysConfigIdPrefix, primary)
}

func (m *defaultSysConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysConfigModel) tableName() string {
	return m.table
}
