// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictDataFieldNames          = builder.RawFieldNames(&SysDictData{})
	sysDictDataRows                = strings.Join(sysDictDataFieldNames, ",")
	sysDictDataRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDictDataRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSysDictDataIdPrefix                = "cache:sysDictData:id:"
	cacheSysDictDataDictTypeDictValuePrefix = "cache:sysDictData:dictType:dictValue:"
)

type (
	sysDictDataModel interface {
		Insert(ctx context.Context, data *SysDictData) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysDictData, error)
		FindOneByDictTypeDictValue(ctx context.Context, dictType string, dictValue string) (*SysDictData, error)
		Update(ctx context.Context, data *SysDictData) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysDictDataModel struct {
		sqlc.CachedConn
		table string
	}

	SysDictData struct {
		Id         int64     `db:"id"`
		DictType   string    `db:"dict_type"`
		DictLabel  string    `db:"dict_label"`
		DictValue  string    `db:"dict_value"`
		DictSort   int64     `db:"dict_sort"`
		ListClass  string    `db:"list_class"`
		IsDefault  int64     `db:"is_default"`
		Status     int64     `db:"status"`
		Remark     string    `db:"remark"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newSysDictDataModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysDictDataModel {
	return &defaultSysDictDataModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_dict_data`",
	}
}

func (m *defaultSysDictDataModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sysDictDataDictTypeDictValueKey := fmt.Sprintf("%s%v:%v", cacheSysDictDataDictTypeDictValuePrefix, data.DictType, data.DictValue)
	sysDictDataIdKey := fmt.Sprintf("%s%v", cacheSysDictDataIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysDictDataDictTypeDictValueKey, sysDictDataIdKey)
	return err
}

func (m *defaultSysDictDataModel) FindOne(ctx context.Context, id int64) (*SysDictData, error) {
	sysDictDataIdKey := fmt.Sprintf("%s%v", cacheSysDictDataIdPrefix, id)
	var resp SysDictData
	err := m.QueryRowCtx(ctx, &resp, sysDictDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictDataRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictDataModel) FindOneByDictTypeDictValue(ctx context.Context, dictType string, dictValue string) (*SysDictData, error) {
	sysDictDataDictTypeDictValueKey := fmt.Sprintf("%s%v:%v", cacheSysDictDataDictTypeDictValuePrefix, dictType, dictValue)
	var resp SysDictData
	err := m.QueryRowIndexCtx(ctx, &resp, sysDictDataDictTypeDictValueKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `dict_type` = ? and `dict_value` = ? limit 1", sysDictDataRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, dictType, dictValue); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictDataModel) Insert(ctx context.Context, data *SysDictData) (sql.Result, error) {
	sysDictDataDictTypeDictValueKey := fmt.Sprintf("%s%v:%v", cacheSysDictDataDictTypeDictValuePrefix, data.DictType, data.DictValue)
	sysDictDataIdKey := fmt.Sprintf("%s%v", cacheSysDictDataIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDictDataRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DictType, data.DictLabel, data.DictValue, data.DictSort, data.ListClass, data.IsDefault, data.Status, data.Remark)
	}, sysDictDataDictTypeDictValueKey, sysDictDataIdKey)
	return ret, err
}

func (m *defaultSysDictDataModel) Update(ctx context.Context, newData *SysDictData) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sysDictDataDictTypeDictValueKey := fmt.Sprintf("%s%v:%v", cacheSysDictDataDictTypeDictValuePrefix, data.DictType, data.DictValue)
	sysDictDataIdKey := fmt.Sprintf("%s%v", cacheSysDictDataIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDictDataRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DictType, newData.DictLabel, newData.DictValue, newData.DictSort, newData.ListClass, newData.IsDefault, newData.Status, newData.Remark, newData.Id)
	}, sysDictDataDictTypeDictValueKey, sysDictDataIdKey)
	return err
}

func (m *defaultSysDictDataModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysDictDataIdPrefix, primary)
}

func (m *defaultSysDictDataModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictDataRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDictDataModel) tableName() string {
	return m.table
}
