// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	itsmTaskFieldNames          = builder.RawFieldNames(&ItsmTask{})
	itsmTaskRows                = strings.Join(itsmTaskFieldNames, ",")
	itsmTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(itsmTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	itsmTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(itsmTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheItsmTaskIdPrefix = "cache:itsmTask:id:"
)

type (
	itsmTaskModel interface {
		Insert(ctx context.Context, data *ItsmTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ItsmTask, error)
		Update(ctx context.Context, data *ItsmTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultItsmTaskModel struct {
		sqlc.CachedConn
		table string
	}

	ItsmTask struct {
		Id             int64          `db:"id"`
		InstId         int64          `db:"inst_id"`
		NodeId         string         `db:"node_id"`
		NodeName       string         `db:"node_name"`
		TaskType       string         `db:"task_type"`
		ApprovalMode   string         `db:"approval_mode"`
		AssigneeId     sql.NullInt64  `db:"assignee_id"`
		CandidateUsers sql.NullString `db:"candidate_users"`
		CandidateRoles sql.NullString `db:"candidate_roles"`
		Status         string         `db:"status"`
		ClaimAt        sql.NullTime   `db:"claim_at"`
		CompletedAt    sql.NullTime   `db:"completed_at"`
		CreateTime     time.Time      `db:"create_time"`
	}
)

func newItsmTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultItsmTaskModel {
	return &defaultItsmTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`itsm_task`",
	}
}

func (m *defaultItsmTaskModel) Delete(ctx context.Context, id int64) error {
	itsmTaskIdKey := fmt.Sprintf("%s%v", cacheItsmTaskIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, itsmTaskIdKey)
	return err
}

func (m *defaultItsmTaskModel) FindOne(ctx context.Context, id int64) (*ItsmTask, error) {
	itsmTaskIdKey := fmt.Sprintf("%s%v", cacheItsmTaskIdPrefix, id)
	var resp ItsmTask
	err := m.QueryRowCtx(ctx, &resp, itsmTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmTaskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItsmTaskModel) Insert(ctx context.Context, data *ItsmTask) (sql.Result, error) {
	itsmTaskIdKey := fmt.Sprintf("%s%v", cacheItsmTaskIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, itsmTaskRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.InstId, data.NodeId, data.NodeName, data.TaskType, data.ApprovalMode, data.AssigneeId, data.CandidateUsers, data.CandidateRoles, data.Status, data.ClaimAt, data.CompletedAt)
	}, itsmTaskIdKey)
	return ret, err
}

func (m *defaultItsmTaskModel) Update(ctx context.Context, data *ItsmTask) error {
	itsmTaskIdKey := fmt.Sprintf("%s%v", cacheItsmTaskIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, itsmTaskRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.InstId, data.NodeId, data.NodeName, data.TaskType, data.ApprovalMode, data.AssigneeId, data.CandidateUsers, data.CandidateRoles, data.Status, data.ClaimAt, data.CompletedAt, data.Id)
	}, itsmTaskIdKey)
	return err
}

func (m *defaultItsmTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheItsmTaskIdPrefix, primary)
}

func (m *defaultItsmTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmTaskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultItsmTaskModel) tableName() string {
	return m.table
}
