// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	itsmSlaPolicyFieldNames          = builder.RawFieldNames(&ItsmSlaPolicy{})
	itsmSlaPolicyRows                = strings.Join(itsmSlaPolicyFieldNames, ",")
	itsmSlaPolicyRowsExpectAutoSet   = strings.Join(stringx.Remove(itsmSlaPolicyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	itsmSlaPolicyRowsWithPlaceHolder = strings.Join(stringx.Remove(itsmSlaPolicyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheItsmSlaPolicyIdPrefix                   = "cache:itsmSlaPolicy:id:"
	cacheItsmSlaPolicyPriorityCalendarTypePrefix = "cache:itsmSlaPolicy:priority:calendarType:"
)

type (
	itsmSlaPolicyModel interface {
		Insert(ctx context.Context, data *ItsmSlaPolicy) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ItsmSlaPolicy, error)
		FindOneByPriorityCalendarType(ctx context.Context, priority string, calendarType string) (*ItsmSlaPolicy, error)
		Update(ctx context.Context, data *ItsmSlaPolicy) error
		Delete(ctx context.Context, id int64) error
	}

	defaultItsmSlaPolicyModel struct {
		sqlc.CachedConn
		table string
	}

	ItsmSlaPolicy struct {
		Id               int64     `db:"id"`
		Priority         string    `db:"priority"`
		CalendarType     string    `db:"calendar_type"`
		ResponseLimitMin int64     `db:"response_limit_min"`
		ResolveLimitMin  int64     `db:"resolve_limit_min"`
		WarnThresholdPct int64     `db:"warn_threshold_pct"`
		CreateTime       time.Time `db:"create_time"`
		UpdateTime       time.Time `db:"update_time"`
	}
)

func newItsmSlaPolicyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultItsmSlaPolicyModel {
	return &defaultItsmSlaPolicyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`itsm_sla_policy`",
	}
}

func (m *defaultItsmSlaPolicyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	itsmSlaPolicyIdKey := fmt.Sprintf("%s%v", cacheItsmSlaPolicyIdPrefix, id)
	itsmSlaPolicyPriorityCalendarTypeKey := fmt.Sprintf("%s%v:%v", cacheItsmSlaPolicyPriorityCalendarTypePrefix, data.Priority, data.CalendarType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, itsmSlaPolicyIdKey, itsmSlaPolicyPriorityCalendarTypeKey)
	return err
}

func (m *defaultItsmSlaPolicyModel) FindOne(ctx context.Context, id int64) (*ItsmSlaPolicy, error) {
	itsmSlaPolicyIdKey := fmt.Sprintf("%s%v", cacheItsmSlaPolicyIdPrefix, id)
	var resp ItsmSlaPolicy
	err := m.QueryRowCtx(ctx, &resp, itsmSlaPolicyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmSlaPolicyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItsmSlaPolicyModel) FindOneByPriorityCalendarType(ctx context.Context, priority string, calendarType string) (*ItsmSlaPolicy, error) {
	itsmSlaPolicyPriorityCalendarTypeKey := fmt.Sprintf("%s%v:%v", cacheItsmSlaPolicyPriorityCalendarTypePrefix, priority, calendarType)
	var resp ItsmSlaPolicy
	err := m.QueryRowIndexCtx(ctx, &resp, itsmSlaPolicyPriorityCalendarTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `priority` = ? and `calendar_type` = ? limit 1", itsmSlaPolicyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, priority, calendarType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItsmSlaPolicyModel) Insert(ctx context.Context, data *ItsmSlaPolicy) (sql.Result, error) {
	itsmSlaPolicyIdKey := fmt.Sprintf("%s%v", cacheItsmSlaPolicyIdPrefix, data.Id)
	itsmSlaPolicyPriorityCalendarTypeKey := fmt.Sprintf("%s%v:%v", cacheItsmSlaPolicyPriorityCalendarTypePrefix, data.Priority, data.CalendarType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, itsmSlaPolicyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Priority, data.CalendarType, data.ResponseLimitMin, data.ResolveLimitMin, data.WarnThresholdPct)
	}, itsmSlaPolicyIdKey, itsmSlaPolicyPriorityCalendarTypeKey)
	return ret, err
}

func (m *defaultItsmSlaPolicyModel) Update(ctx context.Context, newData *ItsmSlaPolicy) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	itsmSlaPolicyIdKey := fmt.Sprintf("%s%v", cacheItsmSlaPolicyIdPrefix, data.Id)
	itsmSlaPolicyPriorityCalendarTypeKey := fmt.Sprintf("%s%v:%v", cacheItsmSlaPolicyPriorityCalendarTypePrefix, data.Priority, data.CalendarType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, itsmSlaPolicyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Priority, newData.CalendarType, newData.ResponseLimitMin, newData.ResolveLimitMin, newData.WarnThresholdPct, newData.Id)
	}, itsmSlaPolicyIdKey, itsmSlaPolicyPriorityCalendarTypeKey)
	return err
}

func (m *defaultItsmSlaPolicyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheItsmSlaPolicyIdPrefix, primary)
}

func (m *defaultItsmSlaPolicyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmSlaPolicyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultItsmSlaPolicyModel) tableName() string {
	return m.table
}
