// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	itsmTicketDataFieldNames          = builder.RawFieldNames(&ItsmTicketData{})
	itsmTicketDataRows                = strings.Join(itsmTicketDataFieldNames, ",")
	itsmTicketDataRowsExpectAutoSet   = strings.Join(stringx.Remove(itsmTicketDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	itsmTicketDataRowsWithPlaceHolder = strings.Join(stringx.Remove(itsmTicketDataFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheItsmTicketDataIdPrefix     = "cache:itsmTicketData:id:"
	cacheItsmTicketDataInstIdPrefix = "cache:itsmTicketData:instId:"
)

type (
	itsmTicketDataModel interface {
		Insert(ctx context.Context, data *ItsmTicketData) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ItsmTicketData, error)
		FindOneByInstId(ctx context.Context, instId int64) (*ItsmTicketData, error)
		Update(ctx context.Context, data *ItsmTicketData) error
		Delete(ctx context.Context, id int64) error
	}

	defaultItsmTicketDataModel struct {
		sqlc.CachedConn
		table string
	}

	ItsmTicketData struct {
		Id             int64          `db:"id"`
		InstId         int64          `db:"inst_id"`
		FormData       string         `db:"form_data"`
		SnapshotSchema sql.NullString `db:"snapshot_schema"`
		CreateTime     time.Time      `db:"create_time"`
		UpdateTime     time.Time      `db:"update_time"`
	}
)

func newItsmTicketDataModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultItsmTicketDataModel {
	return &defaultItsmTicketDataModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`itsm_ticket_data`",
	}
}

func (m *defaultItsmTicketDataModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	itsmTicketDataIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataIdPrefix, id)
	itsmTicketDataInstIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataInstIdPrefix, data.InstId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, itsmTicketDataIdKey, itsmTicketDataInstIdKey)
	return err
}

func (m *defaultItsmTicketDataModel) FindOne(ctx context.Context, id int64) (*ItsmTicketData, error) {
	itsmTicketDataIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataIdPrefix, id)
	var resp ItsmTicketData
	err := m.QueryRowCtx(ctx, &resp, itsmTicketDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmTicketDataRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItsmTicketDataModel) FindOneByInstId(ctx context.Context, instId int64) (*ItsmTicketData, error) {
	itsmTicketDataInstIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataInstIdPrefix, instId)
	var resp ItsmTicketData
	err := m.QueryRowIndexCtx(ctx, &resp, itsmTicketDataInstIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `inst_id` = ? limit 1", itsmTicketDataRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, instId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItsmTicketDataModel) Insert(ctx context.Context, data *ItsmTicketData) (sql.Result, error) {
	itsmTicketDataIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataIdPrefix, data.Id)
	itsmTicketDataInstIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataInstIdPrefix, data.InstId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, itsmTicketDataRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.InstId, data.FormData, data.SnapshotSchema)
	}, itsmTicketDataIdKey, itsmTicketDataInstIdKey)
	return ret, err
}

func (m *defaultItsmTicketDataModel) Update(ctx context.Context, newData *ItsmTicketData) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	itsmTicketDataIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataIdPrefix, data.Id)
	itsmTicketDataInstIdKey := fmt.Sprintf("%s%v", cacheItsmTicketDataInstIdPrefix, data.InstId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, itsmTicketDataRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.InstId, newData.FormData, newData.SnapshotSchema, newData.Id)
	}, itsmTicketDataIdKey, itsmTicketDataInstIdKey)
	return err
}

func (m *defaultItsmTicketDataModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheItsmTicketDataIdPrefix, primary)
}

func (m *defaultItsmTicketDataModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmTicketDataRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultItsmTicketDataModel) tableName() string {
	return m.table
}
