// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	itsmProcessDefFieldNames          = builder.RawFieldNames(&ItsmProcessDef{})
	itsmProcessDefRows                = strings.Join(itsmProcessDefFieldNames, ",")
	itsmProcessDefRowsExpectAutoSet   = strings.Join(stringx.Remove(itsmProcessDefFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	itsmProcessDefRowsWithPlaceHolder = strings.Join(stringx.Remove(itsmProcessDefFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheItsmProcessDefIdPrefix              = "cache:itsmProcessDef:id:"
	cacheItsmProcessDefProcCodeVersionPrefix = "cache:itsmProcessDef:procCode:version:"
)

type (
	itsmProcessDefModel interface {
		Insert(ctx context.Context, data *ItsmProcessDef) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ItsmProcessDef, error)
		FindOneByProcCodeVersion(ctx context.Context, procCode string, version int64) (*ItsmProcessDef, error)
		Update(ctx context.Context, data *ItsmProcessDef) error
		Delete(ctx context.Context, id int64) error
	}

	defaultItsmProcessDefModel struct {
		sqlc.CachedConn
		table string
	}

	ItsmProcessDef struct {
		Id          int64     `db:"id"`
		ProcCode    string    `db:"proc_code"`
		ProcName    string    `db:"proc_name"`
		Category    string    `db:"category"`
		BpmnXml     string    `db:"bpmn_xml"`
		FormSchema  string    `db:"form_schema"`
		Version     int64     `db:"version"`
		Status      int64     `db:"status"`
		Description string    `db:"description"`
		CreatedBy   int64     `db:"created_by"`
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newItsmProcessDefModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultItsmProcessDefModel {
	return &defaultItsmProcessDefModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`itsm_process_def`",
	}
}

func (m *defaultItsmProcessDefModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	itsmProcessDefIdKey := fmt.Sprintf("%s%v", cacheItsmProcessDefIdPrefix, id)
	itsmProcessDefProcCodeVersionKey := fmt.Sprintf("%s%v:%v", cacheItsmProcessDefProcCodeVersionPrefix, data.ProcCode, data.Version)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, itsmProcessDefIdKey, itsmProcessDefProcCodeVersionKey)
	return err
}

func (m *defaultItsmProcessDefModel) FindOne(ctx context.Context, id int64) (*ItsmProcessDef, error) {
	itsmProcessDefIdKey := fmt.Sprintf("%s%v", cacheItsmProcessDefIdPrefix, id)
	var resp ItsmProcessDef
	err := m.QueryRowCtx(ctx, &resp, itsmProcessDefIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmProcessDefRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItsmProcessDefModel) FindOneByProcCodeVersion(ctx context.Context, procCode string, version int64) (*ItsmProcessDef, error) {
	itsmProcessDefProcCodeVersionKey := fmt.Sprintf("%s%v:%v", cacheItsmProcessDefProcCodeVersionPrefix, procCode, version)
	var resp ItsmProcessDef
	err := m.QueryRowIndexCtx(ctx, &resp, itsmProcessDefProcCodeVersionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `proc_code` = ? and `version` = ? limit 1", itsmProcessDefRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, procCode, version); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItsmProcessDefModel) Insert(ctx context.Context, data *ItsmProcessDef) (sql.Result, error) {
	itsmProcessDefIdKey := fmt.Sprintf("%s%v", cacheItsmProcessDefIdPrefix, data.Id)
	itsmProcessDefProcCodeVersionKey := fmt.Sprintf("%s%v:%v", cacheItsmProcessDefProcCodeVersionPrefix, data.ProcCode, data.Version)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, itsmProcessDefRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProcCode, data.ProcName, data.Category, data.BpmnXml, data.FormSchema, data.Version, data.Status, data.Description, data.CreatedBy)
	}, itsmProcessDefIdKey, itsmProcessDefProcCodeVersionKey)
	return ret, err
}

func (m *defaultItsmProcessDefModel) Update(ctx context.Context, newData *ItsmProcessDef) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	itsmProcessDefIdKey := fmt.Sprintf("%s%v", cacheItsmProcessDefIdPrefix, data.Id)
	itsmProcessDefProcCodeVersionKey := fmt.Sprintf("%s%v:%v", cacheItsmProcessDefProcCodeVersionPrefix, data.ProcCode, data.Version)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, itsmProcessDefRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ProcCode, newData.ProcName, newData.Category, newData.BpmnXml, newData.FormSchema, newData.Version, newData.Status, newData.Description, newData.CreatedBy, newData.Id)
	}, itsmProcessDefIdKey, itsmProcessDefProcCodeVersionKey)
	return err
}

func (m *defaultItsmProcessDefModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheItsmProcessDefIdPrefix, primary)
}

func (m *defaultItsmProcessDefModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", itsmProcessDefRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultItsmProcessDefModel) tableName() string {
	return m.table
}
