// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: titan.proto

package server

import (
	"context"

	"go-zero-boilerplate/app/titan/rpc/internal/logic/titan"
	"go-zero-boilerplate/app/titan/rpc/internal/svc"
	"go-zero-boilerplate/app/titan/rpc/titan"
)

type TitanServer struct {
	svcCtx *svc.ServiceContext
	titan.UnimplementedTitanServer
}

func NewTitanServer(svcCtx *svc.ServiceContext) *TitanServer {
	return &TitanServer{
		svcCtx: svcCtx,
	}
}

func (s *TitanServer) Ping(ctx context.Context, in *titan.PingReq) (*titan.PingResp, error) {
	l := titanlogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// 集成凭证
func (s *TitanServer) ListIntegrations(ctx context.Context, in *titan.ListIntegrationsReq) (*titan.ListIntegrationsResp, error) {
	l := titanlogic.NewListIntegrationsLogic(ctx, s.svcCtx)
	return l.ListIntegrations(in)
}

func (s *TitanServer) CreateIntegration(ctx context.Context, in *titan.CreateIntegrationReq) (*titan.CreateIntegrationResp, error) {
	l := titanlogic.NewCreateIntegrationLogic(ctx, s.svcCtx)
	return l.CreateIntegration(in)
}

func (s *TitanServer) UpdateIntegration(ctx context.Context, in *titan.UpdateIntegrationReq) (*titan.CommonResp, error) {
	l := titanlogic.NewUpdateIntegrationLogic(ctx, s.svcCtx)
	return l.UpdateIntegration(in)
}

func (s *TitanServer) DeleteIntegration(ctx context.Context, in *titan.DeleteIntegrationReq) (*titan.CommonResp, error) {
	l := titanlogic.NewDeleteIntegrationLogic(ctx, s.svcCtx)
	return l.DeleteIntegration(in)
}

func (s *TitanServer) TestIntegration(ctx context.Context, in *titan.TestIntegrationReq) (*titan.TestIntegrationResp, error) {
	l := titanlogic.NewTestIntegrationLogic(ctx, s.svcCtx)
	return l.TestIntegration(in)
}

// K8s 集群
func (s *TitanServer) ListClusters(ctx context.Context, in *titan.ListClustersReq) (*titan.ListClustersResp, error) {
	l := titanlogic.NewListClustersLogic(ctx, s.svcCtx)
	return l.ListClusters(in)
}

func (s *TitanServer) CreateCluster(ctx context.Context, in *titan.CreateClusterReq) (*titan.CreateClusterResp, error) {
	l := titanlogic.NewCreateClusterLogic(ctx, s.svcCtx)
	return l.CreateCluster(in)
}

func (s *TitanServer) UpdateCluster(ctx context.Context, in *titan.UpdateClusterReq) (*titan.CommonResp, error) {
	l := titanlogic.NewUpdateClusterLogic(ctx, s.svcCtx)
	return l.UpdateCluster(in)
}

func (s *TitanServer) DeleteCluster(ctx context.Context, in *titan.DeleteClusterReq) (*titan.CommonResp, error) {
	l := titanlogic.NewDeleteClusterLogic(ctx, s.svcCtx)
	return l.DeleteCluster(in)
}

func (s *TitanServer) TestCluster(ctx context.Context, in *titan.TestClusterReq) (*titan.TestClusterResp, error) {
	l := titanlogic.NewTestClusterLogic(ctx, s.svcCtx)
	return l.TestCluster(in)
}

func (s *TitanServer) ListNamespaces(ctx context.Context, in *titan.ListNamespacesReq) (*titan.ListNamespacesResp, error) {
	l := titanlogic.NewListNamespacesLogic(ctx, s.svcCtx)
	return l.ListNamespaces(in)
}

// 流水线定义
func (s *TitanServer) ListPipelines(ctx context.Context, in *titan.ListPipelinesReq) (*titan.ListPipelinesResp, error) {
	l := titanlogic.NewListPipelinesLogic(ctx, s.svcCtx)
	return l.ListPipelines(in)
}

func (s *TitanServer) GetPipeline(ctx context.Context, in *titan.GetPipelineReq) (*titan.PipelineDetailResp, error) {
	l := titanlogic.NewGetPipelineLogic(ctx, s.svcCtx)
	return l.GetPipeline(in)
}

func (s *TitanServer) CreatePipeline(ctx context.Context, in *titan.CreatePipelineReq) (*titan.CreatePipelineResp, error) {
	l := titanlogic.NewCreatePipelineLogic(ctx, s.svcCtx)
	return l.CreatePipeline(in)
}

func (s *TitanServer) UpdatePipeline(ctx context.Context, in *titan.UpdatePipelineReq) (*titan.CommonResp, error) {
	l := titanlogic.NewUpdatePipelineLogic(ctx, s.svcCtx)
	return l.UpdatePipeline(in)
}

func (s *TitanServer) DeletePipeline(ctx context.Context, in *titan.DeletePipelineReq) (*titan.CommonResp, error) {
	l := titanlogic.NewDeletePipelineLogic(ctx, s.svcCtx)
	return l.DeletePipeline(in)
}

// 执行与步骤控制
func (s *TitanServer) TriggerPipeline(ctx context.Context, in *titan.TriggerPipelineReq) (*titan.TriggerPipelineResp, error) {
	l := titanlogic.NewTriggerPipelineLogic(ctx, s.svcCtx)
	return l.TriggerPipeline(in)
}

func (s *TitanServer) ListExecutions(ctx context.Context, in *titan.ListExecutionsReq) (*titan.ListExecutionsResp, error) {
	l := titanlogic.NewListExecutionsLogic(ctx, s.svcCtx)
	return l.ListExecutions(in)
}

func (s *TitanServer) GetExecutionDetail(ctx context.Context, in *titan.GetExecutionDetailReq) (*titan.ExecutionDetailResp, error) {
	l := titanlogic.NewGetExecutionDetailLogic(ctx, s.svcCtx)
	return l.GetExecutionDetail(in)
}

func (s *TitanServer) GetStepLog(ctx context.Context, in *titan.GetStepLogReq) (*titan.GetStepLogResp, error) {
	l := titanlogic.NewGetStepLogLogic(ctx, s.svcCtx)
	return l.GetStepLog(in)
}

func (s *TitanServer) ApproveStep(ctx context.Context, in *titan.ApproveStepReq) (*titan.CommonResp, error) {
	l := titanlogic.NewApproveStepLogic(ctx, s.svcCtx)
	return l.ApproveStep(in)
}

func (s *TitanServer) CancelExecution(ctx context.Context, in *titan.CancelExecutionReq) (*titan.CommonResp, error) {
	l := titanlogic.NewCancelExecutionLogic(ctx, s.svcCtx)
	return l.CancelExecution(in)
}
