// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	devopsClusterFieldNames          = builder.RawFieldNames(&DevopsCluster{})
	devopsClusterRows                = strings.Join(devopsClusterFieldNames, ",")
	devopsClusterRowsExpectAutoSet   = strings.Join(stringx.Remove(devopsClusterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	devopsClusterRowsWithPlaceHolder = strings.Join(stringx.Remove(devopsClusterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDevopsClusterIdPrefix   = "cache:devopsCluster:id:"
	cacheDevopsClusterNamePrefix = "cache:devopsCluster:name:"
)

type (
	devopsClusterModel interface {
		Insert(ctx context.Context, data *DevopsCluster) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DevopsCluster, error)
		FindOneByName(ctx context.Context, name string) (*DevopsCluster, error)
		Update(ctx context.Context, data *DevopsCluster) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDevopsClusterModel struct {
		sqlc.CachedConn
		table string
	}

	DevopsCluster struct {
		Id          int64     `db:"id"`
		Name        string    `db:"name"`
		Env         string    `db:"env"`
		ApiEndpoint string    `db:"api_endpoint"`
		Kubeconfig  string    `db:"kubeconfig"`
		Status      string    `db:"status"`
		Version     string    `db:"version"`
		Description string    `db:"description"`
		CreatedBy   int64     `db:"created_by"`
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newDevopsClusterModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDevopsClusterModel {
	return &defaultDevopsClusterModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`devops_cluster`",
	}
}

func (m *defaultDevopsClusterModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	devopsClusterIdKey := fmt.Sprintf("%s%v", cacheDevopsClusterIdPrefix, id)
	devopsClusterNameKey := fmt.Sprintf("%s%v", cacheDevopsClusterNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, devopsClusterIdKey, devopsClusterNameKey)
	return err
}

func (m *defaultDevopsClusterModel) FindOne(ctx context.Context, id int64) (*DevopsCluster, error) {
	devopsClusterIdKey := fmt.Sprintf("%s%v", cacheDevopsClusterIdPrefix, id)
	var resp DevopsCluster
	err := m.QueryRowCtx(ctx, &resp, devopsClusterIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", devopsClusterRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDevopsClusterModel) FindOneByName(ctx context.Context, name string) (*DevopsCluster, error) {
	devopsClusterNameKey := fmt.Sprintf("%s%v", cacheDevopsClusterNamePrefix, name)
	var resp DevopsCluster
	err := m.QueryRowIndexCtx(ctx, &resp, devopsClusterNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", devopsClusterRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDevopsClusterModel) Insert(ctx context.Context, data *DevopsCluster) (sql.Result, error) {
	devopsClusterIdKey := fmt.Sprintf("%s%v", cacheDevopsClusterIdPrefix, data.Id)
	devopsClusterNameKey := fmt.Sprintf("%s%v", cacheDevopsClusterNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, devopsClusterRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Env, data.ApiEndpoint, data.Kubeconfig, data.Status, data.Version, data.Description, data.CreatedBy)
	}, devopsClusterIdKey, devopsClusterNameKey)
	return ret, err
}

func (m *defaultDevopsClusterModel) Update(ctx context.Context, newData *DevopsCluster) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	devopsClusterIdKey := fmt.Sprintf("%s%v", cacheDevopsClusterIdPrefix, data.Id)
	devopsClusterNameKey := fmt.Sprintf("%s%v", cacheDevopsClusterNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, devopsClusterRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Env, newData.ApiEndpoint, newData.Kubeconfig, newData.Status, newData.Version, newData.Description, newData.CreatedBy, newData.Id)
	}, devopsClusterIdKey, devopsClusterNameKey)
	return err
}

func (m *defaultDevopsClusterModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDevopsClusterIdPrefix, primary)
}

func (m *defaultDevopsClusterModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", devopsClusterRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDevopsClusterModel) tableName() string {
	return m.table
}
