// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	devopsIntegrationFieldNames          = builder.RawFieldNames(&DevopsIntegration{})
	devopsIntegrationRows                = strings.Join(devopsIntegrationFieldNames, ",")
	devopsIntegrationRowsExpectAutoSet   = strings.Join(stringx.Remove(devopsIntegrationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	devopsIntegrationRowsWithPlaceHolder = strings.Join(stringx.Remove(devopsIntegrationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDevopsIntegrationIdPrefix = "cache:devopsIntegration:id:"
)

type (
	devopsIntegrationModel interface {
		Insert(ctx context.Context, data *DevopsIntegration) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DevopsIntegration, error)
		Update(ctx context.Context, data *DevopsIntegration) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDevopsIntegrationModel struct {
		sqlc.CachedConn
		table string
	}

	DevopsIntegration struct {
		Id          int64     `db:"id"`
		Name        string    `db:"name"`
		Category    string    `db:"category"`
		AuthType    string    `db:"auth_type"`
		Config      string    `db:"config"`
		Status      int64     `db:"status"`
		Description string    `db:"description"`
		CreatedBy   int64     `db:"created_by"`
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newDevopsIntegrationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDevopsIntegrationModel {
	return &defaultDevopsIntegrationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`devops_integration`",
	}
}

func (m *defaultDevopsIntegrationModel) Delete(ctx context.Context, id int64) error {
	devopsIntegrationIdKey := fmt.Sprintf("%s%v", cacheDevopsIntegrationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, devopsIntegrationIdKey)
	return err
}

func (m *defaultDevopsIntegrationModel) FindOne(ctx context.Context, id int64) (*DevopsIntegration, error) {
	devopsIntegrationIdKey := fmt.Sprintf("%s%v", cacheDevopsIntegrationIdPrefix, id)
	var resp DevopsIntegration
	err := m.QueryRowCtx(ctx, &resp, devopsIntegrationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", devopsIntegrationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDevopsIntegrationModel) Insert(ctx context.Context, data *DevopsIntegration) (sql.Result, error) {
	devopsIntegrationIdKey := fmt.Sprintf("%s%v", cacheDevopsIntegrationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, devopsIntegrationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Category, data.AuthType, data.Config, data.Status, data.Description, data.CreatedBy)
	}, devopsIntegrationIdKey)
	return ret, err
}

func (m *defaultDevopsIntegrationModel) Update(ctx context.Context, data *DevopsIntegration) error {
	devopsIntegrationIdKey := fmt.Sprintf("%s%v", cacheDevopsIntegrationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, devopsIntegrationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Category, data.AuthType, data.Config, data.Status, data.Description, data.CreatedBy, data.Id)
	}, devopsIntegrationIdKey)
	return err
}

func (m *defaultDevopsIntegrationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDevopsIntegrationIdPrefix, primary)
}

func (m *defaultDevopsIntegrationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", devopsIntegrationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDevopsIntegrationModel) tableName() string {
	return m.table
}
