// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	devopsPipelineStepExecFieldNames          = builder.RawFieldNames(&DevopsPipelineStepExec{})
	devopsPipelineStepExecRows                = strings.Join(devopsPipelineStepExecFieldNames, ",")
	devopsPipelineStepExecRowsExpectAutoSet   = strings.Join(stringx.Remove(devopsPipelineStepExecFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	devopsPipelineStepExecRowsWithPlaceHolder = strings.Join(stringx.Remove(devopsPipelineStepExecFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDevopsPipelineStepExecIdPrefix = "cache:devopsPipelineStepExec:id:"
)

type (
	devopsPipelineStepExecModel interface {
		Insert(ctx context.Context, data *DevopsPipelineStepExec) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DevopsPipelineStepExec, error)
		Update(ctx context.Context, data *DevopsPipelineStepExec) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDevopsPipelineStepExecModel struct {
		sqlc.CachedConn
		table string
	}

	DevopsPipelineStepExec struct {
		Id         int64        `db:"id"`
		ExecId     int64        `db:"exec_id"`
		StageId    string       `db:"stage_id"`
		StepId     string       `db:"step_id"`
		StepName   string       `db:"step_name"`
		StepType   string       `db:"step_type"`
		Status     string       `db:"status"`
		LogPath    string       `db:"log_path"`
		ErrorMsg   string       `db:"error_msg"`
		StartTime  sql.NullTime `db:"start_time"`
		EndTime    sql.NullTime `db:"end_time"`
		DurationMs int64        `db:"duration_ms"`
		CreateTime time.Time    `db:"create_time"`
	}
)

func newDevopsPipelineStepExecModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDevopsPipelineStepExecModel {
	return &defaultDevopsPipelineStepExecModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`devops_pipeline_step_exec`",
	}
}

func (m *defaultDevopsPipelineStepExecModel) Delete(ctx context.Context, id int64) error {
	devopsPipelineStepExecIdKey := fmt.Sprintf("%s%v", cacheDevopsPipelineStepExecIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, devopsPipelineStepExecIdKey)
	return err
}

func (m *defaultDevopsPipelineStepExecModel) FindOne(ctx context.Context, id int64) (*DevopsPipelineStepExec, error) {
	devopsPipelineStepExecIdKey := fmt.Sprintf("%s%v", cacheDevopsPipelineStepExecIdPrefix, id)
	var resp DevopsPipelineStepExec
	err := m.QueryRowCtx(ctx, &resp, devopsPipelineStepExecIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", devopsPipelineStepExecRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDevopsPipelineStepExecModel) Insert(ctx context.Context, data *DevopsPipelineStepExec) (sql.Result, error) {
	devopsPipelineStepExecIdKey := fmt.Sprintf("%s%v", cacheDevopsPipelineStepExecIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, devopsPipelineStepExecRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ExecId, data.StageId, data.StepId, data.StepName, data.StepType, data.Status, data.LogPath, data.ErrorMsg, data.StartTime, data.EndTime, data.DurationMs)
	}, devopsPipelineStepExecIdKey)
	return ret, err
}

func (m *defaultDevopsPipelineStepExecModel) Update(ctx context.Context, data *DevopsPipelineStepExec) error {
	devopsPipelineStepExecIdKey := fmt.Sprintf("%s%v", cacheDevopsPipelineStepExecIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, devopsPipelineStepExecRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ExecId, data.StageId, data.StepId, data.StepName, data.StepType, data.Status, data.LogPath, data.ErrorMsg, data.StartTime, data.EndTime, data.DurationMs, data.Id)
	}, devopsPipelineStepExecIdKey)
	return err
}

func (m *defaultDevopsPipelineStepExecModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDevopsPipelineStepExecIdPrefix, primary)
}

func (m *defaultDevopsPipelineStepExecModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", devopsPipelineStepExecRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDevopsPipelineStepExecModel) tableName() string {
	return m.table
}
