// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: devops.proto

package server

import (
	"context"

	"go-zero-boilerplate/app/devops/rpc/devops"
	"go-zero-boilerplate/app/devops/rpc/internal/logic/devops"
	"go-zero-boilerplate/app/devops/rpc/internal/svc"
)

type DevopsServer struct {
	svcCtx *svc.ServiceContext
	devops.UnimplementedDevopsServer
}

func NewDevopsServer(svcCtx *svc.ServiceContext) *DevopsServer {
	return &DevopsServer{
		svcCtx: svcCtx,
	}
}

func (s *DevopsServer) Ping(ctx context.Context, in *devops.PingReq) (*devops.PingResp, error) {
	l := devopslogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// 集成凭证
func (s *DevopsServer) ListIntegrations(ctx context.Context, in *devops.ListIntegrationsReq) (*devops.ListIntegrationsResp, error) {
	l := devopslogic.NewListIntegrationsLogic(ctx, s.svcCtx)
	return l.ListIntegrations(in)
}

func (s *DevopsServer) CreateIntegration(ctx context.Context, in *devops.CreateIntegrationReq) (*devops.CreateIntegrationResp, error) {
	l := devopslogic.NewCreateIntegrationLogic(ctx, s.svcCtx)
	return l.CreateIntegration(in)
}

func (s *DevopsServer) UpdateIntegration(ctx context.Context, in *devops.UpdateIntegrationReq) (*devops.CommonResp, error) {
	l := devopslogic.NewUpdateIntegrationLogic(ctx, s.svcCtx)
	return l.UpdateIntegration(in)
}

func (s *DevopsServer) DeleteIntegration(ctx context.Context, in *devops.DeleteIntegrationReq) (*devops.CommonResp, error) {
	l := devopslogic.NewDeleteIntegrationLogic(ctx, s.svcCtx)
	return l.DeleteIntegration(in)
}

func (s *DevopsServer) TestIntegration(ctx context.Context, in *devops.TestIntegrationReq) (*devops.TestIntegrationResp, error) {
	l := devopslogic.NewTestIntegrationLogic(ctx, s.svcCtx)
	return l.TestIntegration(in)
}

// K8s 集群
func (s *DevopsServer) ListClusters(ctx context.Context, in *devops.ListClustersReq) (*devops.ListClustersResp, error) {
	l := devopslogic.NewListClustersLogic(ctx, s.svcCtx)
	return l.ListClusters(in)
}

func (s *DevopsServer) CreateCluster(ctx context.Context, in *devops.CreateClusterReq) (*devops.CreateClusterResp, error) {
	l := devopslogic.NewCreateClusterLogic(ctx, s.svcCtx)
	return l.CreateCluster(in)
}

func (s *DevopsServer) UpdateCluster(ctx context.Context, in *devops.UpdateClusterReq) (*devops.CommonResp, error) {
	l := devopslogic.NewUpdateClusterLogic(ctx, s.svcCtx)
	return l.UpdateCluster(in)
}

func (s *DevopsServer) DeleteCluster(ctx context.Context, in *devops.DeleteClusterReq) (*devops.CommonResp, error) {
	l := devopslogic.NewDeleteClusterLogic(ctx, s.svcCtx)
	return l.DeleteCluster(in)
}

func (s *DevopsServer) TestCluster(ctx context.Context, in *devops.TestClusterReq) (*devops.TestClusterResp, error) {
	l := devopslogic.NewTestClusterLogic(ctx, s.svcCtx)
	return l.TestCluster(in)
}

func (s *DevopsServer) ListNamespaces(ctx context.Context, in *devops.ListNamespacesReq) (*devops.ListNamespacesResp, error) {
	l := devopslogic.NewListNamespacesLogic(ctx, s.svcCtx)
	return l.ListNamespaces(in)
}

// 流水线定义
func (s *DevopsServer) ListPipelines(ctx context.Context, in *devops.ListPipelinesReq) (*devops.ListPipelinesResp, error) {
	l := devopslogic.NewListPipelinesLogic(ctx, s.svcCtx)
	return l.ListPipelines(in)
}

func (s *DevopsServer) GetPipeline(ctx context.Context, in *devops.GetPipelineReq) (*devops.PipelineDetailResp, error) {
	l := devopslogic.NewGetPipelineLogic(ctx, s.svcCtx)
	return l.GetPipeline(in)
}

func (s *DevopsServer) CreatePipeline(ctx context.Context, in *devops.CreatePipelineReq) (*devops.CreatePipelineResp, error) {
	l := devopslogic.NewCreatePipelineLogic(ctx, s.svcCtx)
	return l.CreatePipeline(in)
}

func (s *DevopsServer) UpdatePipeline(ctx context.Context, in *devops.UpdatePipelineReq) (*devops.CommonResp, error) {
	l := devopslogic.NewUpdatePipelineLogic(ctx, s.svcCtx)
	return l.UpdatePipeline(in)
}

func (s *DevopsServer) DeletePipeline(ctx context.Context, in *devops.DeletePipelineReq) (*devops.CommonResp, error) {
	l := devopslogic.NewDeletePipelineLogic(ctx, s.svcCtx)
	return l.DeletePipeline(in)
}

// 执行与步骤控制
func (s *DevopsServer) TriggerPipeline(ctx context.Context, in *devops.TriggerPipelineReq) (*devops.TriggerPipelineResp, error) {
	l := devopslogic.NewTriggerPipelineLogic(ctx, s.svcCtx)
	return l.TriggerPipeline(in)
}

func (s *DevopsServer) ListExecutions(ctx context.Context, in *devops.ListExecutionsReq) (*devops.ListExecutionsResp, error) {
	l := devopslogic.NewListExecutionsLogic(ctx, s.svcCtx)
	return l.ListExecutions(in)
}

func (s *DevopsServer) GetExecutionDetail(ctx context.Context, in *devops.GetExecutionDetailReq) (*devops.ExecutionDetailResp, error) {
	l := devopslogic.NewGetExecutionDetailLogic(ctx, s.svcCtx)
	return l.GetExecutionDetail(in)
}

func (s *DevopsServer) GetStepLog(ctx context.Context, in *devops.GetStepLogReq) (*devops.GetStepLogResp, error) {
	l := devopslogic.NewGetStepLogLogic(ctx, s.svcCtx)
	return l.GetStepLog(in)
}

func (s *DevopsServer) ApproveStep(ctx context.Context, in *devops.ApproveStepReq) (*devops.CommonResp, error) {
	l := devopslogic.NewApproveStepLogic(ctx, s.svcCtx)
	return l.ApproveStep(in)
}

func (s *DevopsServer) CancelExecution(ctx context.Context, in *devops.CancelExecutionReq) (*devops.CommonResp, error) {
	l := devopslogic.NewCancelExecutionLogic(ctx, s.svcCtx)
	return l.CancelExecution(in)
}
