/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type {
  TitanApproveStepBody,
  TitanCreateCluster200,
  TitanCreateClusterBody,
  TitanCreateIntegration200,
  TitanCreateIntegrationBody,
  TitanCreatePipeline200,
  TitanCreatePipelineBody,
  TitanGetExecutionDetail200,
  TitanGetPipeline200,
  TitanGetStepLog200,
  TitanGetStepLogParams,
  TitanListClusters200,
  TitanListClustersParams,
  TitanListExecutions200,
  TitanListExecutionsParams,
  TitanListIntegrations200,
  TitanListIntegrationsParams,
  TitanListNamespaces200,
  TitanListPipelines200,
  TitanListPipelinesParams,
  TitanTestCluster200,
  TitanTestIntegration200,
  TitanTriggerPipeline200,
  TitanTriggerPipelineBody,
  TitanUpdateClusterBody,
  TitanUpdateIntegrationBody,
  TitanUpdatePipelineBody
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary listClusters
 */
export const titanListClusters = (
    params: TitanListClustersParams,
 options?: SecondParameter<typeof customInstance<TitanListClusters200>>,) => {
      return customInstance<TitanListClusters200>(
      {url: `/api/v1/titan/clusters`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary createCluster
 */
export const titanCreateCluster = (
    titanCreateClusterBody: TitanCreateClusterBody,
 options?: SecondParameter<typeof customInstance<TitanCreateCluster200>>,) => {
      return customInstance<TitanCreateCluster200>(
      {url: `/api/v1/titan/clusters`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: titanCreateClusterBody
    },
      options);
    }
  /**
 * @summary deleteCluster
 */
export const titanDeleteCluster = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/clusters/${id}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary updateCluster
 */
export const titanUpdateCluster = (
    id: number,
    titanUpdateClusterBody: TitanUpdateClusterBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/clusters/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: titanUpdateClusterBody
    },
      options);
    }
  /**
 * @summary listNamespaces
 */
export const titanListNamespaces = (
    id: number,
 options?: SecondParameter<typeof customInstance<TitanListNamespaces200>>,) => {
      return customInstance<TitanListNamespaces200>(
      {url: `/api/v1/titan/clusters/${id}/namespaces`, method: 'GET'
    },
      options);
    }
  /**
 * @summary testCluster
 */
export const titanTestCluster = (
    id: number,
 options?: SecondParameter<typeof customInstance<TitanTestCluster200>>,) => {
      return customInstance<TitanTestCluster200>(
      {url: `/api/v1/titan/clusters/${id}/test`, method: 'POST'
    },
      options);
    }
  /**
 * @summary listExecutions
 */
export const titanListExecutions = (
    params: TitanListExecutionsParams,
 options?: SecondParameter<typeof customInstance<TitanListExecutions200>>,) => {
      return customInstance<TitanListExecutions200>(
      {url: `/api/v1/titan/executions`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary getExecutionDetail
 */
export const titanGetExecutionDetail = (
    id: number,
 options?: SecondParameter<typeof customInstance<TitanGetExecutionDetail200>>,) => {
      return customInstance<TitanGetExecutionDetail200>(
      {url: `/api/v1/titan/executions/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary cancelExecution
 */
export const titanCancelExecution = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/executions/${id}/cancel`, method: 'POST'
    },
      options);
    }
  /**
 * @summary listIntegrations
 */
export const titanListIntegrations = (
    params: TitanListIntegrationsParams,
 options?: SecondParameter<typeof customInstance<TitanListIntegrations200>>,) => {
      return customInstance<TitanListIntegrations200>(
      {url: `/api/v1/titan/integrations`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary createIntegration
 */
export const titanCreateIntegration = (
    titanCreateIntegrationBody: TitanCreateIntegrationBody,
 options?: SecondParameter<typeof customInstance<TitanCreateIntegration200>>,) => {
      return customInstance<TitanCreateIntegration200>(
      {url: `/api/v1/titan/integrations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: titanCreateIntegrationBody
    },
      options);
    }
  /**
 * @summary deleteIntegration
 */
export const titanDeleteIntegration = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/integrations/${id}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary updateIntegration
 */
export const titanUpdateIntegration = (
    id: number,
    titanUpdateIntegrationBody: TitanUpdateIntegrationBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/integrations/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: titanUpdateIntegrationBody
    },
      options);
    }
  /**
 * @summary testIntegration
 */
export const titanTestIntegration = (
    id: number,
 options?: SecondParameter<typeof customInstance<TitanTestIntegration200>>,) => {
      return customInstance<TitanTestIntegration200>(
      {url: `/api/v1/titan/integrations/${id}/test`, method: 'POST'
    },
      options);
    }
  /**
 * @summary listPipelines
 */
export const titanListPipelines = (
    params: TitanListPipelinesParams,
 options?: SecondParameter<typeof customInstance<TitanListPipelines200>>,) => {
      return customInstance<TitanListPipelines200>(
      {url: `/api/v1/titan/pipelines`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary createPipeline
 */
export const titanCreatePipeline = (
    titanCreatePipelineBody: TitanCreatePipelineBody,
 options?: SecondParameter<typeof customInstance<TitanCreatePipeline200>>,) => {
      return customInstance<TitanCreatePipeline200>(
      {url: `/api/v1/titan/pipelines`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: titanCreatePipelineBody
    },
      options);
    }
  /**
 * @summary deletePipeline
 */
export const titanDeletePipeline = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/pipelines/${id}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary getPipeline
 */
export const titanGetPipeline = (
    id: number,
 options?: SecondParameter<typeof customInstance<TitanGetPipeline200>>,) => {
      return customInstance<TitanGetPipeline200>(
      {url: `/api/v1/titan/pipelines/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary updatePipeline
 */
export const titanUpdatePipeline = (
    id: number,
    titanUpdatePipelineBody: TitanUpdatePipelineBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/pipelines/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: titanUpdatePipelineBody
    },
      options);
    }
  /**
 * @summary triggerPipeline
 */
export const titanTriggerPipeline = (
    id: number,
    titanTriggerPipelineBody: TitanTriggerPipelineBody,
 options?: SecondParameter<typeof customInstance<TitanTriggerPipeline200>>,) => {
      return customInstance<TitanTriggerPipeline200>(
      {url: `/api/v1/titan/pipelines/${id}/trigger`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: titanTriggerPipelineBody
    },
      options);
    }
  /**
 * @summary approveStep
 */
export const titanApproveStep = (
    id: number,
    titanApproveStepBody: TitanApproveStepBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/titan/steps/${id}/approve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: titanApproveStepBody
    },
      options);
    }
  /**
 * @summary getStepLog
 */
export const titanGetStepLog = (
    id: number,
    params: TitanGetStepLogParams,
 options?: SecondParameter<typeof customInstance<TitanGetStepLog200>>,) => {
      return customInstance<TitanGetStepLog200>(
      {url: `/api/v1/titan/steps/${id}/log`, method: 'GET',
        params
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type TitanListClustersResult = NonNullable<Awaited<ReturnType<typeof titanListClusters>>>
export type TitanCreateClusterResult = NonNullable<Awaited<ReturnType<typeof titanCreateCluster>>>
export type TitanDeleteClusterResult = NonNullable<Awaited<ReturnType<typeof titanDeleteCluster>>>
export type TitanUpdateClusterResult = NonNullable<Awaited<ReturnType<typeof titanUpdateCluster>>>
export type TitanListNamespacesResult = NonNullable<Awaited<ReturnType<typeof titanListNamespaces>>>
export type TitanTestClusterResult = NonNullable<Awaited<ReturnType<typeof titanTestCluster>>>
export type TitanListExecutionsResult = NonNullable<Awaited<ReturnType<typeof titanListExecutions>>>
export type TitanGetExecutionDetailResult = NonNullable<Awaited<ReturnType<typeof titanGetExecutionDetail>>>
export type TitanCancelExecutionResult = NonNullable<Awaited<ReturnType<typeof titanCancelExecution>>>
export type TitanListIntegrationsResult = NonNullable<Awaited<ReturnType<typeof titanListIntegrations>>>
export type TitanCreateIntegrationResult = NonNullable<Awaited<ReturnType<typeof titanCreateIntegration>>>
export type TitanDeleteIntegrationResult = NonNullable<Awaited<ReturnType<typeof titanDeleteIntegration>>>
export type TitanUpdateIntegrationResult = NonNullable<Awaited<ReturnType<typeof titanUpdateIntegration>>>
export type TitanTestIntegrationResult = NonNullable<Awaited<ReturnType<typeof titanTestIntegration>>>
export type TitanListPipelinesResult = NonNullable<Awaited<ReturnType<typeof titanListPipelines>>>
export type TitanCreatePipelineResult = NonNullable<Awaited<ReturnType<typeof titanCreatePipeline>>>
export type TitanDeletePipelineResult = NonNullable<Awaited<ReturnType<typeof titanDeletePipeline>>>
export type TitanGetPipelineResult = NonNullable<Awaited<ReturnType<typeof titanGetPipeline>>>
export type TitanUpdatePipelineResult = NonNullable<Awaited<ReturnType<typeof titanUpdatePipeline>>>
export type TitanTriggerPipelineResult = NonNullable<Awaited<ReturnType<typeof titanTriggerPipeline>>>
export type TitanApproveStepResult = NonNullable<Awaited<ReturnType<typeof titanApproveStep>>>
export type TitanGetStepLogResult = NonNullable<Awaited<ReturnType<typeof titanGetStepLog>>>
