// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: titan.proto

package titan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_titan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_titan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{1}
}

func (x *PingReq) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_titan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{2}
}

func (x *PingResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// ----------------------
// 1. 集成凭证 (Integration)
// ----------------------
type IntegrationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	AuthType      string                 `protobuf:"bytes,4,opt,name=authType,proto3" json:"authType,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"` // 安全过滤后的配置 JSON
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,8,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreateTime    string                 `protobuf:"bytes,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationItem) Reset() {
	*x = IntegrationItem{}
	mi := &file_titan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationItem) ProtoMessage() {}

func (x *IntegrationItem) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationItem.ProtoReflect.Descriptor instead.
func (*IntegrationItem) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{3}
}

func (x *IntegrationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IntegrationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntegrationItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *IntegrationItem) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *IntegrationItem) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *IntegrationItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *IntegrationItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IntegrationItem) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *IntegrationItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *IntegrationItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type ListIntegrationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntegrationsReq) Reset() {
	*x = ListIntegrationsReq{}
	mi := &file_titan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntegrationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntegrationsReq) ProtoMessage() {}

func (x *ListIntegrationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntegrationsReq.ProtoReflect.Descriptor instead.
func (*ListIntegrationsReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{4}
}

func (x *ListIntegrationsReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListIntegrationsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIntegrationsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListIntegrationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*IntegrationItem     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntegrationsResp) Reset() {
	*x = ListIntegrationsResp{}
	mi := &file_titan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntegrationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntegrationsResp) ProtoMessage() {}

func (x *ListIntegrationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntegrationsResp.ProtoReflect.Descriptor instead.
func (*ListIntegrationsResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{5}
}

func (x *ListIntegrationsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListIntegrationsResp) GetList() []*IntegrationItem {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateIntegrationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	AuthType      string                 `protobuf:"bytes,3,opt,name=authType,proto3" json:"authType,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"` // 原始配置 JSON（由服务端加密存储）
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntegrationReq) Reset() {
	*x = CreateIntegrationReq{}
	mi := &file_titan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntegrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntegrationReq) ProtoMessage() {}

func (x *CreateIntegrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntegrationReq.ProtoReflect.Descriptor instead.
func (*CreateIntegrationReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{6}
}

func (x *CreateIntegrationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIntegrationReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateIntegrationReq) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *CreateIntegrationReq) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CreateIntegrationReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIntegrationReq) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreateIntegrationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntegrationResp) Reset() {
	*x = CreateIntegrationResp{}
	mi := &file_titan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntegrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntegrationResp) ProtoMessage() {}

func (x *CreateIntegrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntegrationResp.ProtoReflect.Descriptor instead.
func (*CreateIntegrationResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{7}
}

func (x *CreateIntegrationResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateIntegrationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthType      string                 `protobuf:"bytes,3,opt,name=authType,proto3" json:"authType,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIntegrationReq) Reset() {
	*x = UpdateIntegrationReq{}
	mi := &file_titan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIntegrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIntegrationReq) ProtoMessage() {}

func (x *UpdateIntegrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIntegrationReq.ProtoReflect.Descriptor instead.
func (*UpdateIntegrationReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateIntegrationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateIntegrationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateIntegrationReq) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *UpdateIntegrationReq) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *UpdateIntegrationReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateIntegrationReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteIntegrationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIntegrationReq) Reset() {
	*x = DeleteIntegrationReq{}
	mi := &file_titan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIntegrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIntegrationReq) ProtoMessage() {}

func (x *DeleteIntegrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIntegrationReq.ProtoReflect.Descriptor instead.
func (*DeleteIntegrationReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteIntegrationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TestIntegrationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIntegrationReq) Reset() {
	*x = TestIntegrationReq{}
	mi := &file_titan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIntegrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIntegrationReq) ProtoMessage() {}

func (x *TestIntegrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIntegrationReq.ProtoReflect.Descriptor instead.
func (*TestIntegrationReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{10}
}

func (x *TestIntegrationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TestIntegrationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIntegrationResp) Reset() {
	*x = TestIntegrationResp{}
	mi := &file_titan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIntegrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIntegrationResp) ProtoMessage() {}

func (x *TestIntegrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIntegrationResp.ProtoReflect.Descriptor instead.
func (*TestIntegrationResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{11}
}

func (x *TestIntegrationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestIntegrationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ----------------------
// 2. Kubernetes 集群 (Cluster)
// ----------------------
type ClusterItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	ApiEndpoint   string                 `protobuf:"bytes,4,opt,name=apiEndpoint,proto3" json:"apiEndpoint,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,8,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreateTime    string                 `protobuf:"bytes,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterItem) Reset() {
	*x = ClusterItem{}
	mi := &file_titan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterItem) ProtoMessage() {}

func (x *ClusterItem) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterItem.ProtoReflect.Descriptor instead.
func (*ClusterItem) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{12}
}

func (x *ClusterItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClusterItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterItem) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *ClusterItem) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *ClusterItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClusterItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClusterItem) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *ClusterItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *ClusterItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type ListClustersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersReq) Reset() {
	*x = ListClustersReq{}
	mi := &file_titan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersReq) ProtoMessage() {}

func (x *ListClustersReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersReq.ProtoReflect.Descriptor instead.
func (*ListClustersReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{13}
}

func (x *ListClustersReq) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *ListClustersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListClustersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListClustersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*ClusterItem         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResp) Reset() {
	*x = ListClustersResp{}
	mi := &file_titan_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResp) ProtoMessage() {}

func (x *ListClustersResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResp.ProtoReflect.Descriptor instead.
func (*ListClustersResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{14}
}

func (x *ListClustersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListClustersResp) GetList() []*ClusterItem {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateClusterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	ApiEndpoint   string                 `protobuf:"bytes,3,opt,name=apiEndpoint,proto3" json:"apiEndpoint,omitempty"`
	Kubeconfig    string                 `protobuf:"bytes,4,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"` // Kubeconfig 文本
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterReq) Reset() {
	*x = CreateClusterReq{}
	mi := &file_titan_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterReq) ProtoMessage() {}

func (x *CreateClusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterReq.ProtoReflect.Descriptor instead.
func (*CreateClusterReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{15}
}

func (x *CreateClusterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterReq) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *CreateClusterReq) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *CreateClusterReq) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *CreateClusterReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateClusterReq) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreateClusterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterResp) Reset() {
	*x = CreateClusterResp{}
	mi := &file_titan_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterResp) ProtoMessage() {}

func (x *CreateClusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterResp.ProtoReflect.Descriptor instead.
func (*CreateClusterResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{16}
}

func (x *CreateClusterResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateClusterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	ApiEndpoint   string                 `protobuf:"bytes,4,opt,name=apiEndpoint,proto3" json:"apiEndpoint,omitempty"`
	Kubeconfig    string                 `protobuf:"bytes,5,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterReq) Reset() {
	*x = UpdateClusterReq{}
	mi := &file_titan_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterReq) ProtoMessage() {}

func (x *UpdateClusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterReq.ProtoReflect.Descriptor instead.
func (*UpdateClusterReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateClusterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateClusterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClusterReq) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *UpdateClusterReq) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *UpdateClusterReq) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *UpdateClusterReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteClusterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterReq) Reset() {
	*x = DeleteClusterReq{}
	mi := &file_titan_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterReq) ProtoMessage() {}

func (x *DeleteClusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterReq.ProtoReflect.Descriptor instead.
func (*DeleteClusterReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteClusterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TestClusterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestClusterReq) Reset() {
	*x = TestClusterReq{}
	mi := &file_titan_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestClusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestClusterReq) ProtoMessage() {}

func (x *TestClusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestClusterReq.ProtoReflect.Descriptor instead.
func (*TestClusterReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{19}
}

func (x *TestClusterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TestClusterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestClusterResp) Reset() {
	*x = TestClusterResp{}
	mi := &file_titan_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestClusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestClusterResp) ProtoMessage() {}

func (x *TestClusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestClusterResp.ProtoReflect.Descriptor instead.
func (*TestClusterResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{20}
}

func (x *TestClusterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestClusterResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TestClusterResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListNamespacesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     int64                  `protobuf:"varint,1,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesReq) Reset() {
	*x = ListNamespacesReq{}
	mi := &file_titan_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesReq) ProtoMessage() {}

func (x *ListNamespacesReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesReq.ProtoReflect.Descriptor instead.
func (*ListNamespacesReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{21}
}

func (x *ListNamespacesReq) GetClusterId() int64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

type ListNamespacesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResp) Reset() {
	*x = ListNamespacesResp{}
	mi := &file_titan_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResp) ProtoMessage() {}

func (x *ListNamespacesResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResp.ProtoReflect.Descriptor instead.
func (*ListNamespacesResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{22}
}

func (x *ListNamespacesResp) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// ----------------------
// 3. 流水线定义 (Pipeline)
// ----------------------
type PipelineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	GitRepo       string                 `protobuf:"bytes,5,opt,name=gitRepo,proto3" json:"gitRepo,omitempty"`
	GitBranch     string                 `protobuf:"bytes,6,opt,name=gitBranch,proto3" json:"gitBranch,omitempty"`
	Stages        string                 `protobuf:"bytes,7,opt,name=stages,proto3" json:"stages,omitempty"`     // JSON DSL
	Params        string                 `protobuf:"bytes,8,opt,name=params,proto3" json:"params,omitempty"`     // JSON
	Triggers      string                 `protobuf:"bytes,9,opt,name=triggers,proto3" json:"triggers,omitempty"` // JSON
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,12,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreateTime    string                 `protobuf:"bytes,13,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,14,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineItem) Reset() {
	*x = PipelineItem{}
	mi := &file_titan_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineItem) ProtoMessage() {}

func (x *PipelineItem) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineItem.ProtoReflect.Descriptor instead.
func (*PipelineItem) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{23}
}

func (x *PipelineItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PipelineItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipelineItem) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PipelineItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PipelineItem) GetGitRepo() string {
	if x != nil {
		return x.GitRepo
	}
	return ""
}

func (x *PipelineItem) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *PipelineItem) GetStages() string {
	if x != nil {
		return x.Stages
	}
	return ""
}

func (x *PipelineItem) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *PipelineItem) GetTriggers() string {
	if x != nil {
		return x.Triggers
	}
	return ""
}

func (x *PipelineItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PipelineItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PipelineItem) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *PipelineItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *PipelineItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type ListPipelinesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesReq) Reset() {
	*x = ListPipelinesReq{}
	mi := &file_titan_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesReq) ProtoMessage() {}

func (x *ListPipelinesReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesReq.ProtoReflect.Descriptor instead.
func (*ListPipelinesReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{24}
}

func (x *ListPipelinesReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListPipelinesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListPipelinesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPipelinesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPipelinesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*PipelineItem        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesResp) Reset() {
	*x = ListPipelinesResp{}
	mi := &file_titan_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesResp) ProtoMessage() {}

func (x *ListPipelinesResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesResp.ProtoReflect.Descriptor instead.
func (*ListPipelinesResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{25}
}

func (x *ListPipelinesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPipelinesResp) GetList() []*PipelineItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetPipelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineReq) Reset() {
	*x = GetPipelineReq{}
	mi := &file_titan_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineReq) ProtoMessage() {}

func (x *GetPipelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineReq.ProtoReflect.Descriptor instead.
func (*GetPipelineReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{26}
}

func (x *GetPipelineReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PipelineDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *PipelineItem          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineDetailResp) Reset() {
	*x = PipelineDetailResp{}
	mi := &file_titan_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineDetailResp) ProtoMessage() {}

func (x *PipelineDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineDetailResp.ProtoReflect.Descriptor instead.
func (*PipelineDetailResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{27}
}

func (x *PipelineDetailResp) GetPipeline() *PipelineItem {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type CreatePipelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	GitRepo       string                 `protobuf:"bytes,4,opt,name=gitRepo,proto3" json:"gitRepo,omitempty"`
	GitBranch     string                 `protobuf:"bytes,5,opt,name=gitBranch,proto3" json:"gitBranch,omitempty"`
	Stages        string                 `protobuf:"bytes,6,opt,name=stages,proto3" json:"stages,omitempty"`
	Params        string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Triggers      string                 `protobuf:"bytes,8,opt,name=triggers,proto3" json:"triggers,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,10,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineReq) Reset() {
	*x = CreatePipelineReq{}
	mi := &file_titan_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineReq) ProtoMessage() {}

func (x *CreatePipelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineReq.ProtoReflect.Descriptor instead.
func (*CreatePipelineReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{28}
}

func (x *CreatePipelineReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePipelineReq) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreatePipelineReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreatePipelineReq) GetGitRepo() string {
	if x != nil {
		return x.GitRepo
	}
	return ""
}

func (x *CreatePipelineReq) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *CreatePipelineReq) GetStages() string {
	if x != nil {
		return x.Stages
	}
	return ""
}

func (x *CreatePipelineReq) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *CreatePipelineReq) GetTriggers() string {
	if x != nil {
		return x.Triggers
	}
	return ""
}

func (x *CreatePipelineReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePipelineReq) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreatePipelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineResp) Reset() {
	*x = CreatePipelineResp{}
	mi := &file_titan_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineResp) ProtoMessage() {}

func (x *CreatePipelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineResp.ProtoReflect.Descriptor instead.
func (*CreatePipelineResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{29}
}

func (x *CreatePipelineResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdatePipelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	GitRepo       string                 `protobuf:"bytes,4,opt,name=gitRepo,proto3" json:"gitRepo,omitempty"`
	GitBranch     string                 `protobuf:"bytes,5,opt,name=gitBranch,proto3" json:"gitBranch,omitempty"`
	Stages        string                 `protobuf:"bytes,6,opt,name=stages,proto3" json:"stages,omitempty"`
	Params        string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Triggers      string                 `protobuf:"bytes,8,opt,name=triggers,proto3" json:"triggers,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineReq) Reset() {
	*x = UpdatePipelineReq{}
	mi := &file_titan_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineReq) ProtoMessage() {}

func (x *UpdatePipelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineReq.ProtoReflect.Descriptor instead.
func (*UpdatePipelineReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{30}
}

func (x *UpdatePipelineReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePipelineReq) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdatePipelineReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdatePipelineReq) GetGitRepo() string {
	if x != nil {
		return x.GitRepo
	}
	return ""
}

func (x *UpdatePipelineReq) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *UpdatePipelineReq) GetStages() string {
	if x != nil {
		return x.Stages
	}
	return ""
}

func (x *UpdatePipelineReq) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *UpdatePipelineReq) GetTriggers() string {
	if x != nil {
		return x.Triggers
	}
	return ""
}

func (x *UpdatePipelineReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdatePipelineReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeletePipelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePipelineReq) Reset() {
	*x = DeletePipelineReq{}
	mi := &file_titan_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePipelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePipelineReq) ProtoMessage() {}

func (x *DeletePipelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePipelineReq.ProtoReflect.Descriptor instead.
func (*DeletePipelineReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{31}
}

func (x *DeletePipelineReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ----------------------
// 4. 执行实例 (Execution)
// ----------------------
type TriggerPipelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    int64                  `protobuf:"varint,1,opt,name=pipelineId,proto3" json:"pipelineId,omitempty"`
	TriggerType   string                 `protobuf:"bytes,2,opt,name=triggerType,proto3" json:"triggerType,omitempty"` // MANUAL / WEBHOOK
	TriggerBy     int64                  `protobuf:"varint,3,opt,name=triggerBy,proto3" json:"triggerBy,omitempty"`
	GitBranch     string                 `protobuf:"bytes,4,opt,name=gitBranch,proto3" json:"gitBranch,omitempty"`
	GitCommit     string                 `protobuf:"bytes,5,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	RuntimeParams string                 `protobuf:"bytes,6,opt,name=runtimeParams,proto3" json:"runtimeParams,omitempty"` // JSON key-value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerPipelineReq) Reset() {
	*x = TriggerPipelineReq{}
	mi := &file_titan_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPipelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPipelineReq) ProtoMessage() {}

func (x *TriggerPipelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPipelineReq.ProtoReflect.Descriptor instead.
func (*TriggerPipelineReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{32}
}

func (x *TriggerPipelineReq) GetPipelineId() int64 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *TriggerPipelineReq) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *TriggerPipelineReq) GetTriggerBy() int64 {
	if x != nil {
		return x.TriggerBy
	}
	return 0
}

func (x *TriggerPipelineReq) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *TriggerPipelineReq) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *TriggerPipelineReq) GetRuntimeParams() string {
	if x != nil {
		return x.RuntimeParams
	}
	return ""
}

type TriggerPipelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        int64                  `protobuf:"varint,1,opt,name=execId,proto3" json:"execId,omitempty"`
	ExecNo        string                 `protobuf:"bytes,2,opt,name=execNo,proto3" json:"execNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerPipelineResp) Reset() {
	*x = TriggerPipelineResp{}
	mi := &file_titan_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPipelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPipelineResp) ProtoMessage() {}

func (x *TriggerPipelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPipelineResp.ProtoReflect.Descriptor instead.
func (*TriggerPipelineResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{33}
}

func (x *TriggerPipelineResp) GetExecId() int64 {
	if x != nil {
		return x.ExecId
	}
	return 0
}

func (x *TriggerPipelineResp) GetExecNo() string {
	if x != nil {
		return x.ExecNo
	}
	return ""
}

type ExecutionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId    int64                  `protobuf:"varint,2,opt,name=pipelineId,proto3" json:"pipelineId,omitempty"`
	PipelineName  string                 `protobuf:"bytes,3,opt,name=pipelineName,proto3" json:"pipelineName,omitempty"`
	ExecNo        string                 `protobuf:"bytes,4,opt,name=execNo,proto3" json:"execNo,omitempty"`
	TriggerType   string                 `protobuf:"bytes,5,opt,name=triggerType,proto3" json:"triggerType,omitempty"`
	TriggerBy     int64                  `protobuf:"varint,6,opt,name=triggerBy,proto3" json:"triggerBy,omitempty"`
	GitBranch     string                 `protobuf:"bytes,7,opt,name=gitBranch,proto3" json:"gitBranch,omitempty"`
	GitCommit     string                 `protobuf:"bytes,8,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	RuntimeParams string                 `protobuf:"bytes,9,opt,name=runtimeParams,proto3" json:"runtimeParams,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,11,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	StartTime     string                 `protobuf:"bytes,12,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,13,opt,name=endTime,proto3" json:"endTime,omitempty"`
	DurationMs    int64                  `protobuf:"varint,14,opt,name=durationMs,proto3" json:"durationMs,omitempty"`
	Artifacts     string                 `protobuf:"bytes,15,opt,name=artifacts,proto3" json:"artifacts,omitempty"`
	CreateTime    string                 `protobuf:"bytes,16,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionItem) Reset() {
	*x = ExecutionItem{}
	mi := &file_titan_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionItem) ProtoMessage() {}

func (x *ExecutionItem) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionItem.ProtoReflect.Descriptor instead.
func (*ExecutionItem) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{34}
}

func (x *ExecutionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecutionItem) GetPipelineId() int64 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *ExecutionItem) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *ExecutionItem) GetExecNo() string {
	if x != nil {
		return x.ExecNo
	}
	return ""
}

func (x *ExecutionItem) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *ExecutionItem) GetTriggerBy() int64 {
	if x != nil {
		return x.TriggerBy
	}
	return 0
}

func (x *ExecutionItem) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *ExecutionItem) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *ExecutionItem) GetRuntimeParams() string {
	if x != nil {
		return x.RuntimeParams
	}
	return ""
}

func (x *ExecutionItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionItem) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecutionItem) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ExecutionItem) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ExecutionItem) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecutionItem) GetArtifacts() string {
	if x != nil {
		return x.Artifacts
	}
	return ""
}

func (x *ExecutionItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type StepExecItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecId        int64                  `protobuf:"varint,2,opt,name=execId,proto3" json:"execId,omitempty"`
	StageId       string                 `protobuf:"bytes,3,opt,name=stageId,proto3" json:"stageId,omitempty"`
	StepId        string                 `protobuf:"bytes,4,opt,name=stepId,proto3" json:"stepId,omitempty"`
	StepName      string                 `protobuf:"bytes,5,opt,name=stepName,proto3" json:"stepName,omitempty"`
	StepType      string                 `protobuf:"bytes,6,opt,name=stepType,proto3" json:"stepType,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	LogPath       string                 `protobuf:"bytes,8,opt,name=logPath,proto3" json:"logPath,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,9,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	StartTime     string                 `protobuf:"bytes,10,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,11,opt,name=endTime,proto3" json:"endTime,omitempty"`
	DurationMs    int64                  `protobuf:"varint,12,opt,name=durationMs,proto3" json:"durationMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecItem) Reset() {
	*x = StepExecItem{}
	mi := &file_titan_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecItem) ProtoMessage() {}

func (x *StepExecItem) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecItem.ProtoReflect.Descriptor instead.
func (*StepExecItem) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{35}
}

func (x *StepExecItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StepExecItem) GetExecId() int64 {
	if x != nil {
		return x.ExecId
	}
	return 0
}

func (x *StepExecItem) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StepExecItem) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepExecItem) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepExecItem) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *StepExecItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepExecItem) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *StepExecItem) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *StepExecItem) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *StepExecItem) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *StepExecItem) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ListExecutionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    int64                  `protobuf:"varint,1,opt,name=pipelineId,proto3" json:"pipelineId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsReq) Reset() {
	*x = ListExecutionsReq{}
	mi := &file_titan_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsReq) ProtoMessage() {}

func (x *ListExecutionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsReq.ProtoReflect.Descriptor instead.
func (*ListExecutionsReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{36}
}

func (x *ListExecutionsReq) GetPipelineId() int64 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *ListExecutionsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListExecutionsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExecutionsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListExecutionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*ExecutionItem       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResp) Reset() {
	*x = ListExecutionsResp{}
	mi := &file_titan_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResp) ProtoMessage() {}

func (x *ListExecutionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResp.ProtoReflect.Descriptor instead.
func (*ListExecutionsResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{37}
}

func (x *ListExecutionsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListExecutionsResp) GetList() []*ExecutionItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetExecutionDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        int64                  `protobuf:"varint,1,opt,name=execId,proto3" json:"execId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionDetailReq) Reset() {
	*x = GetExecutionDetailReq{}
	mi := &file_titan_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionDetailReq) ProtoMessage() {}

func (x *GetExecutionDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionDetailReq.ProtoReflect.Descriptor instead.
func (*GetExecutionDetailReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{38}
}

func (x *GetExecutionDetailReq) GetExecId() int64 {
	if x != nil {
		return x.ExecId
	}
	return 0
}

type ExecutionDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *ExecutionItem         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	Steps         []*StepExecItem        `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionDetailResp) Reset() {
	*x = ExecutionDetailResp{}
	mi := &file_titan_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionDetailResp) ProtoMessage() {}

func (x *ExecutionDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionDetailResp.ProtoReflect.Descriptor instead.
func (*ExecutionDetailResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{39}
}

func (x *ExecutionDetailResp) GetExecution() *ExecutionItem {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *ExecutionDetailResp) GetSteps() []*StepExecItem {
	if x != nil {
		return x.Steps
	}
	return nil
}

type GetStepLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepExecId    int64                  `protobuf:"varint,1,opt,name=stepExecId,proto3" json:"stepExecId,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStepLogReq) Reset() {
	*x = GetStepLogReq{}
	mi := &file_titan_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStepLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStepLogReq) ProtoMessage() {}

func (x *GetStepLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStepLogReq.ProtoReflect.Descriptor instead.
func (*GetStepLogReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{40}
}

func (x *GetStepLogReq) GetStepExecId() int64 {
	if x != nil {
		return x.StepExecId
	}
	return 0
}

func (x *GetStepLogReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetStepLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	NextOffset    int64                  `protobuf:"varint,2,opt,name=nextOffset,proto3" json:"nextOffset,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStepLogResp) Reset() {
	*x = GetStepLogResp{}
	mi := &file_titan_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStepLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStepLogResp) ProtoMessage() {}

func (x *GetStepLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStepLogResp.ProtoReflect.Descriptor instead.
func (*GetStepLogResp) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{41}
}

func (x *GetStepLogResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetStepLogResp) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *GetStepLogResp) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type ApproveStepReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepExecId    int64                  `protobuf:"varint,1,opt,name=stepExecId,proto3" json:"stepExecId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveStepReq) Reset() {
	*x = ApproveStepReq{}
	mi := &file_titan_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveStepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveStepReq) ProtoMessage() {}

func (x *ApproveStepReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveStepReq.ProtoReflect.Descriptor instead.
func (*ApproveStepReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{42}
}

func (x *ApproveStepReq) GetStepExecId() int64 {
	if x != nil {
		return x.StepExecId
	}
	return 0
}

func (x *ApproveStepReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApproveStepReq) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApproveStepReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CancelExecutionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        int64                  `protobuf:"varint,1,opt,name=execId,proto3" json:"execId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionReq) Reset() {
	*x = CancelExecutionReq{}
	mi := &file_titan_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionReq) ProtoMessage() {}

func (x *CancelExecutionReq) ProtoReflect() protoreflect.Message {
	mi := &file_titan_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionReq.ProtoReflect.Descriptor instead.
func (*CancelExecutionReq) Descriptor() ([]byte, []int) {
	return file_titan_proto_rawDescGZIP(), []int{43}
}

func (x *CancelExecutionReq) GetExecId() int64 {
	if x != nil {
		return x.ExecId
	}
	return 0
}

func (x *CancelExecutionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_titan_proto protoreflect.FileDescriptor

const file_titan_proto_rawDesc = "" +
	"\n" +
	"\vtitan.proto\x12\x05titan\"2\n" +
	"\n" +
	"CommonResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1d\n" +
	"\aPingReq\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bPingResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\x9d\x02\n" +
	"\x0fIntegrationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\bauthType\x18\x04 \x01(\tR\bauthType\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedBy\x18\b \x01(\x03R\tcreatedBy\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\n" +
	" \x01(\tR\n" +
	"updateTime\"a\n" +
	"\x13ListIntegrationsReq\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"X\n" +
	"\x14ListIntegrationsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.titan.IntegrationItemR\x04list\"\xba\x01\n" +
	"\x14CreateIntegrationReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\bauthType\x18\x03 \x01(\tR\bauthType\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedBy\x18\x06 \x01(\x03R\tcreatedBy\"'\n" +
	"\x15CreateIntegrationResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa8\x01\n" +
	"\x14UpdateIntegrationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bauthType\x18\x03 \x01(\tR\bauthType\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"&\n" +
	"\x14DeleteIntegrationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12TestIntegrationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x13TestIntegrationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x97\x02\n" +
	"\vClusterItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12 \n" +
	"\vapiEndpoint\x18\x04 \x01(\tR\vapiEndpoint\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedBy\x18\b \x01(\x03R\tcreatedBy\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\n" +
	" \x01(\tR\n" +
	"updateTime\"S\n" +
	"\x0fListClustersReq\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"P\n" +
	"\x10ListClustersResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12&\n" +
	"\x04list\x18\x02 \x03(\v2\x12.titan.ClusterItemR\x04list\"\xba\x01\n" +
	"\x10CreateClusterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12 \n" +
	"\vapiEndpoint\x18\x03 \x01(\tR\vapiEndpoint\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x04 \x01(\tR\n" +
	"kubeconfig\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedBy\x18\x06 \x01(\x03R\tcreatedBy\"#\n" +
	"\x11CreateClusterResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xac\x01\n" +
	"\x10UpdateClusterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12 \n" +
	"\vapiEndpoint\x18\x04 \x01(\tR\vapiEndpoint\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x05 \x01(\tR\n" +
	"kubeconfig\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\"\n" +
	"\x10DeleteClusterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\" \n" +
	"\x0eTestClusterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\x0fTestClusterResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"1\n" +
	"\x11ListNamespacesReq\x12\x1c\n" +
	"\tclusterId\x18\x01 \x01(\x03R\tclusterId\"4\n" +
	"\x12ListNamespacesResp\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\"\x8c\x03\n" +
	"\fPipelineItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdisplayName\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\agitRepo\x18\x05 \x01(\tR\agitRepo\x12\x1c\n" +
	"\tgitBranch\x18\x06 \x01(\tR\tgitBranch\x12\x16\n" +
	"\x06stages\x18\a \x01(\tR\x06stages\x12\x16\n" +
	"\x06params\x18\b \x01(\tR\x06params\x12\x1a\n" +
	"\btriggers\x18\t \x01(\tR\btriggers\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedBy\x18\f \x01(\x03R\tcreatedBy\x12\x1e\n" +
	"\n" +
	"createTime\x18\r \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x0e \x01(\tR\n" +
	"updateTime\"x\n" +
	"\x10ListPipelinesReq\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"R\n" +
	"\x11ListPipelinesResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12'\n" +
	"\x04list\x18\x02 \x03(\v2\x13.titan.PipelineItemR\x04list\" \n" +
	"\x0eGetPipelineReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x12PipelineDetailResp\x12/\n" +
	"\bpipeline\x18\x01 \x01(\v2\x13.titan.PipelineItemR\bpipeline\"\xa9\x02\n" +
	"\x11CreatePipelineReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\agitRepo\x18\x04 \x01(\tR\agitRepo\x12\x1c\n" +
	"\tgitBranch\x18\x05 \x01(\tR\tgitBranch\x12\x16\n" +
	"\x06stages\x18\x06 \x01(\tR\x06stages\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12\x1a\n" +
	"\btriggers\x18\b \x01(\tR\btriggers\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedBy\x18\n" +
	" \x01(\x03R\tcreatedBy\"$\n" +
	"\x12CreatePipelineResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9f\x02\n" +
	"\x11UpdatePipelineReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\agitRepo\x18\x04 \x01(\tR\agitRepo\x12\x1c\n" +
	"\tgitBranch\x18\x05 \x01(\tR\tgitBranch\x12\x16\n" +
	"\x06stages\x18\x06 \x01(\tR\x06stages\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12\x1a\n" +
	"\btriggers\x18\b \x01(\tR\btriggers\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"#\n" +
	"\x11DeletePipelineReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd6\x01\n" +
	"\x12TriggerPipelineReq\x12\x1e\n" +
	"\n" +
	"pipelineId\x18\x01 \x01(\x03R\n" +
	"pipelineId\x12 \n" +
	"\vtriggerType\x18\x02 \x01(\tR\vtriggerType\x12\x1c\n" +
	"\ttriggerBy\x18\x03 \x01(\x03R\ttriggerBy\x12\x1c\n" +
	"\tgitBranch\x18\x04 \x01(\tR\tgitBranch\x12\x1c\n" +
	"\tgitCommit\x18\x05 \x01(\tR\tgitCommit\x12$\n" +
	"\rruntimeParams\x18\x06 \x01(\tR\rruntimeParams\"E\n" +
	"\x13TriggerPipelineResp\x12\x16\n" +
	"\x06execId\x18\x01 \x01(\x03R\x06execId\x12\x16\n" +
	"\x06execNo\x18\x02 \x01(\tR\x06execNo\"\xeb\x03\n" +
	"\rExecutionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"pipelineId\x18\x02 \x01(\x03R\n" +
	"pipelineId\x12\"\n" +
	"\fpipelineName\x18\x03 \x01(\tR\fpipelineName\x12\x16\n" +
	"\x06execNo\x18\x04 \x01(\tR\x06execNo\x12 \n" +
	"\vtriggerType\x18\x05 \x01(\tR\vtriggerType\x12\x1c\n" +
	"\ttriggerBy\x18\x06 \x01(\x03R\ttriggerBy\x12\x1c\n" +
	"\tgitBranch\x18\a \x01(\tR\tgitBranch\x12\x1c\n" +
	"\tgitCommit\x18\b \x01(\tR\tgitCommit\x12$\n" +
	"\rruntimeParams\x18\t \x01(\tR\rruntimeParams\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"workflowId\x18\v \x01(\tR\n" +
	"workflowId\x12\x1c\n" +
	"\tstartTime\x18\f \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\r \x01(\tR\aendTime\x12\x1e\n" +
	"\n" +
	"durationMs\x18\x0e \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\tartifacts\x18\x0f \x01(\tR\tartifacts\x12\x1e\n" +
	"\n" +
	"createTime\x18\x10 \x01(\tR\n" +
	"createTime\"\xc6\x02\n" +
	"\fStepExecItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06execId\x18\x02 \x01(\x03R\x06execId\x12\x18\n" +
	"\astageId\x18\x03 \x01(\tR\astageId\x12\x16\n" +
	"\x06stepId\x18\x04 \x01(\tR\x06stepId\x12\x1a\n" +
	"\bstepName\x18\x05 \x01(\tR\bstepName\x12\x1a\n" +
	"\bstepType\x18\x06 \x01(\tR\bstepType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\alogPath\x18\b \x01(\tR\alogPath\x12\x1a\n" +
	"\berrorMsg\x18\t \x01(\tR\berrorMsg\x12\x1c\n" +
	"\tstartTime\x18\n" +
	" \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\v \x01(\tR\aendTime\x12\x1e\n" +
	"\n" +
	"durationMs\x18\f \x01(\x03R\n" +
	"durationMs\"{\n" +
	"\x11ListExecutionsReq\x12\x1e\n" +
	"\n" +
	"pipelineId\x18\x01 \x01(\x03R\n" +
	"pipelineId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"T\n" +
	"\x12ListExecutionsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.titan.ExecutionItemR\x04list\"/\n" +
	"\x15GetExecutionDetailReq\x12\x16\n" +
	"\x06execId\x18\x01 \x01(\x03R\x06execId\"t\n" +
	"\x13ExecutionDetailResp\x122\n" +
	"\texecution\x18\x01 \x01(\v2\x14.titan.ExecutionItemR\texecution\x12)\n" +
	"\x05steps\x18\x02 \x03(\v2\x13.titan.StepExecItemR\x05steps\"G\n" +
	"\rGetStepLogReq\x12\x1e\n" +
	"\n" +
	"stepExecId\x18\x01 \x01(\x03R\n" +
	"stepExecId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"`\n" +
	"\x0eGetStepLogResp\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"nextOffset\x18\x02 \x01(\x03R\n" +
	"nextOffset\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"~\n" +
	"\x0eApproveStepReq\x12\x1e\n" +
	"\n" +
	"stepExecId\x18\x01 \x01(\x03R\n" +
	"stepExecId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"D\n" +
	"\x12CancelExecutionReq\x12\x16\n" +
	"\x06execId\x18\x01 \x01(\x03R\x06execId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId2\x85\f\n" +
	"\x05titan\x12'\n" +
	"\x04Ping\x12\x0e.titan.PingReq\x1a\x0f.titan.PingResp\x12K\n" +
	"\x10ListIntegrations\x12\x1a.titan.ListIntegrationsReq\x1a\x1b.titan.ListIntegrationsResp\x12N\n" +
	"\x11CreateIntegration\x12\x1b.titan.CreateIntegrationReq\x1a\x1c.titan.CreateIntegrationResp\x12C\n" +
	"\x11UpdateIntegration\x12\x1b.titan.UpdateIntegrationReq\x1a\x11.titan.CommonResp\x12C\n" +
	"\x11DeleteIntegration\x12\x1b.titan.DeleteIntegrationReq\x1a\x11.titan.CommonResp\x12H\n" +
	"\x0fTestIntegration\x12\x19.titan.TestIntegrationReq\x1a\x1a.titan.TestIntegrationResp\x12?\n" +
	"\fListClusters\x12\x16.titan.ListClustersReq\x1a\x17.titan.ListClustersResp\x12B\n" +
	"\rCreateCluster\x12\x17.titan.CreateClusterReq\x1a\x18.titan.CreateClusterResp\x12;\n" +
	"\rUpdateCluster\x12\x17.titan.UpdateClusterReq\x1a\x11.titan.CommonResp\x12;\n" +
	"\rDeleteCluster\x12\x17.titan.DeleteClusterReq\x1a\x11.titan.CommonResp\x12<\n" +
	"\vTestCluster\x12\x15.titan.TestClusterReq\x1a\x16.titan.TestClusterResp\x12E\n" +
	"\x0eListNamespaces\x12\x18.titan.ListNamespacesReq\x1a\x19.titan.ListNamespacesResp\x12B\n" +
	"\rListPipelines\x12\x17.titan.ListPipelinesReq\x1a\x18.titan.ListPipelinesResp\x12?\n" +
	"\vGetPipeline\x12\x15.titan.GetPipelineReq\x1a\x19.titan.PipelineDetailResp\x12E\n" +
	"\x0eCreatePipeline\x12\x18.titan.CreatePipelineReq\x1a\x19.titan.CreatePipelineResp\x12=\n" +
	"\x0eUpdatePipeline\x12\x18.titan.UpdatePipelineReq\x1a\x11.titan.CommonResp\x12=\n" +
	"\x0eDeletePipeline\x12\x18.titan.DeletePipelineReq\x1a\x11.titan.CommonResp\x12H\n" +
	"\x0fTriggerPipeline\x12\x19.titan.TriggerPipelineReq\x1a\x1a.titan.TriggerPipelineResp\x12E\n" +
	"\x0eListExecutions\x12\x18.titan.ListExecutionsReq\x1a\x19.titan.ListExecutionsResp\x12N\n" +
	"\x12GetExecutionDetail\x12\x1c.titan.GetExecutionDetailReq\x1a\x1a.titan.ExecutionDetailResp\x129\n" +
	"\n" +
	"GetStepLog\x12\x14.titan.GetStepLogReq\x1a\x15.titan.GetStepLogResp\x127\n" +
	"\vApproveStep\x12\x15.titan.ApproveStepReq\x1a\x11.titan.CommonResp\x12?\n" +
	"\x0fCancelExecution\x12\x19.titan.CancelExecutionReq\x1a\x11.titan.CommonRespB\tZ\a./titanb\x06proto3"

var (
	file_titan_proto_rawDescOnce sync.Once
	file_titan_proto_rawDescData []byte
)

func file_titan_proto_rawDescGZIP() []byte {
	file_titan_proto_rawDescOnce.Do(func() {
		file_titan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_titan_proto_rawDesc), len(file_titan_proto_rawDesc)))
	})
	return file_titan_proto_rawDescData
}

var file_titan_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_titan_proto_goTypes = []any{
	(*CommonResp)(nil),            // 0: titan.CommonResp
	(*PingReq)(nil),               // 1: titan.PingReq
	(*PingResp)(nil),              // 2: titan.PingResp
	(*IntegrationItem)(nil),       // 3: titan.IntegrationItem
	(*ListIntegrationsReq)(nil),   // 4: titan.ListIntegrationsReq
	(*ListIntegrationsResp)(nil),  // 5: titan.ListIntegrationsResp
	(*CreateIntegrationReq)(nil),  // 6: titan.CreateIntegrationReq
	(*CreateIntegrationResp)(nil), // 7: titan.CreateIntegrationResp
	(*UpdateIntegrationReq)(nil),  // 8: titan.UpdateIntegrationReq
	(*DeleteIntegrationReq)(nil),  // 9: titan.DeleteIntegrationReq
	(*TestIntegrationReq)(nil),    // 10: titan.TestIntegrationReq
	(*TestIntegrationResp)(nil),   // 11: titan.TestIntegrationResp
	(*ClusterItem)(nil),           // 12: titan.ClusterItem
	(*ListClustersReq)(nil),       // 13: titan.ListClustersReq
	(*ListClustersResp)(nil),      // 14: titan.ListClustersResp
	(*CreateClusterReq)(nil),      // 15: titan.CreateClusterReq
	(*CreateClusterResp)(nil),     // 16: titan.CreateClusterResp
	(*UpdateClusterReq)(nil),      // 17: titan.UpdateClusterReq
	(*DeleteClusterReq)(nil),      // 18: titan.DeleteClusterReq
	(*TestClusterReq)(nil),        // 19: titan.TestClusterReq
	(*TestClusterResp)(nil),       // 20: titan.TestClusterResp
	(*ListNamespacesReq)(nil),     // 21: titan.ListNamespacesReq
	(*ListNamespacesResp)(nil),    // 22: titan.ListNamespacesResp
	(*PipelineItem)(nil),          // 23: titan.PipelineItem
	(*ListPipelinesReq)(nil),      // 24: titan.ListPipelinesReq
	(*ListPipelinesResp)(nil),     // 25: titan.ListPipelinesResp
	(*GetPipelineReq)(nil),        // 26: titan.GetPipelineReq
	(*PipelineDetailResp)(nil),    // 27: titan.PipelineDetailResp
	(*CreatePipelineReq)(nil),     // 28: titan.CreatePipelineReq
	(*CreatePipelineResp)(nil),    // 29: titan.CreatePipelineResp
	(*UpdatePipelineReq)(nil),     // 30: titan.UpdatePipelineReq
	(*DeletePipelineReq)(nil),     // 31: titan.DeletePipelineReq
	(*TriggerPipelineReq)(nil),    // 32: titan.TriggerPipelineReq
	(*TriggerPipelineResp)(nil),   // 33: titan.TriggerPipelineResp
	(*ExecutionItem)(nil),         // 34: titan.ExecutionItem
	(*StepExecItem)(nil),          // 35: titan.StepExecItem
	(*ListExecutionsReq)(nil),     // 36: titan.ListExecutionsReq
	(*ListExecutionsResp)(nil),    // 37: titan.ListExecutionsResp
	(*GetExecutionDetailReq)(nil), // 38: titan.GetExecutionDetailReq
	(*ExecutionDetailResp)(nil),   // 39: titan.ExecutionDetailResp
	(*GetStepLogReq)(nil),         // 40: titan.GetStepLogReq
	(*GetStepLogResp)(nil),        // 41: titan.GetStepLogResp
	(*ApproveStepReq)(nil),        // 42: titan.ApproveStepReq
	(*CancelExecutionReq)(nil),    // 43: titan.CancelExecutionReq
}
var file_titan_proto_depIdxs = []int32{
	3,  // 0: titan.ListIntegrationsResp.list:type_name -> titan.IntegrationItem
	12, // 1: titan.ListClustersResp.list:type_name -> titan.ClusterItem
	23, // 2: titan.ListPipelinesResp.list:type_name -> titan.PipelineItem
	23, // 3: titan.PipelineDetailResp.pipeline:type_name -> titan.PipelineItem
	34, // 4: titan.ListExecutionsResp.list:type_name -> titan.ExecutionItem
	34, // 5: titan.ExecutionDetailResp.execution:type_name -> titan.ExecutionItem
	35, // 6: titan.ExecutionDetailResp.steps:type_name -> titan.StepExecItem
	1,  // 7: titan.titan.Ping:input_type -> titan.PingReq
	4,  // 8: titan.titan.ListIntegrations:input_type -> titan.ListIntegrationsReq
	6,  // 9: titan.titan.CreateIntegration:input_type -> titan.CreateIntegrationReq
	8,  // 10: titan.titan.UpdateIntegration:input_type -> titan.UpdateIntegrationReq
	9,  // 11: titan.titan.DeleteIntegration:input_type -> titan.DeleteIntegrationReq
	10, // 12: titan.titan.TestIntegration:input_type -> titan.TestIntegrationReq
	13, // 13: titan.titan.ListClusters:input_type -> titan.ListClustersReq
	15, // 14: titan.titan.CreateCluster:input_type -> titan.CreateClusterReq
	17, // 15: titan.titan.UpdateCluster:input_type -> titan.UpdateClusterReq
	18, // 16: titan.titan.DeleteCluster:input_type -> titan.DeleteClusterReq
	19, // 17: titan.titan.TestCluster:input_type -> titan.TestClusterReq
	21, // 18: titan.titan.ListNamespaces:input_type -> titan.ListNamespacesReq
	24, // 19: titan.titan.ListPipelines:input_type -> titan.ListPipelinesReq
	26, // 20: titan.titan.GetPipeline:input_type -> titan.GetPipelineReq
	28, // 21: titan.titan.CreatePipeline:input_type -> titan.CreatePipelineReq
	30, // 22: titan.titan.UpdatePipeline:input_type -> titan.UpdatePipelineReq
	31, // 23: titan.titan.DeletePipeline:input_type -> titan.DeletePipelineReq
	32, // 24: titan.titan.TriggerPipeline:input_type -> titan.TriggerPipelineReq
	36, // 25: titan.titan.ListExecutions:input_type -> titan.ListExecutionsReq
	38, // 26: titan.titan.GetExecutionDetail:input_type -> titan.GetExecutionDetailReq
	40, // 27: titan.titan.GetStepLog:input_type -> titan.GetStepLogReq
	42, // 28: titan.titan.ApproveStep:input_type -> titan.ApproveStepReq
	43, // 29: titan.titan.CancelExecution:input_type -> titan.CancelExecutionReq
	2,  // 30: titan.titan.Ping:output_type -> titan.PingResp
	5,  // 31: titan.titan.ListIntegrations:output_type -> titan.ListIntegrationsResp
	7,  // 32: titan.titan.CreateIntegration:output_type -> titan.CreateIntegrationResp
	0,  // 33: titan.titan.UpdateIntegration:output_type -> titan.CommonResp
	0,  // 34: titan.titan.DeleteIntegration:output_type -> titan.CommonResp
	11, // 35: titan.titan.TestIntegration:output_type -> titan.TestIntegrationResp
	14, // 36: titan.titan.ListClusters:output_type -> titan.ListClustersResp
	16, // 37: titan.titan.CreateCluster:output_type -> titan.CreateClusterResp
	0,  // 38: titan.titan.UpdateCluster:output_type -> titan.CommonResp
	0,  // 39: titan.titan.DeleteCluster:output_type -> titan.CommonResp
	20, // 40: titan.titan.TestCluster:output_type -> titan.TestClusterResp
	22, // 41: titan.titan.ListNamespaces:output_type -> titan.ListNamespacesResp
	25, // 42: titan.titan.ListPipelines:output_type -> titan.ListPipelinesResp
	27, // 43: titan.titan.GetPipeline:output_type -> titan.PipelineDetailResp
	29, // 44: titan.titan.CreatePipeline:output_type -> titan.CreatePipelineResp
	0,  // 45: titan.titan.UpdatePipeline:output_type -> titan.CommonResp
	0,  // 46: titan.titan.DeletePipeline:output_type -> titan.CommonResp
	33, // 47: titan.titan.TriggerPipeline:output_type -> titan.TriggerPipelineResp
	37, // 48: titan.titan.ListExecutions:output_type -> titan.ListExecutionsResp
	39, // 49: titan.titan.GetExecutionDetail:output_type -> titan.ExecutionDetailResp
	41, // 50: titan.titan.GetStepLog:output_type -> titan.GetStepLogResp
	0,  // 51: titan.titan.ApproveStep:output_type -> titan.CommonResp
	0,  // 52: titan.titan.CancelExecution:output_type -> titan.CommonResp
	30, // [30:53] is the sub-list for method output_type
	7,  // [7:30] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_titan_proto_init() }
func file_titan_proto_init() {
	if File_titan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_titan_proto_rawDesc), len(file_titan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_titan_proto_goTypes,
		DependencyIndexes: file_titan_proto_depIdxs,
		MessageInfos:      file_titan_proto_msgTypes,
	}.Build()
	File_titan_proto = out.File
	file_titan_proto_goTypes = nil
	file_titan_proto_depIdxs = nil
}
