// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	dashboard "go-zero-boilerplate/app/gateway/internal/handler/dashboard"
	devops "go-zero-boilerplate/app/gateway/internal/handler/devops"
	dict "go-zero-boilerplate/app/gateway/internal/handler/dict"
	itsm "go-zero-boilerplate/app/gateway/internal/handler/itsm"
	portal_nav "go-zero-boilerplate/app/gateway/internal/handler/portal_nav"
	sys_config "go-zero-boilerplate/app/gateway/internal/handler/sys_config"
	sys_dept "go-zero-boilerplate/app/gateway/internal/handler/sys_dept"
	sys_nav "go-zero-boilerplate/app/gateway/internal/handler/sys_nav"
	sys_notice "go-zero-boilerplate/app/gateway/internal/handler/sys_notice"
	sys_post "go-zero-boilerplate/app/gateway/internal/handler/sys_post"
	system "go-zero-boilerplate/app/gateway/internal/handler/system"
	systemtask "go-zero-boilerplate/app/gateway/internal/handler/system/task"
	user "go-zero-boilerplate/app/gateway/internal/handler/user"
	user_notice "go-zero-boilerplate/app/gateway/internal/handler/user_notice"
	"go-zero-boilerplate/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取系统大盘聚合信息（mr.Finish 内网并发拉取用户画像与任务统计）
				Method:  http.MethodGet,
				Path:    "/overview",
				Handler: dashboard.GetDashboardOverviewHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/dashboard"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/clusters",
				Handler: devops.ListClustersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/clusters",
				Handler: devops.CreateClusterHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/clusters/:id",
				Handler: devops.UpdateClusterHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/clusters/:id",
				Handler: devops.DeleteClusterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/clusters/:id/namespaces",
				Handler: devops.ListNamespacesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/clusters/:id/test",
				Handler: devops.TestClusterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/executions",
				Handler: devops.ListExecutionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/executions/:id",
				Handler: devops.GetExecutionDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/executions/:id/cancel",
				Handler: devops.CancelExecutionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/integrations",
				Handler: devops.ListIntegrationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/integrations",
				Handler: devops.CreateIntegrationHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/integrations/:id",
				Handler: devops.UpdateIntegrationHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/integrations/:id",
				Handler: devops.DeleteIntegrationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/integrations/:id/test",
				Handler: devops.TestIntegrationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pipelines",
				Handler: devops.ListPipelinesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pipelines",
				Handler: devops.CreatePipelineHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pipelines/:id",
				Handler: devops.GetPipelineHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/pipelines/:id",
				Handler: devops.UpdatePipelineHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/pipelines/:id",
				Handler: devops.DeletePipelineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pipelines/:id/trigger",
				Handler: devops.TriggerPipelineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/steps/:id/approve",
				Handler: devops.ApproveStepHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/steps/:id/log",
				Handler: devops.GetStepLogHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/devops"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取字典数据项列表
				Method:  http.MethodGet,
				Path:    "/data",
				Handler: dict.ListSysDictDataHandler(serverCtx),
			},
			{
				// 创建字典数据项
				Method:  http.MethodPost,
				Path:    "/data",
				Handler: dict.CreateSysDictDataHandler(serverCtx),
			},
			{
				// 更新字典数据项
				Method:  http.MethodPut,
				Path:    "/data",
				Handler: dict.UpdateSysDictDataHandler(serverCtx),
			},
			{
				// 删除字典数据项
				Method:  http.MethodDelete,
				Path:    "/data/:id",
				Handler: dict.DeleteSysDictDataHandler(serverCtx),
			},
			{
				// 根据字典类型查询数据项列表
				Method:  http.MethodGet,
				Path:    "/data/type/:dictType",
				Handler: dict.GetDictDataByTypeHandler(serverCtx),
			},
			{
				// 获取字典类型列表
				Method:  http.MethodGet,
				Path:    "/types",
				Handler: dict.ListSysDictTypesHandler(serverCtx),
			},
			{
				// 创建字典类型
				Method:  http.MethodPost,
				Path:    "/types",
				Handler: dict.CreateSysDictTypeHandler(serverCtx),
			},
			{
				// 更新字典类型
				Method:  http.MethodPut,
				Path:    "/types",
				Handler: dict.UpdateSysDictTypeHandler(serverCtx),
			},
			{
				// 删除字典类型
				Method:  http.MethodDelete,
				Path:    "/types/:id",
				Handler: dict.DeleteSysDictTypeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/dict"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/process-defs",
				Handler: itsm.ListProcessDefsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/process-defs",
				Handler: itsm.CreateProcessDefHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/process-defs/:id",
				Handler: itsm.GetProcessDefHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/process-defs/:id",
				Handler: itsm.UpdateProcessDefHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/process-defs/:id/deploy",
				Handler: itsm.DeployProcessDefHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sla-policies",
				Handler: itsm.ListSlaPoliciesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/sla-policies/:id",
				Handler: itsm.UpdateSlaPolicyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tickets",
				Handler: itsm.ListTicketsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tickets",
				Handler: itsm.CreateTicketHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tickets/:id",
				Handler: itsm.GetTicketDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tickets/:id/approve",
				Handler: itsm.ApproveTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tickets/:id/cancel",
				Handler: itsm.CancelTicketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tickets/:id/claim",
				Handler: itsm.ClaimTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tickets/:id/reject",
				Handler: itsm.RejectTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tickets/:id/trajectory",
				Handler: itsm.GetTicketTrajectoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tickets/:id/transfer",
				Handler: itsm.TransferTaskHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/itsm"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取门户公开网址导航列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: portal_nav.GetPortalNavListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/portal/navigation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取参数配置表列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: sys_config.ListSysConfigHandler(serverCtx),
			},
			{
				// 创建参数配置表
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sys_config.CreateSysConfigHandler(serverCtx),
			},
			{
				// 更新参数配置表
				Method:  http.MethodPut,
				Path:    "/",
				Handler: sys_config.UpdateSysConfigHandler(serverCtx),
			},
			{
				// 获取参数配置表详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sys_config.GetSysConfigHandler(serverCtx),
			},
			{
				// 删除参数配置表
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: sys_config.DeleteSysConfigHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user/sys-config"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取部门树形列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: sys_dept.ListSysDeptHandler(serverCtx),
			},
			{
				// 创建新部门
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sys_dept.CreateSysDeptHandler(serverCtx),
			},
			{
				// 更新部门
				Method:  http.MethodPut,
				Path:    "/",
				Handler: sys_dept.UpdateSysDeptHandler(serverCtx),
			},
			{
				// 获取部门详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sys_dept.GetSysDeptHandler(serverCtx),
			},
			{
				// 删除部门
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: sys_dept.DeleteSysDeptHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user/dept"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建系统导航站点
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sys_nav.CreateSysPortalNavHandler(serverCtx),
			},
			{
				// 获取导航站点详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sys_nav.GetSysPortalNavHandler(serverCtx),
			},
			{
				// 更新系统导航站点
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: sys_nav.UpdateSysPortalNavHandler(serverCtx),
			},
			{
				// 删除系统导航站点
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: sys_nav.DeleteSysPortalNavHandler(serverCtx),
			},
			{
				// 分页查询系统导航配置列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: sys_nav.ListSysPortalNavHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/navigation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取通知公告表列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: sys_notice.ListSysNoticeHandler(serverCtx),
			},
			{
				// 创建通知公告表
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sys_notice.CreateSysNoticeHandler(serverCtx),
			},
			{
				// 更新通知公告表
				Method:  http.MethodPut,
				Path:    "/",
				Handler: sys_notice.UpdateSysNoticeHandler(serverCtx),
			},
			{
				// 获取通知公告表详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sys_notice.GetSysNoticeHandler(serverCtx),
			},
			{
				// 删除通知公告表
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: sys_notice.DeleteSysNoticeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user/sys-notice"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取岗位信息表列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: sys_post.ListSysPostHandler(serverCtx),
			},
			{
				// 创建岗位信息表
				Method:  http.MethodPost,
				Path:    "/",
				Handler: sys_post.CreateSysPostHandler(serverCtx),
			},
			{
				// 更新岗位信息表
				Method:  http.MethodPut,
				Path:    "/",
				Handler: sys_post.UpdateSysPostHandler(serverCtx),
			},
			{
				// 获取岗位信息表详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: sys_post.GetSysPostHandler(serverCtx),
			},
			{
				// 删除岗位信息表
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: sys_post.DeleteSysPostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user/sys-post"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Casdoor SSO 统一身份登录
				Method:  http.MethodPost,
				Path:    "/auth/casdoor/login",
				Handler: system.CasdoorLoginHandler(serverCtx),
			},
			{
				// 管理员账号登录
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: system.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取系统 API 字典列表
				Method:  http.MethodGet,
				Path:    "/apis",
				Handler: system.ListSysApisHandler(serverCtx),
			},
			{
				// 通用文件上传
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: system.UploadFileHandler(serverCtx),
			},
			{
				// 获取登录日志列表
				Method:  http.MethodGet,
				Path:    "/logs/login",
				Handler: system.ListSysLoginLogsHandler(serverCtx),
			},
			{
				// 获取操作日志列表
				Method:  http.MethodGet,
				Path:    "/logs/oper",
				Handler: system.ListSysOperLogsHandler(serverCtx),
			},
			{
				// 获取全量菜单与按钮树
				Method:  http.MethodGet,
				Path:    "/menus/tree",
				Handler: system.GetSysMenuTreeHandler(serverCtx),
			},
			{
				// 获取当前在线用户会话列表
				Method:  http.MethodGet,
				Path:    "/online",
				Handler: system.ListOnlineSessionsHandler(serverCtx),
			},
			{
				// 强退指定在线用户会话
				Method:  http.MethodDelete,
				Path:    "/online/:sessionId",
				Handler: system.ForceLogoutOnlineSessionHandler(serverCtx),
			},
			{
				// 修改当前登录员工密码
				Method:  http.MethodPut,
				Path:    "/personal/password",
				Handler: system.ChangePersonalPasswordHandler(serverCtx),
			},
			{
				// 获取当前登录员工画像与权限
				Method:  http.MethodGet,
				Path:    "/personal/profile",
				Handler: system.GetAdminProfileHandler(serverCtx),
			},
			{
				// 修改当前登录员工个人资料
				Method:  http.MethodPut,
				Path:    "/personal/profile",
				Handler: system.UpdatePersonalProfileHandler(serverCtx),
			},
			{
				// 获取角色列表
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: system.ListSysRolesHandler(serverCtx),
			},
			{
				// 创建角色
				Method:  http.MethodPost,
				Path:    "/roles",
				Handler: system.CreateSysRoleHandler(serverCtx),
			},
			{
				// 更新角色
				Method:  http.MethodPut,
				Path:    "/roles",
				Handler: system.UpdateSysRoleHandler(serverCtx),
			},
			{
				// 删除角色
				Method:  http.MethodDelete,
				Path:    "/roles/:id",
				Handler: system.DeleteSysRoleHandler(serverCtx),
			},
			{
				// 分配角色菜单与按钮权限
				Method:  http.MethodPost,
				Path:    "/roles/permissions",
				Handler: system.AssignRolePermissionsHandler(serverCtx),
			},
			{
				// 获取员工列表
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: system.ListSysUsersHandler(serverCtx),
			},
			{
				// 创建新员工
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: system.CreateSysUserHandler(serverCtx),
			},
			{
				// 更新员工信息
				Method:  http.MethodPut,
				Path:    "/users",
				Handler: system.UpdateSysUserHandler(serverCtx),
			},
			{
				// 删除员工
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: system.DeleteSysUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取异步任务分页列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: systemtask.ListTasksHandler(serverCtx),
			},
			{
				// 新增异步任务
				Method:  http.MethodPost,
				Path:    "/",
				Handler: systemtask.CreateTaskHandler(serverCtx),
			},
			{
				// 获取异步任务详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: systemtask.GetTaskHandler(serverCtx),
			},
			{
				// 修改异步任务
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: systemtask.UpdateTaskHandler(serverCtx),
			},
			{
				// 删除异步任务
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: systemtask.DeleteTaskHandler(serverCtx),
			},
			{
				// 立即触发执行一次任务
				Method:  http.MethodPost,
				Path:    "/:id/run",
				Handler: systemtask.RunTaskOnceHandler(serverCtx),
			},
			{
				// 启停异步任务
				Method:  http.MethodPut,
				Path:    "/:id/status",
				Handler: systemtask.ToggleTaskStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前登录用户信息（受保护路由，强制由 JWT Claims 解析身份，杜绝水平越权）
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				// 获取统一用户个人画像（双表融合聚合，支持员工与客户）
				Method:  http.MethodGet,
				Path:    "/profile",
				Handler: user.GetUserProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前员工个人通知流与未读数
				Method:  http.MethodGet,
				Path:    "/my-list",
				Handler: user_notice.GetMyNoticeFeedHandler(serverCtx),
			},
			{
				// 标记单条通知已读
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: user_notice.MarkNoticeReadHandler(serverCtx),
			},
			{
				// 全部标记已读
				Method:  http.MethodPost,
				Path:    "/read-all",
				Handler: user_notice.MarkAllNoticesReadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user/notice"),
	)
}
