/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { DashboardGetDashboardOverview200SystemStats } from './dashboardGetDashboardOverview200SystemStats';
import type { DashboardGetDashboardOverview200UserInfo } from './dashboardGetDashboardOverview200UserInfo';

export type DashboardGetDashboardOverview200 = {
  sysTime?: number;
  systemStats?: DashboardGetDashboardOverview200SystemStats;
  userInfo?: DashboardGetDashboardOverview200UserInfo;
};
