/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type DashboardGetDashboardOverview200UserInfo = {
  avatar: string;
  id: number;
  mobile: string;
  name: string;
};
