/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { DevopsListExecutions200ListItem } from './devopsListExecutions200ListItem';

export type DevopsListExecutions200 = {
  list?: DevopsListExecutions200ListItem[];
  total?: number;
};
