/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type DevopsListClusters200ListItem = {
  apiEndpoint: string;
  createTime: string;
  createdBy: number;
  description: string;
  env: string;
  id: number;
  name: string;
  status: string;
  updateTime: string;
  version: string;
};
