/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { DevopsListClusters200ListItem } from './devopsListClusters200ListItem';

export type DevopsListClusters200 = {
  list?: DevopsListClusters200ListItem[];
  total?: number;
};
