/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type DevopsUpdateClusterBody = {
  apiEndpoint?: string;
  description?: string;
  env?: string;
  kubeconfig?: string;
  name?: string;
};
