/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { ItsmListTickets200ListItem } from './itsmListTickets200ListItem';

export type ItsmListTickets200 = {
  list?: ItsmListTickets200ListItem[];
  total?: number;
};
