/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type ItsmCreateProcessDefBody = {
  bpmnXml?: string;
  category?: string;
  description?: string;
  formSchema?: string;
  procCode: string;
  procName: string;
};
