/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type ItsmGetProcessDef200 = {
  bpmnXml?: string;
  category?: string;
  createTime?: string;
  description?: string;
  formSchema?: string;
  id?: number;
  procCode?: string;
  procName?: string;
  status?: number;
  updateTime?: string;
  version?: number;
};
