/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { SysConfigListSysConfig200ListItem } from './sysConfigListSysConfig200ListItem';

export type SysConfigListSysConfig200 = {
  list?: SysConfigListSysConfig200ListItem[];
  total?: number;
};
