/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SysDeptUpdateSysDeptBody = {
  deptName: string;
  id: number;
  leader?: string;
  parentId: number;
  phone?: string;
  sort: number;
  status: number;
};
