/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { SysDeptGetSysDept200ChildrenItem } from './sysDeptGetSysDept200ChildrenItem';

export type SysDeptGetSysDept200 = {
  ancestors?: string;
  children?: SysDeptGetSysDept200ChildrenItem[];
  createTime?: string;
  deptName?: string;
  id?: number;
  leader?: string;
  parentId?: number;
  phone?: string;
  sort?: number;
  status?: number;
  updateTime?: string;
};
