/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SysNoticeListSysNoticeParams = {
page?: number;
pageSize?: number;
keyword?: string;
};
