/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { SysNavListSysPortalNav200ListItem } from './sysNavListSysPortalNav200ListItem';

export type SysNavListSysPortalNav200 = {
  list?: SysNavListSysPortalNav200ListItem[];
  total?: number;
};
