/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SysPostUpdateSysPostBody = {
  /** 岗位ID */
  id: number;
  /** 岗位编码 */
  postCode: string;
  /** 岗位名称 */
  postName: string;
  /** 显示顺序 */
  postSort: number;
  /** 备注 */
  remark: string;
  /** 状态（1正常 0停用） */
  status: number;
};
