/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { SystemTaskListTasks200ListItem } from './systemTaskListTasks200ListItem';

export type SystemTaskListTasks200 = {
  list?: SystemTaskListTasks200ListItem[];
  total?: number;
};
