/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SystemListOnlineSessions200ListItem = {
  browser: string;
  deptName: string;
  isCurrent: boolean;
  loginIp: string;
  loginLocation: string;
  loginTime: string;
  os: string;
  realName: string;
  sessionId: string;
  userId: number;
  username: string;
};
