/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { SystemListSysRoles200ListItem } from './systemListSysRoles200ListItem';

export type SystemListSysRoles200 = {
  list?: SystemListSysRoles200ListItem[];
  total?: number;
};
