/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SystemListOnlineSessionsParams = {
page?: number;
pageSize?: number;
username?: string;
loginIp?: string;
};
