/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SystemTaskListTasksParams = {
page?: number;
pageSize?: number;
taskName?: string;
taskKey?: string;
status?: number;
};
