/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SystemAdminLogin200 = {
  accessExpire?: number;
  accessToken?: string;
  avatar?: string;
  realName?: string;
  refreshAfter?: number;
  roles?: string[];
  userId?: number;
  username?: string;
};
