/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type SystemListSysLoginLogs200ListItem = {
  browser: string;
  id: number;
  loginIp: string;
  loginTime: string;
  msg: string;
  os: string;
  status: number;
  username: string;
};
