/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { SystemGetSysMenuTree200ListItemChildrenItemChildrenItem } from './systemGetSysMenuTree200ListItemChildrenItemChildrenItem';

export type SystemGetSysMenuTree200ListItemChildrenItem = {
  children: SystemGetSysMenuTree200ListItemChildrenItemChildrenItem[];
  component: string;
  icon: string;
  id: number;
  parentId: number;
  path: string;
  permissionCode: string;
  sort: number;
  title: string;
  /** 1:目录 2:菜单 3:按钮 */
  type: number;
};
