/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanUpdateAppBody = {
  buildConfig?: string;
  defaultBranch?: string;
  deploySpec?: string;
  description?: string;
  displayName?: string;
  integrationId?: number;
  name?: string;
  repoUrl?: string;
  status?: number;
};
