/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanUpdateIntegrationBody = {
  authType?: string;
  config?: string;
  description?: string;
  name?: string;
  status?: number;
};
