/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanListReleaseOrdersParams = {
projectId?: number;
targetEnv?: string;
status?: string;
keyword?: string;
/**
 * @minimum 1
 * @maximum 100000
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};
