/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { TitanListProjects200ListItem } from './titanListProjects200ListItem';

export type TitanListProjects200 = {
  list?: TitanListProjects200ListItem[];
  total?: number;
};
