/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanListProjects200ListItem = {
  appCount: number;
  createTime: string;
  description: string;
  displayName: string;
  envCount: number;
  id: number;
  name: string;
  ownerId: number;
  status: number;
  updateTime: string;
};
