/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanTriggerPipelineBody = {
  gitBranch?: string;
  gitCommit?: string;
  runtimeParams?: string;
  triggerType?: string;
};
