/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanListReleaseOrders200ListItem = {
  applicantId: number;
  applicantName: string;
  approverId: number;
  approverName: string;
  createTime: string;
  description: string;
  endTime: string;
  id: number;
  itsmProcessInstId: number;
  orderNo: string;
  projectId: number;
  scheduledTime: string;
  servicesJson: string;
  startTime: string;
  status: string;
  targetEnv: string;
  title: string;
  updateTime: string;
};
