/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanCreateArtifactBody = {
  appId: number;
  buildExecId?: number;
  commitMsg?: string;
  gitBranch?: string;
  gitCommit?: string;
  imageDigest?: string;
  imageSizeBytes?: number;
  imageTag: string;
  imageUrl: string;
};
