/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { TitanGetExecutionDetail200Execution } from './titanGetExecutionDetail200Execution';
import type { TitanGetExecutionDetail200StepsItem } from './titanGetExecutionDetail200StepsItem';

export type TitanGetExecutionDetail200 = {
  execution?: TitanGetExecutionDetail200Execution;
  steps?: TitanGetExecutionDetail200StepsItem[];
};
