/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { TitanListApps200ListItem } from './titanListApps200ListItem';

export type TitanListApps200 = {
  list?: TitanListApps200ListItem[];
  total?: number;
};
