/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */

export type TitanGetDeliveryMatrix200ServicesItemCellsItem = {
  appId: number;
  artifactId: number;
  deployStatus: string;
  diffStatus: string;
  envCode: string;
  envId: number;
  gitBranch: string;
  gitCommit: string;
  healthStatus: string;
  lastDeployedAt: string;
  readyReplicas: number;
  totalReplicas: number;
  versionTag: string;
};
