/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type { TitanListPipelines200ListItem } from './titanListPipelines200ListItem';

export type TitanListPipelines200 = {
  list?: TitanListPipelines200ListItem[];
  total?: number;
};
