// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package server

import (
	"context"

	"go-zero-boilerplate/app/user/rpc/internal/logic/user"
	"go-zero-boilerplate/app/user/rpc/internal/svc"
	"go-zero-boilerplate/app/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 原有业务接口
func (s *UserServer) GetUserInfo(ctx context.Context, in *pb.IdRequest) (*pb.UserInfoResponse, error) {
	l := userlogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 系统管理与 RBAC 权限接口
func (s *UserServer) AdminLogin(ctx context.Context, in *pb.AdminLoginRequest) (*pb.AdminLoginResponse, error) {
	l := userlogic.NewAdminLoginLogic(ctx, s.svcCtx)
	return l.AdminLogin(in)
}

func (s *UserServer) SyncOrCreateCasdoorUser(ctx context.Context, in *pb.SyncCasdoorUserRequest) (*pb.SyncCasdoorUserResponse, error) {
	l := userlogic.NewSyncOrCreateCasdoorUserLogic(ctx, s.svcCtx)
	return l.SyncOrCreateCasdoorUser(in)
}

func (s *UserServer) GetAdminProfile(ctx context.Context, in *pb.IdRequest) (*pb.AdminProfileResponse, error) {
	l := userlogic.NewGetAdminProfileLogic(ctx, s.svcCtx)
	return l.GetAdminProfile(in)
}

// 员工管理
func (s *UserServer) ListSysUsers(ctx context.Context, in *pb.ListSysUsersRequest) (*pb.ListSysUsersResponse, error) {
	l := userlogic.NewListSysUsersLogic(ctx, s.svcCtx)
	return l.ListSysUsers(in)
}

func (s *UserServer) CreateSysUser(ctx context.Context, in *pb.CreateSysUserRequest) (*pb.IdRequest, error) {
	l := userlogic.NewCreateSysUserLogic(ctx, s.svcCtx)
	return l.CreateSysUser(in)
}

func (s *UserServer) UpdateSysUser(ctx context.Context, in *pb.UpdateSysUserRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewUpdateSysUserLogic(ctx, s.svcCtx)
	return l.UpdateSysUser(in)
}

func (s *UserServer) DeleteSysUser(ctx context.Context, in *pb.IdRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewDeleteSysUserLogic(ctx, s.svcCtx)
	return l.DeleteSysUser(in)
}

// 角色管理
func (s *UserServer) ListSysRoles(ctx context.Context, in *pb.ListSysRolesRequest) (*pb.ListSysRolesResponse, error) {
	l := userlogic.NewListSysRolesLogic(ctx, s.svcCtx)
	return l.ListSysRoles(in)
}

func (s *UserServer) CreateSysRole(ctx context.Context, in *pb.CreateSysRoleRequest) (*pb.IdRequest, error) {
	l := userlogic.NewCreateSysRoleLogic(ctx, s.svcCtx)
	return l.CreateSysRole(in)
}

func (s *UserServer) UpdateSysRole(ctx context.Context, in *pb.UpdateSysRoleRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewUpdateSysRoleLogic(ctx, s.svcCtx)
	return l.UpdateSysRole(in)
}

func (s *UserServer) DeleteSysRole(ctx context.Context, in *pb.IdRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewDeleteSysRoleLogic(ctx, s.svcCtx)
	return l.DeleteSysRole(in)
}

func (s *UserServer) AssignRolePermissions(ctx context.Context, in *pb.AssignRolePermRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewAssignRolePermissionsLogic(ctx, s.svcCtx)
	return l.AssignRolePermissions(in)
}

// 菜单与接口字典
func (s *UserServer) GetSysMenuTree(ctx context.Context, in *pb.EmptyRequest) (*pb.GetSysMenuTreeResponse, error) {
	l := userlogic.NewGetSysMenuTreeLogic(ctx, s.svcCtx)
	return l.GetSysMenuTree(in)
}

func (s *UserServer) ListSysApis(ctx context.Context, in *pb.EmptyRequest) (*pb.ListSysApisResponse, error) {
	l := userlogic.NewListSysApisLogic(ctx, s.svcCtx)
	return l.ListSysApis(in)
}

// 数据字典管理
func (s *UserServer) ListSysDictTypes(ctx context.Context, in *pb.ListSysDictTypesRequest) (*pb.ListSysDictTypesResponse, error) {
	l := userlogic.NewListSysDictTypesLogic(ctx, s.svcCtx)
	return l.ListSysDictTypes(in)
}

func (s *UserServer) CreateSysDictType(ctx context.Context, in *pb.CreateSysDictTypeRequest) (*pb.IdRequest, error) {
	l := userlogic.NewCreateSysDictTypeLogic(ctx, s.svcCtx)
	return l.CreateSysDictType(in)
}

func (s *UserServer) UpdateSysDictType(ctx context.Context, in *pb.UpdateSysDictTypeRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewUpdateSysDictTypeLogic(ctx, s.svcCtx)
	return l.UpdateSysDictType(in)
}

func (s *UserServer) DeleteSysDictType(ctx context.Context, in *pb.IdRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewDeleteSysDictTypeLogic(ctx, s.svcCtx)
	return l.DeleteSysDictType(in)
}

func (s *UserServer) ListSysDictData(ctx context.Context, in *pb.ListSysDictDataRequest) (*pb.ListSysDictDataResponse, error) {
	l := userlogic.NewListSysDictDataLogic(ctx, s.svcCtx)
	return l.ListSysDictData(in)
}

func (s *UserServer) CreateSysDictData(ctx context.Context, in *pb.CreateSysDictDataRequest) (*pb.IdRequest, error) {
	l := userlogic.NewCreateSysDictDataLogic(ctx, s.svcCtx)
	return l.CreateSysDictData(in)
}

func (s *UserServer) UpdateSysDictData(ctx context.Context, in *pb.UpdateSysDictDataRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewUpdateSysDictDataLogic(ctx, s.svcCtx)
	return l.UpdateSysDictData(in)
}

func (s *UserServer) DeleteSysDictData(ctx context.Context, in *pb.IdRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewDeleteSysDictDataLogic(ctx, s.svcCtx)
	return l.DeleteSysDictData(in)
}

func (s *UserServer) GetDictDataByType(ctx context.Context, in *pb.GetDictDataByTypeRequest) (*pb.GetDictDataByTypeResponse, error) {
	l := userlogic.NewGetDictDataByTypeLogic(ctx, s.svcCtx)
	return l.GetDictDataByType(in)
}

// 网关 RBAC 接口动态拦截鉴权
func (s *UserServer) CheckApiPermission(ctx context.Context, in *pb.CheckApiPermissionRequest) (*pb.CheckApiPermissionResponse, error) {
	l := userlogic.NewCheckApiPermissionLogic(ctx, s.svcCtx)
	return l.CheckApiPermission(in)
}

// 审计日志管理
func (s *UserServer) RecordOperLog(ctx context.Context, in *pb.RecordOperLogRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewRecordOperLogLogic(ctx, s.svcCtx)
	return l.RecordOperLog(in)
}

func (s *UserServer) RecordLoginLog(ctx context.Context, in *pb.RecordLoginLogRequest) (*pb.EmptyResponse, error) {
	l := userlogic.NewRecordLoginLogLogic(ctx, s.svcCtx)
	return l.RecordLoginLog(in)
}

func (s *UserServer) ListSysOperLogs(ctx context.Context, in *pb.ListSysOperLogsRequest) (*pb.ListSysOperLogsResponse, error) {
	l := userlogic.NewListSysOperLogsLogic(ctx, s.svcCtx)
	return l.ListSysOperLogs(in)
}

func (s *UserServer) ListSysLoginLogs(ctx context.Context, in *pb.ListSysLoginLogsRequest) (*pb.ListSysLoginLogsResponse, error) {
	l := userlogic.NewListSysLoginLogsLogic(ctx, s.svcCtx)
	return l.ListSysLoginLogs(in)
}
