/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: v1
 */
import type {
  ItsmApproveTaskBody,
  ItsmCancelTicketBody,
  ItsmClaimTaskBody,
  ItsmCreateProcessDef200,
  ItsmCreateProcessDefBody,
  ItsmCreateTicket200,
  ItsmCreateTicketBody,
  ItsmGetProcessDef200,
  ItsmGetTicketDetail200,
  ItsmGetTicketTrajectory200,
  ItsmListProcessDefs200,
  ItsmListProcessDefsParams,
  ItsmListSlaPolicies200,
  ItsmListTickets200,
  ItsmListTicketsParams,
  ItsmRejectTaskBody,
  ItsmTransferTaskBody,
  ItsmUpdateProcessDefBody,
  ItsmUpdateSlaPolicyBody
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary listProcessDefs
 */
export const itsmListProcessDefs = (
    params: ItsmListProcessDefsParams,
 options?: SecondParameter<typeof customInstance<ItsmListProcessDefs200>>,) => {
      return customInstance<ItsmListProcessDefs200>(
      {url: `/api/v1/itsm/process-defs`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary createProcessDef
 */
export const itsmCreateProcessDef = (
    itsmCreateProcessDefBody: ItsmCreateProcessDefBody,
 options?: SecondParameter<typeof customInstance<ItsmCreateProcessDef200>>,) => {
      return customInstance<ItsmCreateProcessDef200>(
      {url: `/api/v1/itsm/process-defs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itsmCreateProcessDefBody
    },
      options);
    }
  /**
 * @summary getProcessDef
 */
export const itsmGetProcessDef = (
    id: number,
 options?: SecondParameter<typeof customInstance<ItsmGetProcessDef200>>,) => {
      return customInstance<ItsmGetProcessDef200>(
      {url: `/api/v1/itsm/process-defs/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary updateProcessDef
 */
export const itsmUpdateProcessDef = (
    id: number,
    itsmUpdateProcessDefBody: ItsmUpdateProcessDefBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/process-defs/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: itsmUpdateProcessDefBody
    },
      options);
    }
  /**
 * @summary deployProcessDef
 */
export const itsmDeployProcessDef = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/process-defs/${id}/deploy`, method: 'POST'
    },
      options);
    }
  /**
 * @summary listSlaPolicies
 */
export const itsmListSlaPolicies = (

 options?: SecondParameter<typeof customInstance<ItsmListSlaPolicies200>>,) => {
      return customInstance<ItsmListSlaPolicies200>(
      {url: `/api/v1/itsm/sla-policies`, method: 'GET'
    },
      options);
    }
  /**
 * @summary updateSlaPolicy
 */
export const itsmUpdateSlaPolicy = (
    id: number,
    itsmUpdateSlaPolicyBody: ItsmUpdateSlaPolicyBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/sla-policies/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: itsmUpdateSlaPolicyBody
    },
      options);
    }
  /**
 * @summary listTickets
 */
export const itsmListTickets = (
    params: ItsmListTicketsParams,
 options?: SecondParameter<typeof customInstance<ItsmListTickets200>>,) => {
      return customInstance<ItsmListTickets200>(
      {url: `/api/v1/itsm/tickets`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary createTicket
 */
export const itsmCreateTicket = (
    itsmCreateTicketBody: ItsmCreateTicketBody,
 options?: SecondParameter<typeof customInstance<ItsmCreateTicket200>>,) => {
      return customInstance<ItsmCreateTicket200>(
      {url: `/api/v1/itsm/tickets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itsmCreateTicketBody
    },
      options);
    }
  /**
 * @summary getTicketDetail
 */
export const itsmGetTicketDetail = (
    id: number,
 options?: SecondParameter<typeof customInstance<ItsmGetTicketDetail200>>,) => {
      return customInstance<ItsmGetTicketDetail200>(
      {url: `/api/v1/itsm/tickets/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary approveTask
 */
export const itsmApproveTask = (
    id: number,
    itsmApproveTaskBody: ItsmApproveTaskBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/tickets/${id}/approve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itsmApproveTaskBody
    },
      options);
    }
  /**
 * @summary cancelTicket
 */
export const itsmCancelTicket = (
    id: number,
    itsmCancelTicketBody: ItsmCancelTicketBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/tickets/${id}/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itsmCancelTicketBody
    },
      options);
    }
  /**
 * @summary claimTask
 */
export const itsmClaimTask = (
    id: number,
    itsmClaimTaskBody: ItsmClaimTaskBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/tickets/${id}/claim`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itsmClaimTaskBody
    },
      options);
    }
  /**
 * @summary rejectTask
 */
export const itsmRejectTask = (
    id: number,
    itsmRejectTaskBody: ItsmRejectTaskBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/tickets/${id}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itsmRejectTaskBody
    },
      options);
    }
  /**
 * @summary getTicketTrajectory
 */
export const itsmGetTicketTrajectory = (
    id: number,
 options?: SecondParameter<typeof customInstance<ItsmGetTicketTrajectory200>>,) => {
      return customInstance<ItsmGetTicketTrajectory200>(
      {url: `/api/v1/itsm/tickets/${id}/trajectory`, method: 'GET'
    },
      options);
    }
  /**
 * @summary transferTask
 */
export const itsmTransferTask = (
    id: number,
    itsmTransferTaskBody: ItsmTransferTaskBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/itsm/tickets/${id}/transfer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itsmTransferTaskBody
    },
      options);
    }

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type ItsmListProcessDefsResult = NonNullable<Awaited<ReturnType<typeof itsmListProcessDefs>>>
export type ItsmCreateProcessDefResult = NonNullable<Awaited<ReturnType<typeof itsmCreateProcessDef>>>
export type ItsmGetProcessDefResult = NonNullable<Awaited<ReturnType<typeof itsmGetProcessDef>>>
export type ItsmUpdateProcessDefResult = NonNullable<Awaited<ReturnType<typeof itsmUpdateProcessDef>>>
export type ItsmDeployProcessDefResult = NonNullable<Awaited<ReturnType<typeof itsmDeployProcessDef>>>
export type ItsmListSlaPoliciesResult = NonNullable<Awaited<ReturnType<typeof itsmListSlaPolicies>>>
export type ItsmUpdateSlaPolicyResult = NonNullable<Awaited<ReturnType<typeof itsmUpdateSlaPolicy>>>
export type ItsmListTicketsResult = NonNullable<Awaited<ReturnType<typeof itsmListTickets>>>
export type ItsmCreateTicketResult = NonNullable<Awaited<ReturnType<typeof itsmCreateTicket>>>
export type ItsmGetTicketDetailResult = NonNullable<Awaited<ReturnType<typeof itsmGetTicketDetail>>>
export type ItsmApproveTaskResult = NonNullable<Awaited<ReturnType<typeof itsmApproveTask>>>
export type ItsmCancelTicketResult = NonNullable<Awaited<ReturnType<typeof itsmCancelTicket>>>
export type ItsmClaimTaskResult = NonNullable<Awaited<ReturnType<typeof itsmClaimTask>>>
export type ItsmRejectTaskResult = NonNullable<Awaited<ReturnType<typeof itsmRejectTask>>>
export type ItsmGetTicketTrajectoryResult = NonNullable<Awaited<ReturnType<typeof itsmGetTicketTrajectory>>>
export type ItsmTransferTaskResult = NonNullable<Awaited<ReturnType<typeof itsmTransferTask>>>
