// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	titanReleaseOrderFieldNames          = builder.RawFieldNames(&TitanReleaseOrder{})
	titanReleaseOrderRows                = strings.Join(titanReleaseOrderFieldNames, ",")
	titanReleaseOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(titanReleaseOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	titanReleaseOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(titanReleaseOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoZeroBoilerplateTitanReleaseOrderIdPrefix      = "cache:goZeroBoilerplate:titanReleaseOrder:id:"
	cacheGoZeroBoilerplateTitanReleaseOrderOrderNoPrefix = "cache:goZeroBoilerplate:titanReleaseOrder:orderNo:"
)

type (
	titanReleaseOrderModel interface {
		Insert(ctx context.Context, data *TitanReleaseOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TitanReleaseOrder, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*TitanReleaseOrder, error)
		Update(ctx context.Context, data *TitanReleaseOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTitanReleaseOrderModel struct {
		sqlc.CachedConn
		table string
	}

	TitanReleaseOrder struct {
		Id                int64        `db:"id"`                   // 发布单ID
		OrderNo           string       `db:"order_no"`             // 发布单号 (如 RO202609190001)
		ProjectId         int64        `db:"project_id"`           // 所属项目ID
		Title             string       `db:"title"`                // 发布单标题
		Description       string       `db:"description"`          // 发布说明
		TargetEnv         string       `db:"target_env"`           // 目标环境 (dev, test, staging, prod)
		ServicesJson      string       `db:"services_json"`        // 变更服务及目标版本详情 JSON
		Status            string       `db:"status"`               // DRAFT, PENDING_APPROVAL, APPROVED, REJECTED, EXECUTING, SUCCESS, FAILED, CANCELED
		ItsmProcessInstId int64        `db:"itsm_process_inst_id"` // 关联ITSM流程实例ID
		ApplicantId       int64        `db:"applicant_id"`         // 申请人ID
		ApplicantName     string       `db:"applicant_name"`       // 申请人姓名
		ApproverId        int64        `db:"approver_id"`          // 审批人ID
		ApproverName      string       `db:"approver_name"`        // 审批人姓名
		ScheduledTime     sql.NullTime `db:"scheduled_time"`       // 计划发布时间
		StartTime         sql.NullTime `db:"start_time"`           // 实际开始时间
		EndTime           sql.NullTime `db:"end_time"`             // 实际完成时间
		CreateTime        time.Time    `db:"create_time"`
		UpdateTime        time.Time    `db:"update_time"`
	}
)

func newTitanReleaseOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTitanReleaseOrderModel {
	return &defaultTitanReleaseOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`titan_release_order`",
	}
}

func (m *defaultTitanReleaseOrderModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	goZeroBoilerplateTitanReleaseOrderIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderIdPrefix, id)
	goZeroBoilerplateTitanReleaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goZeroBoilerplateTitanReleaseOrderIdKey, goZeroBoilerplateTitanReleaseOrderOrderNoKey)
	return err
}

func (m *defaultTitanReleaseOrderModel) FindOne(ctx context.Context, id int64) (*TitanReleaseOrder, error) {
	goZeroBoilerplateTitanReleaseOrderIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderIdPrefix, id)
	var resp TitanReleaseOrder
	err := m.QueryRowCtx(ctx, &resp, goZeroBoilerplateTitanReleaseOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanReleaseOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitanReleaseOrderModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*TitanReleaseOrder, error) {
	goZeroBoilerplateTitanReleaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderOrderNoPrefix, orderNo)
	var resp TitanReleaseOrder
	err := m.QueryRowIndexCtx(ctx, &resp, goZeroBoilerplateTitanReleaseOrderOrderNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", titanReleaseOrderRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitanReleaseOrderModel) Insert(ctx context.Context, data *TitanReleaseOrder) (sql.Result, error) {
	goZeroBoilerplateTitanReleaseOrderIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderIdPrefix, data.Id)
	goZeroBoilerplateTitanReleaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderOrderNoPrefix, data.OrderNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, titanReleaseOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OrderNo, data.ProjectId, data.Title, data.Description, data.TargetEnv, data.ServicesJson, data.Status, data.ItsmProcessInstId, data.ApplicantId, data.ApplicantName, data.ApproverId, data.ApproverName, data.ScheduledTime, data.StartTime, data.EndTime)
	}, goZeroBoilerplateTitanReleaseOrderIdKey, goZeroBoilerplateTitanReleaseOrderOrderNoKey)
	return ret, err
}

func (m *defaultTitanReleaseOrderModel) Update(ctx context.Context, newData *TitanReleaseOrder) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	goZeroBoilerplateTitanReleaseOrderIdKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderIdPrefix, data.Id)
	goZeroBoilerplateTitanReleaseOrderOrderNoKey := fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, titanReleaseOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.OrderNo, newData.ProjectId, newData.Title, newData.Description, newData.TargetEnv, newData.ServicesJson, newData.Status, newData.ItsmProcessInstId, newData.ApplicantId, newData.ApplicantName, newData.ApproverId, newData.ApproverName, newData.ScheduledTime, newData.StartTime, newData.EndTime, newData.Id)
	}, goZeroBoilerplateTitanReleaseOrderIdKey, goZeroBoilerplateTitanReleaseOrderOrderNoKey)
	return err
}

func (m *defaultTitanReleaseOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoZeroBoilerplateTitanReleaseOrderIdPrefix, primary)
}

func (m *defaultTitanReleaseOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanReleaseOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTitanReleaseOrderModel) tableName() string {
	return m.table
}
