// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	titanPipelineExecFieldNames          = builder.RawFieldNames(&TitanPipelineExec{})
	titanPipelineExecRows                = strings.Join(titanPipelineExecFieldNames, ",")
	titanPipelineExecRowsExpectAutoSet   = strings.Join(stringx.Remove(titanPipelineExecFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	titanPipelineExecRowsWithPlaceHolder = strings.Join(stringx.Remove(titanPipelineExecFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTitanPipelineExecIdPrefix     = "cache:titanPipelineExec:id:"
	cacheTitanPipelineExecExecNoPrefix = "cache:titanPipelineExec:execNo:"
)

type (
	titanPipelineExecModel interface {
		Insert(ctx context.Context, data *TitanPipelineExec) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TitanPipelineExec, error)
		FindOneByExecNo(ctx context.Context, execNo string) (*TitanPipelineExec, error)
		Update(ctx context.Context, data *TitanPipelineExec) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTitanPipelineExecModel struct {
		sqlc.CachedConn
		table string
	}

	TitanPipelineExec struct {
		Id            int64        `db:"id"`
		PipelineId    int64        `db:"pipeline_id"`
		PipelineName  string       `db:"pipeline_name"`
		ExecNo        string       `db:"exec_no"`
		TriggerType   string       `db:"trigger_type"`
		TriggerBy     int64        `db:"trigger_by"`
		GitBranch     string       `db:"git_branch"`
		GitCommit     string       `db:"git_commit"`
		RuntimeParams string       `db:"runtime_params"`
		Status        string       `db:"status"`
		WorkflowId    string       `db:"workflow_id"`
		StartTime     sql.NullTime `db:"start_time"`
		EndTime       sql.NullTime `db:"end_time"`
		DurationMs    int64        `db:"duration_ms"`
		Artifacts     string       `db:"artifacts"`
		CreateTime    time.Time    `db:"create_time"`
		UpdateTime    time.Time    `db:"update_time"`
	}
)

func newTitanPipelineExecModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTitanPipelineExecModel {
	return &defaultTitanPipelineExecModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`titan_pipeline_exec`",
	}
}

func (m *defaultTitanPipelineExecModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	titanPipelineExecExecNoKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecExecNoPrefix, data.ExecNo)
	titanPipelineExecIdKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, titanPipelineExecExecNoKey, titanPipelineExecIdKey)
	return err
}

func (m *defaultTitanPipelineExecModel) FindOne(ctx context.Context, id int64) (*TitanPipelineExec, error) {
	titanPipelineExecIdKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecIdPrefix, id)
	var resp TitanPipelineExec
	err := m.QueryRowCtx(ctx, &resp, titanPipelineExecIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanPipelineExecRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitanPipelineExecModel) FindOneByExecNo(ctx context.Context, execNo string) (*TitanPipelineExec, error) {
	titanPipelineExecExecNoKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecExecNoPrefix, execNo)
	var resp TitanPipelineExec
	err := m.QueryRowIndexCtx(ctx, &resp, titanPipelineExecExecNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `exec_no` = ? limit 1", titanPipelineExecRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, execNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitanPipelineExecModel) Insert(ctx context.Context, data *TitanPipelineExec) (sql.Result, error) {
	titanPipelineExecExecNoKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecExecNoPrefix, data.ExecNo)
	titanPipelineExecIdKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, titanPipelineExecRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PipelineId, data.PipelineName, data.ExecNo, data.TriggerType, data.TriggerBy, data.GitBranch, data.GitCommit, data.RuntimeParams, data.Status, data.WorkflowId, data.StartTime, data.EndTime, data.DurationMs, data.Artifacts)
	}, titanPipelineExecExecNoKey, titanPipelineExecIdKey)
	return ret, err
}

func (m *defaultTitanPipelineExecModel) Update(ctx context.Context, newData *TitanPipelineExec) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	titanPipelineExecExecNoKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecExecNoPrefix, data.ExecNo)
	titanPipelineExecIdKey := fmt.Sprintf("%s%v", cacheTitanPipelineExecIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, titanPipelineExecRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.PipelineId, newData.PipelineName, newData.ExecNo, newData.TriggerType, newData.TriggerBy, newData.GitBranch, newData.GitCommit, newData.RuntimeParams, newData.Status, newData.WorkflowId, newData.StartTime, newData.EndTime, newData.DurationMs, newData.Artifacts, newData.Id)
	}, titanPipelineExecExecNoKey, titanPipelineExecIdKey)
	return err
}

func (m *defaultTitanPipelineExecModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTitanPipelineExecIdPrefix, primary)
}

func (m *defaultTitanPipelineExecModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanPipelineExecRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTitanPipelineExecModel) tableName() string {
	return m.table
}
