// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	titanProjectFieldNames          = builder.RawFieldNames(&TitanProject{})
	titanProjectRows                = strings.Join(titanProjectFieldNames, ",")
	titanProjectRowsExpectAutoSet   = strings.Join(stringx.Remove(titanProjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	titanProjectRowsWithPlaceHolder = strings.Join(stringx.Remove(titanProjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTitanProjectIdPrefix   = "cache:titanProject:id:"
	cacheTitanProjectNamePrefix = "cache:titanProject:name:"
)

type (
	titanProjectModel interface {
		Insert(ctx context.Context, data *TitanProject) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TitanProject, error)
		FindOneByName(ctx context.Context, name string) (*TitanProject, error)
		Update(ctx context.Context, data *TitanProject) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTitanProjectModel struct {
		sqlc.CachedConn
		table string
	}

	TitanProject struct {
		Id          int64     `db:"id"`
		Name        string    `db:"name"`
		DisplayName string    `db:"display_name"`
		Description string    `db:"description"`
		OwnerId     int64     `db:"owner_id"`
		Status      int64     `db:"status"`
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newTitanProjectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTitanProjectModel {
	return &defaultTitanProjectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`titan_project`",
	}
}

func (m *defaultTitanProjectModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	titanProjectIdKey := fmt.Sprintf("%s%v", cacheTitanProjectIdPrefix, id)
	titanProjectNameKey := fmt.Sprintf("%s%v", cacheTitanProjectNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, titanProjectIdKey, titanProjectNameKey)
	return err
}

func (m *defaultTitanProjectModel) FindOne(ctx context.Context, id int64) (*TitanProject, error) {
	titanProjectIdKey := fmt.Sprintf("%s%v", cacheTitanProjectIdPrefix, id)
	var resp TitanProject
	err := m.QueryRowCtx(ctx, &resp, titanProjectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanProjectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitanProjectModel) FindOneByName(ctx context.Context, name string) (*TitanProject, error) {
	titanProjectNameKey := fmt.Sprintf("%s%v", cacheTitanProjectNamePrefix, name)
	var resp TitanProject
	err := m.QueryRowIndexCtx(ctx, &resp, titanProjectNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", titanProjectRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitanProjectModel) Insert(ctx context.Context, data *TitanProject) (sql.Result, error) {
	titanProjectIdKey := fmt.Sprintf("%s%v", cacheTitanProjectIdPrefix, data.Id)
	titanProjectNameKey := fmt.Sprintf("%s%v", cacheTitanProjectNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, titanProjectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.DisplayName, data.Description, data.OwnerId, data.Status)
	}, titanProjectIdKey, titanProjectNameKey)
	return ret, err
}

func (m *defaultTitanProjectModel) Update(ctx context.Context, newData *TitanProject) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	titanProjectIdKey := fmt.Sprintf("%s%v", cacheTitanProjectIdPrefix, data.Id)
	titanProjectNameKey := fmt.Sprintf("%s%v", cacheTitanProjectNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, titanProjectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.DisplayName, newData.Description, newData.OwnerId, newData.Status, newData.Id)
	}, titanProjectIdKey, titanProjectNameKey)
	return err
}

func (m *defaultTitanProjectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTitanProjectIdPrefix, primary)
}

func (m *defaultTitanProjectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanProjectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTitanProjectModel) tableName() string {
	return m.table
}
