// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	titanIntegrationFieldNames          = builder.RawFieldNames(&TitanIntegration{})
	titanIntegrationRows                = strings.Join(titanIntegrationFieldNames, ",")
	titanIntegrationRowsExpectAutoSet   = strings.Join(stringx.Remove(titanIntegrationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	titanIntegrationRowsWithPlaceHolder = strings.Join(stringx.Remove(titanIntegrationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTitanIntegrationIdPrefix = "cache:titanIntegration:id:"
)

type (
	titanIntegrationModel interface {
		Insert(ctx context.Context, data *TitanIntegration) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TitanIntegration, error)
		Update(ctx context.Context, data *TitanIntegration) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTitanIntegrationModel struct {
		sqlc.CachedConn
		table string
	}

	TitanIntegration struct {
		Id          int64     `db:"id"`
		Name        string    `db:"name"`
		Category    string    `db:"category"`
		AuthType    string    `db:"auth_type"`
		Config      string    `db:"config"`
		Status      int64     `db:"status"`
		Description string    `db:"description"`
		CreatedBy   int64     `db:"created_by"`
		CreateTime  time.Time `db:"create_time"`
		UpdateTime  time.Time `db:"update_time"`
	}
)

func newTitanIntegrationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTitanIntegrationModel {
	return &defaultTitanIntegrationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`titan_integration`",
	}
}

func (m *defaultTitanIntegrationModel) Delete(ctx context.Context, id int64) error {
	titanIntegrationIdKey := fmt.Sprintf("%s%v", cacheTitanIntegrationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, titanIntegrationIdKey)
	return err
}

func (m *defaultTitanIntegrationModel) FindOne(ctx context.Context, id int64) (*TitanIntegration, error) {
	titanIntegrationIdKey := fmt.Sprintf("%s%v", cacheTitanIntegrationIdPrefix, id)
	var resp TitanIntegration
	err := m.QueryRowCtx(ctx, &resp, titanIntegrationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanIntegrationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitanIntegrationModel) Insert(ctx context.Context, data *TitanIntegration) (sql.Result, error) {
	titanIntegrationIdKey := fmt.Sprintf("%s%v", cacheTitanIntegrationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, titanIntegrationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Category, data.AuthType, data.Config, data.Status, data.Description, data.CreatedBy)
	}, titanIntegrationIdKey)
	return ret, err
}

func (m *defaultTitanIntegrationModel) Update(ctx context.Context, data *TitanIntegration) error {
	titanIntegrationIdKey := fmt.Sprintf("%s%v", cacheTitanIntegrationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, titanIntegrationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Category, data.AuthType, data.Config, data.Status, data.Description, data.CreatedBy, data.Id)
	}, titanIntegrationIdKey)
	return err
}

func (m *defaultTitanIntegrationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTitanIntegrationIdPrefix, primary)
}

func (m *defaultTitanIntegrationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titanIntegrationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTitanIntegrationModel) tableName() string {
	return m.table
}
