// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

export interface DashboardReq {
}
export interface DashboardReqParams {
	orderId?: number
}

export interface DashboardResp {
	userInfo: UserInfoResp
	order: OrderDetailResp
	sysTime: number
}

export interface LoginReq {
	mobile: string
	password: string
}

export interface LoginResp {
	accessToken: string
	accessExpire: number
	refreshAfter: number
	userId: number
	username: string
}

export interface OrderDetailReq {
}
export interface OrderDetailReqParams {
	orderId: number
}

export interface OrderDetailResp {
	orderId: number
	item: string
	amount: number
	status: string
	// 聚合用户微服务信息
	userId: number
	userName: string
	avatar: string
}

export interface RegisterReq {
	username?: string
	mobile: string
	password: string
}

export interface RegisterResp {
	id: number
}

export interface UserInfoReq {
}
export interface UserInfoReqParams {
	id?: number
}

export interface UserInfoResp {
	id: number
	name: string
	mobile: string
	avatar: string
}

