// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

export interface AdminLoginReq {
	account: string
	password: string
}

export interface AdminLoginResp {
	accessToken: string
	accessExpire: number
	refreshAfter: number
	userId: number
	username: string
	realName: string
	avatar: string
	roles: Array<string>
}

export interface AdminProfileResp {
	id: number
	username: string
	realName: string
	mobile: string
	email: string
	avatar: string
	deptName: string
	roles: Array<string>
	permissions: Array<string>
	menus: Array<SysMenuItem>
}

export interface ApproveStepReqVO {
	approved: boolean
	comment?: string
}
export interface ApproveStepReqVOParams {
}

export interface ApproveTaskReqVO {
	taskId: number
	opinion?: string
	updatedFormDataJson?: string
}
export interface ApproveTaskReqVOParams {
}

export interface AssignRolePermReq {
	roleId: number
	menuIds: Array<number>
}

export interface AsyncTaskItem {
	id: number
	taskName: string
	taskKey: string
	taskType: string
	cronExpr: string
	workflowType: string
	taskQueue: string
	payload: string
	status: number
	lastRunTime: string
	lastRunStatus: string
	remark: string
	createTime: string
	updateTime: string
}

export interface CancelExecutionReqVO {
}
export interface CancelExecutionReqVOParams {
}

export interface CancelTicketReqVO {
	reason?: string
}
export interface CancelTicketReqVOParams {
}

export interface CasdoorLoginReq {
	code: string
	state?: string
}

export interface ChangePersonalPasswordReq {
	oldPassword: string
	newPassword: string
}

export interface ClaimTaskReqVO {
	taskId: number
}
export interface ClaimTaskReqVOParams {
}

export interface ClusterVO {
	id: number
	name: string
	env: string
	apiEndpoint: string
	status: string
	version: string
	description: string
	createdBy: number
	createTime: string
	updateTime: string
}

export interface CreateClusterReqVO {
	name: string
	env: string
	apiEndpoint?: string
	kubeconfig: string
	description?: string
}

export interface CreateClusterRespVO {
	id: number
}

export interface CreateIntegrationReqVO {
	name: string
	category: string
	authType: string
	config: string
	description?: string
}

export interface CreateIntegrationRespVO {
	id: number
}

export interface CreatePipelineReqVO {
	name: string
	displayName: string
	category?: string
	gitRepo?: string
	gitBranch?: string
	stages: string
	params?: string
	triggers?: string
	description?: string
}

export interface CreatePipelineRespVO {
	id: number
}

export interface CreateProcessDefReqVO {
	procCode: string
	procName: string
	category?: string
	bpmnXml?: string
	formSchema?: string
	description?: string
}

export interface CreateSysConfigReq {
	configName: string // 参数名称
	configKey: string // 参数键名
	configValue: string // 参数键值
	configType: string // 系统内置（Y是 N否）
	remark: string // 备注说明
}

export interface CreateSysDeptReq {
	parentId: number
	deptName: string
	sort?: number
	leader?: string
	phone?: string
	status?: number
}

export interface CreateSysDictDataReq {
	dictType: string
	dictLabel: string
	dictValue: string
	dictSort?: number
	listClass?: string
	isDefault?: number
	status?: number
	remark?: string
}

export interface CreateSysDictTypeReq {
	dictName: string
	dictType: string
	status?: number
	remark?: string
}

export interface CreateSysNoticeReq {
	noticeTitle: string // 公告标题
	noticeType: number // 公告类型（1通知 2消息 3待办）
	noticeContent: string // 公告内容
	status: number // 公告状态（1正常 0关闭）
	createBy: string // 创建者
	remark?: string // 备注
}

export interface CreateSysPortalNavReq {
	title: string
	category: string
	url: string
	icon?: string
	description?: string
	tags?: string
	sort?: number
	target?: string
	status?: number
	env?: string
}

export interface CreateSysPortalNavResp {
	id: number
}

export interface CreateSysPostReq {
	postCode: string // 岗位编码
	postName: string // 岗位名称
	postSort: number // 显示顺序
	status: number // 状态（1正常 0停用）
	remark?: string // 备注
}

export interface CreateSysRoleReq {
	name: string
	code: string
	sort?: number
	dataScope?: number
	description?: string
}

export interface CreateSysUserReq {
	deptId?: number
	username: string
	password: string
	realName: string
	mobile?: string
	email?: string
	roleIds?: Array<number>
}

export interface CreateTaskReq {
	taskName: string
	taskKey: string
	taskType?: string
	cronExpr?: string
	workflowType?: string
	taskQueue?: string
	payload?: string
	status?: number
	remark?: string
}

export interface CreateTicketReqVO {
	procDefId: number
	title: string
	priority?: string
	formDataJson?: string
}

export interface CreateTicketRespVO {
	id: number
	ticketNo: string
}

export interface DashboardReq {
}
export interface DashboardReqParams {
	timestamp?: number
}

export interface DashboardResp {
	userInfo: UserInfoResp
	systemStats: DashboardSystemStats
	sysTime: number
}

export interface DashboardSystemStats {
	totalUsers: number
	activeTasks: number
	completedTasks: number
	successRate: number
}

export interface DeleteClusterReqVO {
}
export interface DeleteClusterReqVOParams {
}

export interface DeleteIntegrationReqVO {
}
export interface DeleteIntegrationReqVOParams {
}

export interface DeletePipelineReqVO {
}
export interface DeletePipelineReqVOParams {
}

export interface DeleteSysPortalNavReq {
}
export interface DeleteSysPortalNavReqParams {
}

export interface DeleteSysPortalNavResp {
	success: boolean
}

export interface DeleteTaskReq {
}
export interface DeleteTaskReqParams {
}

export interface DeleteTaskResp {
	success: boolean
}

export interface DeployProcessDefReqVO {
}
export interface DeployProcessDefReqVOParams {
}

export interface ExecutionDetailRespVO {
	execution: ExecutionVO
	steps: Array<StepExecVO>
}

export interface ExecutionVO {
	id: number
	pipelineId: number
	pipelineName: string
	execNo: string
	triggerType: string
	triggerBy: number
	gitBranch: string
	gitCommit: string
	runtimeParams: string
	status: string
	workflowId: string
	startTime: string
	endTime: string
	durationMs: number
	artifacts: string
	createTime: string
}

export interface FileUploadResp {
	url: string
	filename: string
	originalName: string
	size: number
	mimeType: string
	hash: string
}

export interface ForceLogoutReq {
}
export interface ForceLogoutReqParams {
}

export interface GetDictDataByTypeReq {
}
export interface GetDictDataByTypeReqParams {
}

export interface GetDictDataByTypeResp {
	list: Array<SysDictDataItem>
}

export interface GetExecutionDetailReqVO {
}
export interface GetExecutionDetailReqVOParams {
}

export interface GetMyNoticeFeedReq {
}
export interface GetMyNoticeFeedReqParams {
	limit?: number
}

export interface GetMyNoticeFeedResp {
	totalUnread: number
	list: Array<NoticeFeedItem>
}

export interface GetPipelineReqVO {
}
export interface GetPipelineReqVOParams {
}

export interface GetPortalNavListReq {
}
export interface GetPortalNavListReqParams {
	status?: number
	env?: string
}

export interface GetPortalNavListResp {
	list: Array<PortalNavDTO>
}

export interface GetProcessDefReq {
}
export interface GetProcessDefReqParams {
}

export interface GetStepLogReqVO {
}
export interface GetStepLogReqVOParams {
	offset: number
}

export interface GetStepLogRespVO {
	content: string
	nextOffset: number
	isEnd: boolean
}

export interface GetSysMenuTreeResp {
	list: Array<SysMenuItem>
}

export interface GetSysPortalNavReq {
}
export interface GetSysPortalNavReqParams {
}

export interface GetTaskReq {
}
export interface GetTaskReqParams {
}

export interface GetTicketDetailReqVO {
}
export interface GetTicketDetailReqVOParams {
}

export interface GetTicketTrajectoryReqVO {
}
export interface GetTicketTrajectoryReqVOParams {
}

export interface IntegrationVO {
	id: number
	name: string
	category: string
	authType: string
	config: string
	status: number
	description: string
	createdBy: number
	createTime: string
	updateTime: string
}

export interface ListClustersReqVO {
}
export interface ListClustersReqVOParams {
	env?: string
	page: number
	pageSize: number
}

export interface ListClustersRespVO {
	total: number
	list: Array<ClusterVO>
}

export interface ListExecutionsReqVO {
}
export interface ListExecutionsReqVOParams {
	pipelineId?: number
	status?: string
	page: number
	pageSize: number
}

export interface ListExecutionsRespVO {
	total: number
	list: Array<ExecutionVO>
}

export interface ListIntegrationsReqVO {
}
export interface ListIntegrationsReqVOParams {
	category?: string
	page: number
	pageSize: number
}

export interface ListIntegrationsRespVO {
	total: number
	list: Array<IntegrationVO>
}

export interface ListNamespacesReqVO {
}
export interface ListNamespacesReqVOParams {
}

export interface ListNamespacesRespVO {
	namespaces: Array<string>
}

export interface ListOnlineSessionsReq {
}
export interface ListOnlineSessionsReqParams {
	page: number
	pageSize: number
	username?: string
	loginIp?: string
}

export interface ListOnlineSessionsResp {
	total: number
	list: Array<OnlineSessionItem>
}

export interface ListPipelinesReqVO {
}
export interface ListPipelinesReqVOParams {
	category?: string
	keyword?: string
	page: number
	pageSize: number
}

export interface ListPipelinesRespVO {
	total: number
	list: Array<PipelineVO>
}

export interface ListProcessDefsReq {
}
export interface ListProcessDefsReqParams {
	page: number
	pageSize: number
	category?: string
	status?: number
	keyword?: string
}

export interface ListProcessDefsResp {
	total: number
	list: Array<ProcessDefVO>
}

export interface ListSlaPoliciesRespVO {
	list: Array<SlaPolicyVO>
}

export interface ListSysApisResp {
	list: Array<SysApiItem>
}

export interface ListSysConfigReq {
}
export interface ListSysConfigReqParams {
	page: number
	pageSize: number
	keyword?: string
}

export interface ListSysConfigResp {
	total: number
	list: Array<SysConfigItem>
}

export interface ListSysDeptReq {
}
export interface ListSysDeptReqParams {
	keyword?: string
	status?: number
}

export interface ListSysDeptResp {
	list: Array<SysDeptItem>
}

export interface ListSysDictDataReq {
}
export interface ListSysDictDataReqParams {
	page: number
	pageSize: number
	dictType: string
	keyword?: string
	status?: number
}

export interface ListSysDictDataResp {
	total: number
	list: Array<SysDictDataItem>
}

export interface ListSysDictTypesReq {
}
export interface ListSysDictTypesReqParams {
	page: number
	pageSize: number
	keyword?: string
	status?: number
}

export interface ListSysDictTypesResp {
	total: number
	list: Array<SysDictTypeItem>
}

export interface ListSysLoginLogsReq {
}
export interface ListSysLoginLogsReqParams {
	page: number
	pageSize: number
	username?: string
	status?: number
}

export interface ListSysLoginLogsResp {
	total: number
	list: Array<SysLoginLogItem>
}

export interface ListSysNoticeReq {
}
export interface ListSysNoticeReqParams {
	page: number
	pageSize: number
	keyword?: string
}

export interface ListSysNoticeResp {
	total: number
	list: Array<SysNoticeItem>
}

export interface ListSysOperLogsReq {
}
export interface ListSysOperLogsReqParams {
	page: number
	pageSize: number
	operName?: string
	title?: string
	status?: number
}

export interface ListSysOperLogsResp {
	total: number
	list: Array<SysOperLogItem>
}

export interface ListSysPortalNavReq {
}
export interface ListSysPortalNavReqParams {
	page?: number
	pageSize?: number
	title?: string
	category?: string
	env?: string
	status?: number
}

export interface ListSysPortalNavResp {
	total: number
	list: Array<PortalNavDTO>
}

export interface ListSysPostReq {
}
export interface ListSysPostReqParams {
	page: number
	pageSize: number
	keyword?: string
}

export interface ListSysPostResp {
	total: number
	list: Array<SysPostItem>
}

export interface ListSysRolesReq {
}
export interface ListSysRolesReqParams {
	page: number
	pageSize: number
	keyword?: string
}

export interface ListSysRolesResp {
	total: number
	list: Array<SysRoleItem>
}

export interface ListSysUsersReq {
}
export interface ListSysUsersReqParams {
	page: number
	pageSize: number
	keyword?: string
	deptId?: number
}

export interface ListSysUsersResp {
	total: number
	list: Array<SysUserItem>
}

export interface ListTasksReq {
}
export interface ListTasksReqParams {
	page: number
	pageSize: number
	taskName?: string
	taskKey?: string
	status?: number
}

export interface ListTasksResp {
	total: number
	list: Array<AsyncTaskItem>
}

export interface ListTicketsReqVO {
}
export interface ListTicketsReqVOParams {
	page: number
	pageSize: number
	viewType?: string
	status?: string
	priority?: string
	keyword?: string
}

export interface ListTicketsRespVO {
	total: number
	list: Array<TicketVO>
}

export interface LoginReq {
	mobile: string
	password: string
}

export interface LoginResp {
	accessToken: string
	accessExpire: number
	refreshAfter: number
	userId: number
	username: string
}

export interface MarkAllNoticesReadReq {
	noticeType?: number
}

export interface MarkNoticeReadReq {
	noticeId: number
}

export interface NoticeFeedItem {
	id: number
	noticeTitle: string
	noticeType: number
	noticeContent: string
	status: number
	createBy: string
	remark: string
	createTime: string
	updateTime: string
	isRead: boolean
}

export interface OnlineSessionItem {
	sessionId: string
	userId: number
	username: string
	realName: string
	deptName: string
	loginIp: string
	loginLocation: string
	browser: string
	os: string
	loginTime: string
	isCurrent: boolean
}

export interface PipelineVO {
	id: number
	name: string
	displayName: string
	category: string
	gitRepo: string
	gitBranch: string
	stages: string
	params: string
	triggers: string
	status: number
	description: string
	createdBy: number
	createTime: string
	updateTime: string
}

export interface PortalNavDTO {
	id: number
	title: string
	category: string
	url: string
	icon: string
	description: string
	tags: string
	sort: number
	target: string
	status: number
	env: string
	createTime: string
	updateTime: string
}

export interface ProcessDefVO {
	id: number
	procCode: string
	procName: string
	category: string
	bpmnXml: string
	formSchema: string
	version: number
	status: number
	description: string
	createTime: string
	updateTime: string
}

export interface RegisterReq {
	username?: string
	mobile: string
	password: string
}

export interface RegisterResp {
	id: number
}

export interface RejectTaskReqVO {
	taskId: number
	opinion?: string
}
export interface RejectTaskReqVOParams {
}

export interface RunTaskOnceReq {
}
export interface RunTaskOnceReqParams {
}

export interface RunTaskOnceResp {
	success: boolean
	workflowId: string
	runId: string
	message: string
}

export interface SlaPolicyVO {
	id: number
	priority: string
	calendarType: string
	responseLimitMin: number
	resolveLimitMin: number
	warnThresholdPct: number
}

export interface StepExecVO {
	id: number
	execId: number
	stageId: string
	stepId: string
	stepName: string
	stepType: string
	status: string
	logPath: string
	errorMsg: string
	startTime: string
	endTime: string
	durationMs: number
}

export interface SysApiItem {
	id: number
	apiGroup: string
	title: string
	path: string
	method: string
	isAutoSync: number
}

export interface SysConfigItem {
	id: number // 参数主键
	configName: string // 参数名称
	configKey: string // 参数键名
	configValue: string // 参数键值
	configType: string // 系统内置（Y是 N否）
	remark: string // 备注说明
	createTime: string // 创建时间
	updateTime: string // 更新时间
}

export interface SysDeptItem {
	id: number
	parentId: number
	ancestors: string
	deptName: string
	sort: number
	leader: string
	phone: string
	status: number
	createTime: string
	updateTime: string
	children?: Array<SysDeptItem>
}

export interface SysDictDataItem {
	id: number
	dictType: string
	dictLabel: string
	dictValue: string
	dictSort: number
	listClass: string
	isDefault: number
	status: number
	remark: string
	createTime: string
}

export interface SysDictTypeItem {
	id: number
	dictName: string
	dictType: string
	status: number
	remark: string
	createTime: string
}

export interface SysEmptyResp {
	success: boolean
}

export interface SysIdReq {
}
export interface SysIdReqParams {
}

export interface SysIdResp {
	id: number
}

export interface SysLoginLogItem {
	id: number
	username: string
	loginIp: string
	browser: string
	os: string
	status: number
	msg: string
	loginTime: string
}

export interface SysMenuItem {
	id: number
	parentId: number
	title: string
	type: number // 1:目录 2:菜单 3:按钮
	path: string
	component: string
	permissionCode: string
	icon: string
	sort: number
	children?: Array<SysMenuItem>
}

export interface SysNoticeItem {
	id: number // 公告ID
	noticeTitle: string // 公告标题
	noticeType: number // 公告类型（1通知 2消息 3待办）
	noticeContent: string // 公告内容
	status: number // 公告状态（1正常 0关闭）
	createBy: string // 创建者
	remark: string // 备注
	createTime: string // 创建时间
	updateTime: string // 更新时间
}

export interface SysOperLogItem {
	id: number
	title: string
	operName: string
	operUrl: string
	operMethod: string
	operIp: string
	status: number
	errorMsg: string
	costTime: number
	createTime: string
}

export interface SysPostItem {
	id: number // 岗位ID
	postCode: string // 岗位编码
	postName: string // 岗位名称
	postSort: number // 显示顺序
	status: number // 状态（1正常 0停用）
	remark: string // 备注
	createTime: string // 创建时间
	updateTime: string // 更新时间
}

export interface SysRoleItem {
	id: number
	name: string
	code: string
	sort?: number
	dataScope?: number
	status: number
	description?: string
	menuIds?: Array<number>
	createTime: string
}

export interface SysUserItem {
	id: number
	deptId: number
	deptName: string
	username: string
	realName: string
	mobile: string
	email: string
	avatar: string
	status: number
	roleNames: Array<string>
	roleIds: Array<number>
	createTime: string
}

export interface TaskLogVO {
	id: number
	taskId: number
	nodeId: string
	nodeName: string
	operatorId: number
	operatorName: string
	actionType: string
	opinion?: string
	durationSec: number
	createTime: string
}

export interface TaskVO {
	id: number
	instId: number
	nodeId: string
	nodeName: string
	taskType: string
	approvalMode: string
	assigneeId: number
	assigneeName?: string
	status: string
	claimAt?: string
	createTime: string
}

export interface TestClusterReqVO {
}
export interface TestClusterReqVOParams {
}

export interface TestClusterRespVO {
	success: boolean
	version: string
	message: string
}

export interface TestIntegrationReqVO {
}
export interface TestIntegrationReqVOParams {
}

export interface TestIntegrationRespVO {
	success: boolean
	message: string
}

export interface TicketDetailRespVO {
	ticket: TicketVO
	formDataJson: string
	formSchemaJson: string
	bpmnXml: string
	activeTasks: Array<TaskVO>
	logs: Array<TaskLogVO>
}

export interface TicketTrajectoryRespVO {
	bpmnXml: string
	completedNodeIds: Array<string>
	activeNodeIds: Array<string>
	rejectedNodeIds: Array<string>
	logs: Array<TaskLogVO>
}

export interface TicketVO {
	id: number
	ticketNo: string
	title: string
	priority: string
	procDefId: number
	procName?: string
	initiatorId: number
	initiatorName?: string
	currentNodeId: string
	currentNodeName: string
	status: string
	slaStatus: string
	slaResponseDeadline?: string
	slaResolveDeadline?: string
	createTime: string
}

export interface ToggleTaskStatusReq {
	status: number
}
export interface ToggleTaskStatusReqParams {
}

export interface ToggleTaskStatusResp {
	success: boolean
}

export interface TransferTaskReqVO {
	taskId: number
	targetUserId: number
	opinion?: string
}
export interface TransferTaskReqVOParams {
}

export interface TriggerPipelineReqVO {
	triggerType?: string
	gitBranch?: string
	gitCommit?: string
	runtimeParams?: string
}
export interface TriggerPipelineReqVOParams {
}

export interface TriggerPipelineRespVO {
	execId: number
	execNo: string
}

export interface UpdateClusterReqVO {
	name?: string
	env?: string
	apiEndpoint?: string
	kubeconfig?: string
	description?: string
}
export interface UpdateClusterReqVOParams {
}

export interface UpdateIntegrationReqVO {
	name?: string
	authType?: string
	config?: string
	status?: number
	description?: string
}
export interface UpdateIntegrationReqVOParams {
}

export interface UpdatePersonalProfileReq {
	realName: string
	mobile?: string
	email?: string
	avatar?: string
}

export interface UpdatePipelineReqVO {
	displayName?: string
	category?: string
	gitRepo?: string
	gitBranch?: string
	stages?: string
	params?: string
	triggers?: string
	status?: number
	description?: string
}
export interface UpdatePipelineReqVOParams {
}

export interface UpdateProcessDefReqVO {
	procName?: string
	category?: string
	bpmnXml?: string
	formSchema?: string
	description?: string
	status?: number
}
export interface UpdateProcessDefReqVOParams {
}

export interface UpdateSlaPolicyReqVO {
	responseLimitMin?: number
	resolveLimitMin?: number
	warnThresholdPct?: number
}
export interface UpdateSlaPolicyReqVOParams {
}

export interface UpdateSysConfigReq {
	id: number // 参数主键
	configName: string // 参数名称
	configKey: string // 参数键名
	configValue: string // 参数键值
	configType: string // 系统内置（Y是 N否）
	remark: string // 备注说明
}

export interface UpdateSysDeptReq {
	id: number
	parentId: number
	deptName: string
	sort: number
	leader?: string
	phone?: string
	status: number
}

export interface UpdateSysDictDataReq {
	id: number
	dictType: string
	dictLabel: string
	dictValue: string
	dictSort: number
	listClass?: string
	isDefault: number
	status: number
	remark?: string
}

export interface UpdateSysDictTypeReq {
	id: number
	dictName: string
	dictType: string
	status: number
	remark?: string
}

export interface UpdateSysNoticeReq {
	id: number // 公告ID
	noticeTitle: string // 公告标题
	noticeType: number // 公告类型（1通知 2消息 3待办）
	noticeContent: string // 公告内容
	status: number // 公告状态（1正常 0关闭）
	createBy: string // 创建者
	remark: string // 备注
}

export interface UpdateSysPortalNavReq {
	title: string
	category: string
	url: string
	icon?: string
	description?: string
	tags?: string
	sort?: number
	target?: string
	status?: number
	env?: string
}
export interface UpdateSysPortalNavReqParams {
}

export interface UpdateSysPortalNavResp {
	success: boolean
}

export interface UpdateSysPostReq {
	id: number // 岗位ID
	postCode: string // 岗位编码
	postName: string // 岗位名称
	postSort: number // 显示顺序
	status: number // 状态（1正常 0停用）
	remark: string // 备注
}

export interface UpdateSysRoleReq {
	id: number
	name: string
	code: string
	sort?: number
	dataScope?: number
	description?: string
	status: number
}

export interface UpdateSysUserReq {
	id: number
	deptId?: number
	realName: string
	mobile?: string
	email?: string
	status: number
	roleIds?: Array<number>
}

export interface UpdateTaskReq {
	taskName: string
	taskType?: string
	cronExpr?: string
	workflowType?: string
	taskQueue?: string
	payload?: string
	status?: number
	remark?: string
}
export interface UpdateTaskReqParams {
}

export interface UserInfoReq {
}
export interface UserInfoReqParams {
	id?: number
}

export interface UserInfoResp {
	id: number
	name: string
	mobile: string
	avatar: string
}

export interface UserProfileResp {
	userId: number
	username: string
	realName: string
	avatar: string
	mobile: string
	email: string
	userType: string // "employee" or "customer"
	roles: Array<string>
	deptName: string
}

