// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: itsm.proto

package itsm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_itsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_itsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{1}
}

func (x *PingReq) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_itsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{2}
}

func (x *PingResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 流程定义相关
type ProcessDefItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcCode      string                 `protobuf:"bytes,2,opt,name=procCode,proto3" json:"procCode,omitempty"`
	ProcName      string                 `protobuf:"bytes,3,opt,name=procName,proto3" json:"procName,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	BpmnXml       string                 `protobuf:"bytes,5,opt,name=bpmnXml,proto3" json:"bpmnXml,omitempty"`
	FormSchema    string                 `protobuf:"bytes,6,opt,name=formSchema,proto3" json:"formSchema,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"` // 1-草稿, 2-已发布, 3-已停用
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime    string                 `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDefItem) Reset() {
	*x = ProcessDefItem{}
	mi := &file_itsm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDefItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDefItem) ProtoMessage() {}

func (x *ProcessDefItem) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDefItem.ProtoReflect.Descriptor instead.
func (*ProcessDefItem) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessDefItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessDefItem) GetProcCode() string {
	if x != nil {
		return x.ProcCode
	}
	return ""
}

func (x *ProcessDefItem) GetProcName() string {
	if x != nil {
		return x.ProcName
	}
	return ""
}

func (x *ProcessDefItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProcessDefItem) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *ProcessDefItem) GetFormSchema() string {
	if x != nil {
		return x.FormSchema
	}
	return ""
}

func (x *ProcessDefItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProcessDefItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProcessDefItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProcessDefItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *ProcessDefItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type CreateProcessDefReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcCode      string                 `protobuf:"bytes,1,opt,name=procCode,proto3" json:"procCode,omitempty"`
	ProcName      string                 `protobuf:"bytes,2,opt,name=procName,proto3" json:"procName,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BpmnXml       string                 `protobuf:"bytes,4,opt,name=bpmnXml,proto3" json:"bpmnXml,omitempty"`
	FormSchema    string                 `protobuf:"bytes,5,opt,name=formSchema,proto3" json:"formSchema,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,7,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProcessDefReq) Reset() {
	*x = CreateProcessDefReq{}
	mi := &file_itsm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessDefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessDefReq) ProtoMessage() {}

func (x *CreateProcessDefReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessDefReq.ProtoReflect.Descriptor instead.
func (*CreateProcessDefReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProcessDefReq) GetProcCode() string {
	if x != nil {
		return x.ProcCode
	}
	return ""
}

func (x *CreateProcessDefReq) GetProcName() string {
	if x != nil {
		return x.ProcName
	}
	return ""
}

func (x *CreateProcessDefReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProcessDefReq) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *CreateProcessDefReq) GetFormSchema() string {
	if x != nil {
		return x.FormSchema
	}
	return ""
}

func (x *CreateProcessDefReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProcessDefReq) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreateProcessDefResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProcessDefResp) Reset() {
	*x = CreateProcessDefResp{}
	mi := &file_itsm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessDefResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessDefResp) ProtoMessage() {}

func (x *CreateProcessDefResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessDefResp.ProtoReflect.Descriptor instead.
func (*CreateProcessDefResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProcessDefResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProcessDefReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcName      string                 `protobuf:"bytes,2,opt,name=procName,proto3" json:"procName,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	BpmnXml       string                 `protobuf:"bytes,4,opt,name=bpmnXml,proto3" json:"bpmnXml,omitempty"`
	FormSchema    string                 `protobuf:"bytes,5,opt,name=formSchema,proto3" json:"formSchema,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProcessDefReq) Reset() {
	*x = UpdateProcessDefReq{}
	mi := &file_itsm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessDefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessDefReq) ProtoMessage() {}

func (x *UpdateProcessDefReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessDefReq.ProtoReflect.Descriptor instead.
func (*UpdateProcessDefReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProcessDefReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProcessDefReq) GetProcName() string {
	if x != nil {
		return x.ProcName
	}
	return ""
}

func (x *UpdateProcessDefReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateProcessDefReq) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *UpdateProcessDefReq) GetFormSchema() string {
	if x != nil {
		return x.FormSchema
	}
	return ""
}

func (x *UpdateProcessDefReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProcessDefReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetProcessDefReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcCode      string                 `protobuf:"bytes,2,opt,name=procCode,proto3" json:"procCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessDefReq) Reset() {
	*x = GetProcessDefReq{}
	mi := &file_itsm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessDefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessDefReq) ProtoMessage() {}

func (x *GetProcessDefReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessDefReq.ProtoReflect.Descriptor instead.
func (*GetProcessDefReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{7}
}

func (x *GetProcessDefReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProcessDefReq) GetProcCode() string {
	if x != nil {
		return x.ProcCode
	}
	return ""
}

type ListProcessDefReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessDefReq) Reset() {
	*x = ListProcessDefReq{}
	mi := &file_itsm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessDefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessDefReq) ProtoMessage() {}

func (x *ListProcessDefReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessDefReq.ProtoReflect.Descriptor instead.
func (*ListProcessDefReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{8}
}

func (x *ListProcessDefReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProcessDefReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProcessDefReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListProcessDefReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListProcessDefReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListProcessDefResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*ProcessDefItem      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessDefResp) Reset() {
	*x = ListProcessDefResp{}
	mi := &file_itsm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessDefResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessDefResp) ProtoMessage() {}

func (x *ListProcessDefResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessDefResp.ProtoReflect.Descriptor instead.
func (*ListProcessDefResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{9}
}

func (x *ListProcessDefResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProcessDefResp) GetList() []*ProcessDefItem {
	if x != nil {
		return x.List
	}
	return nil
}

type DeployProcessDefReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployProcessDefReq) Reset() {
	*x = DeployProcessDefReq{}
	mi := &file_itsm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployProcessDefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployProcessDefReq) ProtoMessage() {}

func (x *DeployProcessDefReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployProcessDefReq.ProtoReflect.Descriptor instead.
func (*DeployProcessDefReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{10}
}

func (x *DeployProcessDefReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 工单流转相关
type TicketItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketNo            string                 `protobuf:"bytes,2,opt,name=ticketNo,proto3" json:"ticketNo,omitempty"`
	Title               string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Priority            string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	ProcDefId           int64                  `protobuf:"varint,5,opt,name=procDefId,proto3" json:"procDefId,omitempty"`
	ProcName            string                 `protobuf:"bytes,6,opt,name=procName,proto3" json:"procName,omitempty"`
	InitiatorId         int64                  `protobuf:"varint,7,opt,name=initiatorId,proto3" json:"initiatorId,omitempty"`
	InitiatorName       string                 `protobuf:"bytes,8,opt,name=initiatorName,proto3" json:"initiatorName,omitempty"`
	CurrentNodeId       string                 `protobuf:"bytes,9,opt,name=currentNodeId,proto3" json:"currentNodeId,omitempty"`
	CurrentNodeName     string                 `protobuf:"bytes,10,opt,name=currentNodeName,proto3" json:"currentNodeName,omitempty"`
	Status              string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	SlaStatus           string                 `protobuf:"bytes,12,opt,name=slaStatus,proto3" json:"slaStatus,omitempty"`
	SlaResponseDeadline string                 `protobuf:"bytes,13,opt,name=slaResponseDeadline,proto3" json:"slaResponseDeadline,omitempty"`
	SlaResolveDeadline  string                 `protobuf:"bytes,14,opt,name=slaResolveDeadline,proto3" json:"slaResolveDeadline,omitempty"`
	CreateTime          string                 `protobuf:"bytes,15,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TicketItem) Reset() {
	*x = TicketItem{}
	mi := &file_itsm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketItem) ProtoMessage() {}

func (x *TicketItem) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketItem.ProtoReflect.Descriptor instead.
func (*TicketItem) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{11}
}

func (x *TicketItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketItem) GetTicketNo() string {
	if x != nil {
		return x.TicketNo
	}
	return ""
}

func (x *TicketItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TicketItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *TicketItem) GetProcDefId() int64 {
	if x != nil {
		return x.ProcDefId
	}
	return 0
}

func (x *TicketItem) GetProcName() string {
	if x != nil {
		return x.ProcName
	}
	return ""
}

func (x *TicketItem) GetInitiatorId() int64 {
	if x != nil {
		return x.InitiatorId
	}
	return 0
}

func (x *TicketItem) GetInitiatorName() string {
	if x != nil {
		return x.InitiatorName
	}
	return ""
}

func (x *TicketItem) GetCurrentNodeId() string {
	if x != nil {
		return x.CurrentNodeId
	}
	return ""
}

func (x *TicketItem) GetCurrentNodeName() string {
	if x != nil {
		return x.CurrentNodeName
	}
	return ""
}

func (x *TicketItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketItem) GetSlaStatus() string {
	if x != nil {
		return x.SlaStatus
	}
	return ""
}

func (x *TicketItem) GetSlaResponseDeadline() string {
	if x != nil {
		return x.SlaResponseDeadline
	}
	return ""
}

func (x *TicketItem) GetSlaResolveDeadline() string {
	if x != nil {
		return x.SlaResolveDeadline
	}
	return ""
}

func (x *TicketItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type CreateTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcDefId     int64                  `protobuf:"varint,1,opt,name=procDefId,proto3" json:"procDefId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	InitiatorId   int64                  `protobuf:"varint,4,opt,name=initiatorId,proto3" json:"initiatorId,omitempty"`
	InitiatorName string                 `protobuf:"bytes,5,opt,name=initiatorName,proto3" json:"initiatorName,omitempty"`
	FormDataJson  string                 `protobuf:"bytes,6,opt,name=formDataJson,proto3" json:"formDataJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketReq) Reset() {
	*x = CreateTicketReq{}
	mi := &file_itsm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketReq) ProtoMessage() {}

func (x *CreateTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketReq.ProtoReflect.Descriptor instead.
func (*CreateTicketReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTicketReq) GetProcDefId() int64 {
	if x != nil {
		return x.ProcDefId
	}
	return 0
}

func (x *CreateTicketReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTicketReq) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTicketReq) GetInitiatorId() int64 {
	if x != nil {
		return x.InitiatorId
	}
	return 0
}

func (x *CreateTicketReq) GetInitiatorName() string {
	if x != nil {
		return x.InitiatorName
	}
	return ""
}

func (x *CreateTicketReq) GetFormDataJson() string {
	if x != nil {
		return x.FormDataJson
	}
	return ""
}

type CreateTicketResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketNo      string                 `protobuf:"bytes,2,opt,name=ticketNo,proto3" json:"ticketNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketResp) Reset() {
	*x = CreateTicketResp{}
	mi := &file_itsm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketResp) ProtoMessage() {}

func (x *CreateTicketResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketResp.ProtoReflect.Descriptor instead.
func (*CreateTicketResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTicketResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTicketResp) GetTicketNo() string {
	if x != nil {
		return x.TicketNo
	}
	return ""
}

type GetTicketDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketNo      string                 `protobuf:"bytes,2,opt,name=ticketNo,proto3" json:"ticketNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketDetailReq) Reset() {
	*x = GetTicketDetailReq{}
	mi := &file_itsm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketDetailReq) ProtoMessage() {}

func (x *GetTicketDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketDetailReq.ProtoReflect.Descriptor instead.
func (*GetTicketDetailReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{14}
}

func (x *GetTicketDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTicketDetailReq) GetTicketNo() string {
	if x != nil {
		return x.TicketNo
	}
	return ""
}

type TaskItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InstId        int64                  `protobuf:"varint,2,opt,name=instId,proto3" json:"instId,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	TaskType      string                 `protobuf:"bytes,5,opt,name=taskType,proto3" json:"taskType,omitempty"`
	ApprovalMode  string                 `protobuf:"bytes,6,opt,name=approvalMode,proto3" json:"approvalMode,omitempty"`
	AssigneeId    int64                  `protobuf:"varint,7,opt,name=assigneeId,proto3" json:"assigneeId,omitempty"`
	AssigneeName  string                 `protobuf:"bytes,8,opt,name=assigneeName,proto3" json:"assigneeName,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ClaimAt       string                 `protobuf:"bytes,10,opt,name=claimAt,proto3" json:"claimAt,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,11,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	CreateTime    string                 `protobuf:"bytes,12,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskItem) Reset() {
	*x = TaskItem{}
	mi := &file_itsm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskItem) ProtoMessage() {}

func (x *TaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskItem.ProtoReflect.Descriptor instead.
func (*TaskItem) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{15}
}

func (x *TaskItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskItem) GetInstId() int64 {
	if x != nil {
		return x.InstId
	}
	return 0
}

func (x *TaskItem) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskItem) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TaskItem) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskItem) GetApprovalMode() string {
	if x != nil {
		return x.ApprovalMode
	}
	return ""
}

func (x *TaskItem) GetAssigneeId() int64 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

func (x *TaskItem) GetAssigneeName() string {
	if x != nil {
		return x.AssigneeName
	}
	return ""
}

func (x *TaskItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskItem) GetClaimAt() string {
	if x != nil {
		return x.ClaimAt
	}
	return ""
}

func (x *TaskItem) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *TaskItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type TaskLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	OperatorId    int64                  `protobuf:"varint,5,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	OperatorName  string                 `protobuf:"bytes,6,opt,name=operatorName,proto3" json:"operatorName,omitempty"`
	ActionType    string                 `protobuf:"bytes,7,opt,name=actionType,proto3" json:"actionType,omitempty"`
	Opinion       string                 `protobuf:"bytes,8,opt,name=opinion,proto3" json:"opinion,omitempty"`
	DurationSec   int32                  `protobuf:"varint,9,opt,name=durationSec,proto3" json:"durationSec,omitempty"`
	CreateTime    string                 `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogItem) Reset() {
	*x = TaskLogItem{}
	mi := &file_itsm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogItem) ProtoMessage() {}

func (x *TaskLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogItem.ProtoReflect.Descriptor instead.
func (*TaskLogItem) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{16}
}

func (x *TaskLogItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskLogItem) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskLogItem) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskLogItem) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TaskLogItem) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *TaskLogItem) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *TaskLogItem) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *TaskLogItem) GetOpinion() string {
	if x != nil {
		return x.Opinion
	}
	return ""
}

func (x *TaskLogItem) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *TaskLogItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type TicketDetailResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ticket         *TicketItem            `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	FormDataJson   string                 `protobuf:"bytes,2,opt,name=formDataJson,proto3" json:"formDataJson,omitempty"`
	FormSchemaJson string                 `protobuf:"bytes,3,opt,name=formSchemaJson,proto3" json:"formSchemaJson,omitempty"`
	BpmnXml        string                 `protobuf:"bytes,4,opt,name=bpmnXml,proto3" json:"bpmnXml,omitempty"`
	ActiveTasks    []*TaskItem            `protobuf:"bytes,5,rep,name=activeTasks,proto3" json:"activeTasks,omitempty"`
	Logs           []*TaskLogItem         `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TicketDetailResp) Reset() {
	*x = TicketDetailResp{}
	mi := &file_itsm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDetailResp) ProtoMessage() {}

func (x *TicketDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDetailResp.ProtoReflect.Descriptor instead.
func (*TicketDetailResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{17}
}

func (x *TicketDetailResp) GetTicket() *TicketItem {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *TicketDetailResp) GetFormDataJson() string {
	if x != nil {
		return x.FormDataJson
	}
	return ""
}

func (x *TicketDetailResp) GetFormSchemaJson() string {
	if x != nil {
		return x.FormSchemaJson
	}
	return ""
}

func (x *TicketDetailResp) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *TicketDetailResp) GetActiveTasks() []*TaskItem {
	if x != nil {
		return x.ActiveTasks
	}
	return nil
}

func (x *TicketDetailResp) GetLogs() []*TaskLogItem {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ListTicketsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	ViewType      string                 `protobuf:"bytes,3,opt,name=viewType,proto3" json:"viewType,omitempty"` // "todo", "done", "my_submitted", "all", "sla_warning"
	UserId        int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Keyword       string                 `protobuf:"bytes,7,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsReq) Reset() {
	*x = ListTicketsReq{}
	mi := &file_itsm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsReq) ProtoMessage() {}

func (x *ListTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsReq.ProtoReflect.Descriptor instead.
func (*ListTicketsReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{18}
}

func (x *ListTicketsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTicketsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTicketsReq) GetViewType() string {
	if x != nil {
		return x.ViewType
	}
	return ""
}

func (x *ListTicketsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTicketsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTicketsReq) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ListTicketsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListTicketsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*TicketItem          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResp) Reset() {
	*x = ListTicketsResp{}
	mi := &file_itsm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResp) ProtoMessage() {}

func (x *ListTicketsResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResp.ProtoReflect.Descriptor instead.
func (*ListTicketsResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{19}
}

func (x *ListTicketsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTicketsResp) GetList() []*TicketItem {
	if x != nil {
		return x.List
	}
	return nil
}

type ClaimTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskReq) Reset() {
	*x = ClaimTaskReq{}
	mi := &file_itsm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskReq) ProtoMessage() {}

func (x *ClaimTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskReq.ProtoReflect.Descriptor instead.
func (*ClaimTaskReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{20}
}

func (x *ClaimTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ClaimTaskReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimTaskReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ApproveTaskReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              int64                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId              int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName            string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Opinion             string                 `protobuf:"bytes,4,opt,name=opinion,proto3" json:"opinion,omitempty"`
	UpdatedFormDataJson string                 `protobuf:"bytes,5,opt,name=updatedFormDataJson,proto3" json:"updatedFormDataJson,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApproveTaskReq) Reset() {
	*x = ApproveTaskReq{}
	mi := &file_itsm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTaskReq) ProtoMessage() {}

func (x *ApproveTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTaskReq.ProtoReflect.Descriptor instead.
func (*ApproveTaskReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{21}
}

func (x *ApproveTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ApproveTaskReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApproveTaskReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ApproveTaskReq) GetOpinion() string {
	if x != nil {
		return x.Opinion
	}
	return ""
}

func (x *ApproveTaskReq) GetUpdatedFormDataJson() string {
	if x != nil {
		return x.UpdatedFormDataJson
	}
	return ""
}

type RejectTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Opinion       string                 `protobuf:"bytes,4,opt,name=opinion,proto3" json:"opinion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTaskReq) Reset() {
	*x = RejectTaskReq{}
	mi := &file_itsm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTaskReq) ProtoMessage() {}

func (x *RejectTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTaskReq.ProtoReflect.Descriptor instead.
func (*RejectTaskReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{22}
}

func (x *RejectTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RejectTaskReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RejectTaskReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RejectTaskReq) GetOpinion() string {
	if x != nil {
		return x.Opinion
	}
	return ""
}

type TransferTaskReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int64                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName       string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	TargetUserId   int64                  `protobuf:"varint,4,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	TargetUserName string                 `protobuf:"bytes,5,opt,name=targetUserName,proto3" json:"targetUserName,omitempty"`
	Opinion        string                 `protobuf:"bytes,6,opt,name=opinion,proto3" json:"opinion,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferTaskReq) Reset() {
	*x = TransferTaskReq{}
	mi := &file_itsm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTaskReq) ProtoMessage() {}

func (x *TransferTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTaskReq.ProtoReflect.Descriptor instead.
func (*TransferTaskReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{23}
}

func (x *TransferTaskReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TransferTaskReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransferTaskReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *TransferTaskReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *TransferTaskReq) GetTargetUserName() string {
	if x != nil {
		return x.TargetUserName
	}
	return ""
}

func (x *TransferTaskReq) GetOpinion() string {
	if x != nil {
		return x.Opinion
	}
	return ""
}

type CancelTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTicketReq) Reset() {
	*x = CancelTicketReq{}
	mi := &file_itsm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketReq) ProtoMessage() {}

func (x *CancelTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketReq.ProtoReflect.Descriptor instead.
func (*CancelTicketReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{24}
}

func (x *CancelTicketReq) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *CancelTicketReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelTicketReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CancelTicketReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 轨迹图相关
type GetTicketTrajectoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int64                  `protobuf:"varint,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketTrajectoryReq) Reset() {
	*x = GetTicketTrajectoryReq{}
	mi := &file_itsm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketTrajectoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketTrajectoryReq) ProtoMessage() {}

func (x *GetTicketTrajectoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketTrajectoryReq.ProtoReflect.Descriptor instead.
func (*GetTicketTrajectoryReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{25}
}

func (x *GetTicketTrajectoryReq) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type TicketTrajectoryResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BpmnXml          string                 `protobuf:"bytes,1,opt,name=bpmnXml,proto3" json:"bpmnXml,omitempty"`
	CompletedNodeIds []string               `protobuf:"bytes,2,rep,name=completedNodeIds,proto3" json:"completedNodeIds,omitempty"`
	ActiveNodeIds    []string               `protobuf:"bytes,3,rep,name=activeNodeIds,proto3" json:"activeNodeIds,omitempty"`
	RejectedNodeIds  []string               `protobuf:"bytes,4,rep,name=rejectedNodeIds,proto3" json:"rejectedNodeIds,omitempty"`
	Logs             []*TaskLogItem         `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TicketTrajectoryResp) Reset() {
	*x = TicketTrajectoryResp{}
	mi := &file_itsm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketTrajectoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketTrajectoryResp) ProtoMessage() {}

func (x *TicketTrajectoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketTrajectoryResp.ProtoReflect.Descriptor instead.
func (*TicketTrajectoryResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{26}
}

func (x *TicketTrajectoryResp) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *TicketTrajectoryResp) GetCompletedNodeIds() []string {
	if x != nil {
		return x.CompletedNodeIds
	}
	return nil
}

func (x *TicketTrajectoryResp) GetActiveNodeIds() []string {
	if x != nil {
		return x.ActiveNodeIds
	}
	return nil
}

func (x *TicketTrajectoryResp) GetRejectedNodeIds() []string {
	if x != nil {
		return x.RejectedNodeIds
	}
	return nil
}

func (x *TicketTrajectoryResp) GetLogs() []*TaskLogItem {
	if x != nil {
		return x.Logs
	}
	return nil
}

// SLA 策略相关
type SlaPolicyItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority         string                 `protobuf:"bytes,2,opt,name=priority,proto3" json:"priority,omitempty"`
	CalendarType     string                 `protobuf:"bytes,3,opt,name=calendarType,proto3" json:"calendarType,omitempty"`
	ResponseLimitMin int32                  `protobuf:"varint,4,opt,name=responseLimitMin,proto3" json:"responseLimitMin,omitempty"`
	ResolveLimitMin  int32                  `protobuf:"varint,5,opt,name=resolveLimitMin,proto3" json:"resolveLimitMin,omitempty"`
	WarnThresholdPct int32                  `protobuf:"varint,6,opt,name=warnThresholdPct,proto3" json:"warnThresholdPct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SlaPolicyItem) Reset() {
	*x = SlaPolicyItem{}
	mi := &file_itsm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlaPolicyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaPolicyItem) ProtoMessage() {}

func (x *SlaPolicyItem) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaPolicyItem.ProtoReflect.Descriptor instead.
func (*SlaPolicyItem) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{27}
}

func (x *SlaPolicyItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SlaPolicyItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SlaPolicyItem) GetCalendarType() string {
	if x != nil {
		return x.CalendarType
	}
	return ""
}

func (x *SlaPolicyItem) GetResponseLimitMin() int32 {
	if x != nil {
		return x.ResponseLimitMin
	}
	return 0
}

func (x *SlaPolicyItem) GetResolveLimitMin() int32 {
	if x != nil {
		return x.ResolveLimitMin
	}
	return 0
}

func (x *SlaPolicyItem) GetWarnThresholdPct() int32 {
	if x != nil {
		return x.WarnThresholdPct
	}
	return 0
}

type ListSlaPoliciesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlaPoliciesReq) Reset() {
	*x = ListSlaPoliciesReq{}
	mi := &file_itsm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlaPoliciesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlaPoliciesReq) ProtoMessage() {}

func (x *ListSlaPoliciesReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlaPoliciesReq.ProtoReflect.Descriptor instead.
func (*ListSlaPoliciesReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{28}
}

type ListSlaPoliciesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SlaPolicyItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlaPoliciesResp) Reset() {
	*x = ListSlaPoliciesResp{}
	mi := &file_itsm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlaPoliciesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlaPoliciesResp) ProtoMessage() {}

func (x *ListSlaPoliciesResp) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlaPoliciesResp.ProtoReflect.Descriptor instead.
func (*ListSlaPoliciesResp) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{29}
}

func (x *ListSlaPoliciesResp) GetList() []*SlaPolicyItem {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateSlaPolicyReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseLimitMin int32                  `protobuf:"varint,2,opt,name=responseLimitMin,proto3" json:"responseLimitMin,omitempty"`
	ResolveLimitMin  int32                  `protobuf:"varint,3,opt,name=resolveLimitMin,proto3" json:"resolveLimitMin,omitempty"`
	WarnThresholdPct int32                  `protobuf:"varint,4,opt,name=warnThresholdPct,proto3" json:"warnThresholdPct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateSlaPolicyReq) Reset() {
	*x = UpdateSlaPolicyReq{}
	mi := &file_itsm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSlaPolicyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSlaPolicyReq) ProtoMessage() {}

func (x *UpdateSlaPolicyReq) ProtoReflect() protoreflect.Message {
	mi := &file_itsm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSlaPolicyReq.ProtoReflect.Descriptor instead.
func (*UpdateSlaPolicyReq) Descriptor() ([]byte, []int) {
	return file_itsm_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateSlaPolicyReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSlaPolicyReq) GetResponseLimitMin() int32 {
	if x != nil {
		return x.ResponseLimitMin
	}
	return 0
}

func (x *UpdateSlaPolicyReq) GetResolveLimitMin() int32 {
	if x != nil {
		return x.ResolveLimitMin
	}
	return 0
}

func (x *UpdateSlaPolicyReq) GetWarnThresholdPct() int32 {
	if x != nil {
		return x.WarnThresholdPct
	}
	return 0
}

var File_itsm_proto protoreflect.FileDescriptor

const file_itsm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"itsm.proto\x12\x04itsm\"2\n" +
	"\n" +
	"CommonResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1d\n" +
	"\aPingReq\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bPingResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\xc2\x02\n" +
	"\x0eProcessDefItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprocCode\x18\x02 \x01(\tR\bprocCode\x12\x1a\n" +
	"\bprocName\x18\x03 \x01(\tR\bprocName\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\abpmnXml\x18\x05 \x01(\tR\abpmnXml\x12\x1e\n" +
	"\n" +
	"formSchema\x18\x06 \x01(\tR\n" +
	"formSchema\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\v \x01(\tR\n" +
	"updateTime\"\xe3\x01\n" +
	"\x13CreateProcessDefReq\x12\x1a\n" +
	"\bprocCode\x18\x01 \x01(\tR\bprocCode\x12\x1a\n" +
	"\bprocName\x18\x02 \x01(\tR\bprocName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\abpmnXml\x18\x04 \x01(\tR\abpmnXml\x12\x1e\n" +
	"\n" +
	"formSchema\x18\x05 \x01(\tR\n" +
	"formSchema\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedBy\x18\a \x01(\x03R\tcreatedBy\"&\n" +
	"\x14CreateProcessDefResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd1\x01\n" +
	"\x13UpdateProcessDefReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprocName\x18\x02 \x01(\tR\bprocName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\abpmnXml\x18\x04 \x01(\tR\abpmnXml\x12\x1e\n" +
	"\n" +
	"formSchema\x18\x05 \x01(\tR\n" +
	"formSchema\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\">\n" +
	"\x10GetProcessDefReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprocCode\x18\x02 \x01(\tR\bprocCode\"\x91\x01\n" +
	"\x11ListProcessDefReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\"T\n" +
	"\x12ListProcessDefResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.itsm.ProcessDefItemR\x04list\"%\n" +
	"\x13DeployProcessDefReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf4\x03\n" +
	"\n" +
	"TicketItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bticketNo\x18\x02 \x01(\tR\bticketNo\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12\x1c\n" +
	"\tprocDefId\x18\x05 \x01(\x03R\tprocDefId\x12\x1a\n" +
	"\bprocName\x18\x06 \x01(\tR\bprocName\x12 \n" +
	"\vinitiatorId\x18\a \x01(\x03R\vinitiatorId\x12$\n" +
	"\rinitiatorName\x18\b \x01(\tR\rinitiatorName\x12$\n" +
	"\rcurrentNodeId\x18\t \x01(\tR\rcurrentNodeId\x12(\n" +
	"\x0fcurrentNodeName\x18\n" +
	" \x01(\tR\x0fcurrentNodeName\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1c\n" +
	"\tslaStatus\x18\f \x01(\tR\tslaStatus\x120\n" +
	"\x13slaResponseDeadline\x18\r \x01(\tR\x13slaResponseDeadline\x12.\n" +
	"\x12slaResolveDeadline\x18\x0e \x01(\tR\x12slaResolveDeadline\x12\x1e\n" +
	"\n" +
	"createTime\x18\x0f \x01(\tR\n" +
	"createTime\"\xcd\x01\n" +
	"\x0fCreateTicketReq\x12\x1c\n" +
	"\tprocDefId\x18\x01 \x01(\x03R\tprocDefId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12 \n" +
	"\vinitiatorId\x18\x04 \x01(\x03R\vinitiatorId\x12$\n" +
	"\rinitiatorName\x18\x05 \x01(\tR\rinitiatorName\x12\"\n" +
	"\fformDataJson\x18\x06 \x01(\tR\fformDataJson\">\n" +
	"\x10CreateTicketResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bticketNo\x18\x02 \x01(\tR\bticketNo\"@\n" +
	"\x12GetTicketDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bticketNo\x18\x02 \x01(\tR\bticketNo\"\xde\x02\n" +
	"\bTaskItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06instId\x18\x02 \x01(\x03R\x06instId\x12\x16\n" +
	"\x06nodeId\x18\x03 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bnodeName\x18\x04 \x01(\tR\bnodeName\x12\x1a\n" +
	"\btaskType\x18\x05 \x01(\tR\btaskType\x12\"\n" +
	"\fapprovalMode\x18\x06 \x01(\tR\fapprovalMode\x12\x1e\n" +
	"\n" +
	"assigneeId\x18\a \x01(\x03R\n" +
	"assigneeId\x12\"\n" +
	"\fassigneeName\x18\b \x01(\tR\fassigneeName\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\aclaimAt\x18\n" +
	" \x01(\tR\aclaimAt\x12 \n" +
	"\vcompletedAt\x18\v \x01(\tR\vcompletedAt\x12\x1e\n" +
	"\n" +
	"createTime\x18\f \x01(\tR\n" +
	"createTime\"\xa9\x02\n" +
	"\vTaskLogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06nodeId\x18\x03 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bnodeName\x18\x04 \x01(\tR\bnodeName\x12\x1e\n" +
	"\n" +
	"operatorId\x18\x05 \x01(\x03R\n" +
	"operatorId\x12\"\n" +
	"\foperatorName\x18\x06 \x01(\tR\foperatorName\x12\x1e\n" +
	"\n" +
	"actionType\x18\a \x01(\tR\n" +
	"actionType\x12\x18\n" +
	"\aopinion\x18\b \x01(\tR\aopinion\x12 \n" +
	"\vdurationSec\x18\t \x01(\x05R\vdurationSec\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\tR\n" +
	"createTime\"\xfb\x01\n" +
	"\x10TicketDetailResp\x12(\n" +
	"\x06ticket\x18\x01 \x01(\v2\x10.itsm.TicketItemR\x06ticket\x12\"\n" +
	"\fformDataJson\x18\x02 \x01(\tR\fformDataJson\x12&\n" +
	"\x0eformSchemaJson\x18\x03 \x01(\tR\x0eformSchemaJson\x12\x18\n" +
	"\abpmnXml\x18\x04 \x01(\tR\abpmnXml\x120\n" +
	"\vactiveTasks\x18\x05 \x03(\v2\x0e.itsm.TaskItemR\vactiveTasks\x12%\n" +
	"\x04logs\x18\x06 \x03(\v2\x11.itsm.TaskLogItemR\x04logs\"\xc2\x01\n" +
	"\x0eListTicketsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bviewType\x18\x03 \x01(\tR\bviewType\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12\x18\n" +
	"\akeyword\x18\a \x01(\tR\akeyword\"M\n" +
	"\x0fListTicketsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12$\n" +
	"\x04list\x18\x02 \x03(\v2\x10.itsm.TicketItemR\x04list\"Z\n" +
	"\fClaimTaskReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\"\xa8\x01\n" +
	"\x0eApproveTaskReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\x18\n" +
	"\aopinion\x18\x04 \x01(\tR\aopinion\x120\n" +
	"\x13updatedFormDataJson\x18\x05 \x01(\tR\x13updatedFormDataJson\"u\n" +
	"\rRejectTaskReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\x18\n" +
	"\aopinion\x18\x04 \x01(\tR\aopinion\"\xc3\x01\n" +
	"\x0fTransferTaskReq\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\"\n" +
	"\ftargetUserId\x18\x04 \x01(\x03R\ftargetUserId\x12&\n" +
	"\x0etargetUserName\x18\x05 \x01(\tR\x0etargetUserName\x12\x18\n" +
	"\aopinion\x18\x06 \x01(\tR\aopinion\"y\n" +
	"\x0fCancelTicketReq\x12\x1a\n" +
	"\bticketId\x18\x01 \x01(\x03R\bticketId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"4\n" +
	"\x16GetTicketTrajectoryReq\x12\x1a\n" +
	"\bticketId\x18\x01 \x01(\x03R\bticketId\"\xd3\x01\n" +
	"\x14TicketTrajectoryResp\x12\x18\n" +
	"\abpmnXml\x18\x01 \x01(\tR\abpmnXml\x12*\n" +
	"\x10completedNodeIds\x18\x02 \x03(\tR\x10completedNodeIds\x12$\n" +
	"\ractiveNodeIds\x18\x03 \x03(\tR\ractiveNodeIds\x12(\n" +
	"\x0frejectedNodeIds\x18\x04 \x03(\tR\x0frejectedNodeIds\x12%\n" +
	"\x04logs\x18\x05 \x03(\v2\x11.itsm.TaskLogItemR\x04logs\"\xe1\x01\n" +
	"\rSlaPolicyItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\tR\bpriority\x12\"\n" +
	"\fcalendarType\x18\x03 \x01(\tR\fcalendarType\x12*\n" +
	"\x10responseLimitMin\x18\x04 \x01(\x05R\x10responseLimitMin\x12(\n" +
	"\x0fresolveLimitMin\x18\x05 \x01(\x05R\x0fresolveLimitMin\x12*\n" +
	"\x10warnThresholdPct\x18\x06 \x01(\x05R\x10warnThresholdPct\"\x14\n" +
	"\x12ListSlaPoliciesReq\">\n" +
	"\x13ListSlaPoliciesResp\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.itsm.SlaPolicyItemR\x04list\"\xa6\x01\n" +
	"\x12UpdateSlaPolicyReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x10responseLimitMin\x18\x02 \x01(\x05R\x10responseLimitMin\x12(\n" +
	"\x0fresolveLimitMin\x18\x03 \x01(\x05R\x0fresolveLimitMin\x12*\n" +
	"\x10warnThresholdPct\x18\x04 \x01(\x05R\x10warnThresholdPct2\xa7\b\n" +
	"\x04Itsm\x12%\n" +
	"\x04Ping\x12\r.itsm.PingReq\x1a\x0e.itsm.PingResp\x12I\n" +
	"\x10CreateProcessDef\x12\x19.itsm.CreateProcessDefReq\x1a\x1a.itsm.CreateProcessDefResp\x12?\n" +
	"\x10UpdateProcessDef\x12\x19.itsm.UpdateProcessDefReq\x1a\x10.itsm.CommonResp\x12=\n" +
	"\rGetProcessDef\x12\x16.itsm.GetProcessDefReq\x1a\x14.itsm.ProcessDefItem\x12C\n" +
	"\x0eListProcessDef\x12\x17.itsm.ListProcessDefReq\x1a\x18.itsm.ListProcessDefResp\x12?\n" +
	"\x10DeployProcessDef\x12\x19.itsm.DeployProcessDefReq\x1a\x10.itsm.CommonResp\x12=\n" +
	"\fCreateTicket\x12\x15.itsm.CreateTicketReq\x1a\x16.itsm.CreateTicketResp\x12C\n" +
	"\x0fGetTicketDetail\x12\x18.itsm.GetTicketDetailReq\x1a\x16.itsm.TicketDetailResp\x12:\n" +
	"\vListTickets\x12\x14.itsm.ListTicketsReq\x1a\x15.itsm.ListTicketsResp\x121\n" +
	"\tClaimTask\x12\x12.itsm.ClaimTaskReq\x1a\x10.itsm.CommonResp\x125\n" +
	"\vApproveTask\x12\x14.itsm.ApproveTaskReq\x1a\x10.itsm.CommonResp\x123\n" +
	"\n" +
	"RejectTask\x12\x13.itsm.RejectTaskReq\x1a\x10.itsm.CommonResp\x127\n" +
	"\fTransferTask\x12\x15.itsm.TransferTaskReq\x1a\x10.itsm.CommonResp\x127\n" +
	"\fCancelTicket\x12\x15.itsm.CancelTicketReq\x1a\x10.itsm.CommonResp\x12O\n" +
	"\x13GetTicketTrajectory\x12\x1c.itsm.GetTicketTrajectoryReq\x1a\x1a.itsm.TicketTrajectoryResp\x12F\n" +
	"\x0fListSlaPolicies\x12\x18.itsm.ListSlaPoliciesReq\x1a\x19.itsm.ListSlaPoliciesResp\x12=\n" +
	"\x0fUpdateSlaPolicy\x12\x18.itsm.UpdateSlaPolicyReq\x1a\x10.itsm.CommonRespB\bZ\x06./itsmb\x06proto3"

var (
	file_itsm_proto_rawDescOnce sync.Once
	file_itsm_proto_rawDescData []byte
)

func file_itsm_proto_rawDescGZIP() []byte {
	file_itsm_proto_rawDescOnce.Do(func() {
		file_itsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_itsm_proto_rawDesc), len(file_itsm_proto_rawDesc)))
	})
	return file_itsm_proto_rawDescData
}

var file_itsm_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_itsm_proto_goTypes = []any{
	(*CommonResp)(nil),             // 0: itsm.CommonResp
	(*PingReq)(nil),                // 1: itsm.PingReq
	(*PingResp)(nil),               // 2: itsm.PingResp
	(*ProcessDefItem)(nil),         // 3: itsm.ProcessDefItem
	(*CreateProcessDefReq)(nil),    // 4: itsm.CreateProcessDefReq
	(*CreateProcessDefResp)(nil),   // 5: itsm.CreateProcessDefResp
	(*UpdateProcessDefReq)(nil),    // 6: itsm.UpdateProcessDefReq
	(*GetProcessDefReq)(nil),       // 7: itsm.GetProcessDefReq
	(*ListProcessDefReq)(nil),      // 8: itsm.ListProcessDefReq
	(*ListProcessDefResp)(nil),     // 9: itsm.ListProcessDefResp
	(*DeployProcessDefReq)(nil),    // 10: itsm.DeployProcessDefReq
	(*TicketItem)(nil),             // 11: itsm.TicketItem
	(*CreateTicketReq)(nil),        // 12: itsm.CreateTicketReq
	(*CreateTicketResp)(nil),       // 13: itsm.CreateTicketResp
	(*GetTicketDetailReq)(nil),     // 14: itsm.GetTicketDetailReq
	(*TaskItem)(nil),               // 15: itsm.TaskItem
	(*TaskLogItem)(nil),            // 16: itsm.TaskLogItem
	(*TicketDetailResp)(nil),       // 17: itsm.TicketDetailResp
	(*ListTicketsReq)(nil),         // 18: itsm.ListTicketsReq
	(*ListTicketsResp)(nil),        // 19: itsm.ListTicketsResp
	(*ClaimTaskReq)(nil),           // 20: itsm.ClaimTaskReq
	(*ApproveTaskReq)(nil),         // 21: itsm.ApproveTaskReq
	(*RejectTaskReq)(nil),          // 22: itsm.RejectTaskReq
	(*TransferTaskReq)(nil),        // 23: itsm.TransferTaskReq
	(*CancelTicketReq)(nil),        // 24: itsm.CancelTicketReq
	(*GetTicketTrajectoryReq)(nil), // 25: itsm.GetTicketTrajectoryReq
	(*TicketTrajectoryResp)(nil),   // 26: itsm.TicketTrajectoryResp
	(*SlaPolicyItem)(nil),          // 27: itsm.SlaPolicyItem
	(*ListSlaPoliciesReq)(nil),     // 28: itsm.ListSlaPoliciesReq
	(*ListSlaPoliciesResp)(nil),    // 29: itsm.ListSlaPoliciesResp
	(*UpdateSlaPolicyReq)(nil),     // 30: itsm.UpdateSlaPolicyReq
}
var file_itsm_proto_depIdxs = []int32{
	3,  // 0: itsm.ListProcessDefResp.list:type_name -> itsm.ProcessDefItem
	11, // 1: itsm.TicketDetailResp.ticket:type_name -> itsm.TicketItem
	15, // 2: itsm.TicketDetailResp.activeTasks:type_name -> itsm.TaskItem
	16, // 3: itsm.TicketDetailResp.logs:type_name -> itsm.TaskLogItem
	11, // 4: itsm.ListTicketsResp.list:type_name -> itsm.TicketItem
	16, // 5: itsm.TicketTrajectoryResp.logs:type_name -> itsm.TaskLogItem
	27, // 6: itsm.ListSlaPoliciesResp.list:type_name -> itsm.SlaPolicyItem
	1,  // 7: itsm.Itsm.Ping:input_type -> itsm.PingReq
	4,  // 8: itsm.Itsm.CreateProcessDef:input_type -> itsm.CreateProcessDefReq
	6,  // 9: itsm.Itsm.UpdateProcessDef:input_type -> itsm.UpdateProcessDefReq
	7,  // 10: itsm.Itsm.GetProcessDef:input_type -> itsm.GetProcessDefReq
	8,  // 11: itsm.Itsm.ListProcessDef:input_type -> itsm.ListProcessDefReq
	10, // 12: itsm.Itsm.DeployProcessDef:input_type -> itsm.DeployProcessDefReq
	12, // 13: itsm.Itsm.CreateTicket:input_type -> itsm.CreateTicketReq
	14, // 14: itsm.Itsm.GetTicketDetail:input_type -> itsm.GetTicketDetailReq
	18, // 15: itsm.Itsm.ListTickets:input_type -> itsm.ListTicketsReq
	20, // 16: itsm.Itsm.ClaimTask:input_type -> itsm.ClaimTaskReq
	21, // 17: itsm.Itsm.ApproveTask:input_type -> itsm.ApproveTaskReq
	22, // 18: itsm.Itsm.RejectTask:input_type -> itsm.RejectTaskReq
	23, // 19: itsm.Itsm.TransferTask:input_type -> itsm.TransferTaskReq
	24, // 20: itsm.Itsm.CancelTicket:input_type -> itsm.CancelTicketReq
	25, // 21: itsm.Itsm.GetTicketTrajectory:input_type -> itsm.GetTicketTrajectoryReq
	28, // 22: itsm.Itsm.ListSlaPolicies:input_type -> itsm.ListSlaPoliciesReq
	30, // 23: itsm.Itsm.UpdateSlaPolicy:input_type -> itsm.UpdateSlaPolicyReq
	2,  // 24: itsm.Itsm.Ping:output_type -> itsm.PingResp
	5,  // 25: itsm.Itsm.CreateProcessDef:output_type -> itsm.CreateProcessDefResp
	0,  // 26: itsm.Itsm.UpdateProcessDef:output_type -> itsm.CommonResp
	3,  // 27: itsm.Itsm.GetProcessDef:output_type -> itsm.ProcessDefItem
	9,  // 28: itsm.Itsm.ListProcessDef:output_type -> itsm.ListProcessDefResp
	0,  // 29: itsm.Itsm.DeployProcessDef:output_type -> itsm.CommonResp
	13, // 30: itsm.Itsm.CreateTicket:output_type -> itsm.CreateTicketResp
	17, // 31: itsm.Itsm.GetTicketDetail:output_type -> itsm.TicketDetailResp
	19, // 32: itsm.Itsm.ListTickets:output_type -> itsm.ListTicketsResp
	0,  // 33: itsm.Itsm.ClaimTask:output_type -> itsm.CommonResp
	0,  // 34: itsm.Itsm.ApproveTask:output_type -> itsm.CommonResp
	0,  // 35: itsm.Itsm.RejectTask:output_type -> itsm.CommonResp
	0,  // 36: itsm.Itsm.TransferTask:output_type -> itsm.CommonResp
	0,  // 37: itsm.Itsm.CancelTicket:output_type -> itsm.CommonResp
	26, // 38: itsm.Itsm.GetTicketTrajectory:output_type -> itsm.TicketTrajectoryResp
	29, // 39: itsm.Itsm.ListSlaPolicies:output_type -> itsm.ListSlaPoliciesResp
	0,  // 40: itsm.Itsm.UpdateSlaPolicy:output_type -> itsm.CommonResp
	24, // [24:41] is the sub-list for method output_type
	7,  // [7:24] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_itsm_proto_init() }
func file_itsm_proto_init() {
	if File_itsm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_itsm_proto_rawDesc), len(file_itsm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_itsm_proto_goTypes,
		DependencyIndexes: file_itsm_proto_depIdxs,
		MessageInfos:      file_itsm_proto_msgTypes,
	}.Build()
	File_itsm_proto = out.File
	file_itsm_proto_goTypes = nil
	file_itsm_proto_depIdxs = nil
}
