// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateSysDictDataReq struct {
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictSort  int32  `json:"dictSort,optional,default=0"`
	ListClass string `json:"listClass,optional"`
	IsDefault int32  `json:"isDefault,optional,default=0"`
	Status    int32  `json:"status,optional,default=1"`
	Remark    string `json:"remark,optional"`
}

type CreateSysDictTypeReq struct {
	DictName string `json:"dictName"`
	DictType string `json:"dictType"`
	Status   int32  `json:"status,optional,default=1"`
	Remark   string `json:"remark,optional"`
}

type GetDictDataByTypeReq struct {
	DictType string `path:"dictType"`
}

type GetDictDataByTypeResp struct {
	List []*SysDictDataItem `json:"list"`
}

type ListSysDictDataReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	DictType string `form:"dictType"`
	Keyword  string `form:"keyword,optional"`
	Status   int32  `form:"status,optional"`
}

type ListSysDictDataResp struct {
	Total int64              `json:"total"`
	List  []*SysDictDataItem `json:"list"`
}

type ListSysDictTypesReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
	Status   int32  `form:"status,optional"`
}

type ListSysDictTypesResp struct {
	Total int64              `json:"total"`
	List  []*SysDictTypeItem `json:"list"`
}

type UpdateSysDictDataReq struct {
	Id        int64  `json:"id"`
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictSort  int32  `json:"dictSort"`
	ListClass string `json:"listClass,optional"`
	IsDefault int32  `json:"isDefault"`
	Status    int32  `json:"status"`
	Remark    string `json:"remark,optional"`
}

type UpdateSysDictTypeReq struct {
	Id       int64  `json:"id"`
	DictName string `json:"dictName"`
	DictType string `json:"dictType"`
	Status   int32  `json:"status"`
	Remark   string `json:"remark,optional"`
}
