// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ApproveTaskReqVO struct {
	Id                  int64  `path:"id"`
	TaskId              int64  `json:"taskId"`
	Opinion             string `json:"opinion,optional"`
	UpdatedFormDataJson string `json:"updatedFormDataJson,optional"`
}

type CancelTicketReqVO struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason,optional"`
}

type ClaimTaskReqVO struct {
	Id     int64 `path:"id"`
	TaskId int64 `json:"taskId"`
}

type CreateProcessDefReqVO struct {
	ProcCode    string `json:"procCode"`
	ProcName    string `json:"procName"`
	Category    string `json:"category,optional,default=it_service"`
	BpmnXml     string `json:"bpmnXml,optional"`
	FormSchema  string `json:"formSchema,optional"`
	Description string `json:"description,optional"`
}

type CreateTicketReqVO struct {
	ProcDefId    int64  `json:"procDefId"`
	Title        string `json:"title"`
	Priority     string `json:"priority,optional,default=P3"`
	FormDataJson string `json:"formDataJson,optional"`
}

type CreateTicketRespVO struct {
	Id       int64  `json:"id"`
	TicketNo string `json:"ticketNo"`
}

type DeployProcessDefReqVO struct {
	Id int64 `path:"id"`
}

type GetProcessDefReq struct {
	Id int64 `path:"id"`
}

type GetTicketDetailReqVO struct {
	Id int64 `path:"id"`
}

type GetTicketTrajectoryReqVO struct {
	Id int64 `path:"id"`
}

type ListProcessDefsReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Category string `form:"category,optional"`
	Status   int32  `form:"status,default=0,optional"`
	Keyword  string `form:"keyword,optional"`
}

type ListProcessDefsResp struct {
	Total int64          `json:"total"`
	List  []ProcessDefVO `json:"list"`
}

type ListSlaPoliciesRespVO struct {
	List []SlaPolicyVO `json:"list"`
}

type ListTicketsReqVO struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	ViewType string `form:"viewType,optional,default=all"`
	Status   string `form:"status,optional"`
	Priority string `form:"priority,optional"`
	Keyword  string `form:"keyword,optional"`
}

type ListTicketsRespVO struct {
	Total int64      `json:"total"`
	List  []TicketVO `json:"list"`
}

type ProcessDefVO struct {
	Id          int64  `json:"id"`
	ProcCode    string `json:"procCode"`
	ProcName    string `json:"procName"`
	Category    string `json:"category"`
	BpmnXml     string `json:"bpmnXml"`
	FormSchema  string `json:"formSchema"`
	Version     int32  `json:"version"`
	Status      int32  `json:"status"`
	Description string `json:"description"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type RejectTaskReqVO struct {
	Id      int64  `path:"id"`
	TaskId  int64  `json:"taskId"`
	Opinion string `json:"opinion,optional"`
}

type TicketDetailRespVO struct {
	Ticket         TicketVO    `json:"ticket"`
	FormDataJson   string      `json:"formDataJson"`
	FormSchemaJson string      `json:"formSchemaJson"`
	BpmnXml        string      `json:"bpmnXml"`
	ActiveTasks    []TaskVO    `json:"activeTasks"`
	Logs           []TaskLogVO `json:"logs"`
}

type TicketTrajectoryRespVO struct {
	BpmnXml          string      `json:"bpmnXml"`
	CompletedNodeIds []string    `json:"completedNodeIds"`
	ActiveNodeIds    []string    `json:"activeNodeIds"`
	RejectedNodeIds  []string    `json:"rejectedNodeIds"`
	Logs             []TaskLogVO `json:"logs"`
}

type TransferTaskReqVO struct {
	Id           int64  `path:"id"`
	TaskId       int64  `json:"taskId"`
	TargetUserId int64  `json:"targetUserId"`
	Opinion      string `json:"opinion,optional"`
}

type UpdateProcessDefReqVO struct {
	Id          int64  `path:"id"`
	ProcName    string `json:"procName,optional"`
	Category    string `json:"category,optional"`
	BpmnXml     string `json:"bpmnXml,optional"`
	FormSchema  string `json:"formSchema,optional"`
	Description string `json:"description,optional"`
	Status      int32  `json:"status,optional"`
}

type UpdateSlaPolicyReqVO struct {
	Id               int64 `path:"id"`
	ResponseLimitMin int32 `json:"responseLimitMin,optional"`
	ResolveLimitMin  int32 `json:"resolveLimitMin,optional"`
	WarnThresholdPct int32 `json:"warnThresholdPct,optional"`
}
