// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type GetPortalNavListReq struct {
	Status int64  `form:"status,default=1,optional"`
	Env    string `form:"env,optional"`
}

type GetPortalNavListResp struct {
	List []PortalNavDTO `json:"list"`
}
