// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateSysPostReq struct {
	PostCode string `json:"postCode"`        // 岗位编码
	PostName string `json:"postName"`        // 岗位名称
	PostSort int64  `json:"postSort"`        // 显示顺序
	Status   int64  `json:"status"`          // 状态（1正常 0停用）
	Remark   string `json:"remark,optional"` // 备注
}

type ListSysPostReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type ListSysPostResp struct {
	Total int64          `json:"total"`
	List  []*SysPostItem `json:"list"`
}

type SysPostItem struct {
	Id         int64  `json:"id"`         // 岗位ID
	PostCode   string `json:"postCode"`   // 岗位编码
	PostName   string `json:"postName"`   // 岗位名称
	PostSort   int64  `json:"postSort"`   // 显示顺序
	Status     int64  `json:"status"`     // 状态（1正常 0停用）
	Remark     string `json:"remark"`     // 备注
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
}

type UpdateSysPostReq struct {
	Id       int64  `json:"id"`       // 岗位ID
	PostCode string `json:"postCode"` // 岗位编码
	PostName string `json:"postName"` // 岗位名称
	PostSort int64  `json:"postSort"` // 显示顺序
	Status   int64  `json:"status"`   // 状态（1正常 0停用）
	Remark   string `json:"remark"`   // 备注
}
