// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateSysNoticeReq struct {
	NoticeTitle   string `json:"noticeTitle"`     // 公告标题
	NoticeType    int64  `json:"noticeType"`      // 公告类型（1通知 2消息 3待办）
	NoticeContent string `json:"noticeContent"`   // 公告内容
	Status        int64  `json:"status"`          // 公告状态（1正常 0关闭）
	CreateBy      string `json:"createBy"`        // 创建者
	Remark        string `json:"remark,optional"` // 备注
}

type ListSysNoticeReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type ListSysNoticeResp struct {
	Total int64            `json:"total"`
	List  []*SysNoticeItem `json:"list"`
}

type SysNoticeItem struct {
	Id            int64  `json:"id"`            // 公告ID
	NoticeTitle   string `json:"noticeTitle"`   // 公告标题
	NoticeType    int64  `json:"noticeType"`    // 公告类型（1通知 2消息 3待办）
	NoticeContent string `json:"noticeContent"` // 公告内容
	Status        int64  `json:"status"`        // 公告状态（1正常 0关闭）
	CreateBy      string `json:"createBy"`      // 创建者
	Remark        string `json:"remark"`        // 备注
	CreateTime    string `json:"createTime"`    // 创建时间
	UpdateTime    string `json:"updateTime"`    // 更新时间
}

type UpdateSysNoticeReq struct {
	Id            int64  `json:"id"`            // 公告ID
	NoticeTitle   string `json:"noticeTitle"`   // 公告标题
	NoticeType    int64  `json:"noticeType"`    // 公告类型（1通知 2消息 3待办）
	NoticeContent string `json:"noticeContent"` // 公告内容
	Status        int64  `json:"status"`        // 公告状态（1正常 0关闭）
	CreateBy      string `json:"createBy"`      // 创建者
	Remark        string `json:"remark"`        // 备注
}
