// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DashboardReq struct {
	OrderId int64 `form:"orderId,optional"`
}

type DashboardResp struct {
	UserInfo UserInfoResp    `json:"userInfo"`
	Order    OrderDetailResp `json:"order"`
	SysTime  int64           `json:"sysTime"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	UserId       int64  `json:"userId"`
	Username     string `json:"username"`
}

type OrderDetailReq struct {
	OrderId int64 `form:"orderId"`
}

type OrderDetailResp struct {
	OrderId  int64   `json:"orderId"`
	Item     string  `json:"item"`
	Amount   float64 `json:"amount"`
	Status   string  `json:"status"`
	UserId   int64   `json:"userId"`
	UserName string  `json:"userName"`
	Avatar   string  `json:"avatar"`
}

type RegisterReq struct {
	Username string `json:"username,optional"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id int64 `json:"id"`
}

type UserInfoReq struct {
	Id int64 `form:"id,optional"`
}

type UserInfoResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
	Avatar string `json:"avatar"`
}
