// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AdminLoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	AccessToken  string   `json:"accessToken"`
	AccessExpire int64    `json:"accessExpire"`
	RefreshAfter int64    `json:"refreshAfter"`
	UserId       int64    `json:"userId"`
	Username     string   `json:"username"`
	RealName     string   `json:"realName"`
	Avatar       string   `json:"avatar"`
	Roles        []string `json:"roles"`
}

type AdminProfileResp struct {
	Id          int64          `json:"id"`
	Username    string         `json:"username"`
	RealName    string         `json:"realName"`
	Mobile      string         `json:"mobile"`
	Email       string         `json:"email"`
	Avatar      string         `json:"avatar"`
	DeptName    string         `json:"deptName"`
	Roles       []string       `json:"roles"`
	Permissions []string       `json:"permissions"`
	Menus       []*SysMenuItem `json:"menus"`
}

type AssignRolePermReq struct {
	RoleId  int64   `json:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type CasdoorLoginReq struct {
	Code  string `json:"code"`
	State string `json:"state,optional"`
}

type ChangePersonalPasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CreateSysDeptReq struct {
	ParentId int64  `json:"parentId"`
	DeptName string `json:"deptName"`
	Sort     int64  `json:"sort,optional"`
	Leader   string `json:"leader,optional"`
	Phone    string `json:"phone,optional"`
	Status   int64  `json:"status,optional,default=1"`
}

type CreateSysDictDataReq struct {
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictSort  int32  `json:"dictSort,optional,default=0"`
	ListClass string `json:"listClass,optional"`
	IsDefault int32  `json:"isDefault,optional,default=0"`
	Status    int32  `json:"status,optional,default=1"`
	Remark    string `json:"remark,optional"`
}

type CreateSysDictTypeReq struct {
	DictName string `json:"dictName"`
	DictType string `json:"dictType"`
	Status   int32  `json:"status,optional,default=1"`
	Remark   string `json:"remark,optional"`
}

type CreateSysNoticeReq struct {
	NoticeTitle   string `json:"noticeTitle"`     // 公告标题
	NoticeType    int64  `json:"noticeType"`      // 公告类型（1通知 2消息 3待办）
	NoticeContent string `json:"noticeContent"`   // 公告内容
	Status        int64  `json:"status"`          // 公告状态（1正常 0关闭）
	CreateBy      string `json:"createBy"`        // 创建者
	Remark        string `json:"remark,optional"` // 备注
}

type CreateSysPostReq struct {
	PostCode string `json:"postCode"`        // 岗位编码
	PostName string `json:"postName"`        // 岗位名称
	PostSort int64  `json:"postSort"`        // 显示顺序
	Status   int64  `json:"status"`          // 状态（1正常 0停用）
	Remark   string `json:"remark,optional"` // 备注
}

type CreateSysRoleReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Sort        int32  `json:"sort,optional"`
	DataScope   int32  `json:"dataScope,optional"`
	Description string `json:"description,optional"`
}

type CreateSysUserReq struct {
	DeptId   int64   `json:"deptId,optional"`
	Username string  `json:"username"`
	Password string  `json:"password"`
	RealName string  `json:"realName"`
	Mobile   string  `json:"mobile,optional"`
	Email    string  `json:"email,optional"`
	RoleIds  []int64 `json:"roleIds,optional"`
}

type DashboardReq struct {
	OrderId int64 `form:"orderId,optional"`
}

type DashboardResp struct {
	UserInfo UserInfoResp    `json:"userInfo"`
	Order    OrderDetailResp `json:"order"`
	SysTime  int64           `json:"sysTime"`
}

type FileUploadResp struct {
	Url          string `json:"url"`
	Filename     string `json:"filename"`
	OriginalName string `json:"originalName"`
	Size         int64  `json:"size"`
	MimeType     string `json:"mimeType"`
	Hash         string `json:"hash"`
}

type GetDictDataByTypeReq struct {
	DictType string `path:"dictType"`
}

type GetDictDataByTypeResp struct {
	List []*SysDictDataItem `json:"list"`
}

type GetMyNoticeFeedReq struct {
	Limit int64 `form:"limit,optional,default=50"`
}

type GetMyNoticeFeedResp struct {
	TotalUnread int64             `json:"totalUnread"`
	List        []*NoticeFeedItem `json:"list"`
}

type GetSysMenuTreeResp struct {
	List []*SysMenuItem `json:"list"`
}

type ListSysApisResp struct {
	List []*SysApiItem `json:"list"`
}

type ListSysDeptReq struct {
	Keyword string `form:"keyword,optional"`
	Status  int64  `form:"status,optional,default=-1"`
}

type ListSysDeptResp struct {
	List []*SysDeptItem `json:"list"`
}

type ListSysDictDataReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	DictType string `form:"dictType"`
	Keyword  string `form:"keyword,optional"`
	Status   int32  `form:"status,optional"`
}

type ListSysDictDataResp struct {
	Total int64              `json:"total"`
	List  []*SysDictDataItem `json:"list"`
}

type ListSysDictTypesReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
	Status   int32  `form:"status,optional"`
}

type ListSysDictTypesResp struct {
	Total int64              `json:"total"`
	List  []*SysDictTypeItem `json:"list"`
}

type ListSysLoginLogsReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Username string `form:"username,optional"`
	Status   int32  `form:"status,optional"`
}

type ListSysLoginLogsResp struct {
	Total int64              `json:"total"`
	List  []*SysLoginLogItem `json:"list"`
}

type ListSysNoticeReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type ListSysNoticeResp struct {
	Total int64            `json:"total"`
	List  []*SysNoticeItem `json:"list"`
}

type ListSysOperLogsReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	OperName string `form:"operName,optional"`
	Title    string `form:"title,optional"`
	Status   int32  `form:"status,optional"`
}

type ListSysOperLogsResp struct {
	Total int64             `json:"total"`
	List  []*SysOperLogItem `json:"list"`
}

type ListSysPostReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type ListSysPostResp struct {
	Total int64          `json:"total"`
	List  []*SysPostItem `json:"list"`
}

type ListSysRolesReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type ListSysRolesResp struct {
	Total int64          `json:"total"`
	List  []*SysRoleItem `json:"list"`
}

type ListSysUsersReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
	DeptId   int64  `form:"deptId,optional"`
}

type ListSysUsersResp struct {
	Total int64          `json:"total"`
	List  []*SysUserItem `json:"list"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	UserId       int64  `json:"userId"`
	Username     string `json:"username"`
}

type MarkAllNoticesReadReq struct {
	NoticeType int64 `json:"noticeType,optional"`
}

type MarkNoticeReadReq struct {
	NoticeId int64 `json:"noticeId"`
}

type NoticeFeedItem struct {
	Id            int64  `json:"id"`
	NoticeTitle   string `json:"noticeTitle"`
	NoticeType    int64  `json:"noticeType"`
	NoticeContent string `json:"noticeContent"`
	Status        int64  `json:"status"`
	CreateBy      string `json:"createBy"`
	Remark        string `json:"remark"`
	CreateTime    string `json:"createTime"`
	UpdateTime    string `json:"updateTime"`
	IsRead        bool   `json:"isRead"`
}

type OrderDetailReq struct {
	OrderId int64 `form:"orderId,default=1001,optional"`
}

type OrderDetailResp struct {
	OrderId  int64   `json:"orderId"`
	Item     string  `json:"item"`
	Amount   float64 `json:"amount"`
	Status   string  `json:"status"`
	UserId   int64   `json:"userId"`
	UserName string  `json:"userName"`
	Avatar   string  `json:"avatar"`
}

type RegisterReq struct {
	Username string `json:"username,optional"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id int64 `json:"id"`
}

type SysApiItem struct {
	Id         int64  `json:"id"`
	ApiGroup   string `json:"apiGroup"`
	Title      string `json:"title"`
	Path       string `json:"path"`
	Method     string `json:"method"`
	IsAutoSync int32  `json:"isAutoSync"`
}

type SysDeptItem struct {
	Id         int64          `json:"id"`
	ParentId   int64          `json:"parentId"`
	Ancestors  string         `json:"ancestors"`
	DeptName   string         `json:"deptName"`
	Sort       int64          `json:"sort"`
	Leader     string         `json:"leader"`
	Phone      string         `json:"phone"`
	Status     int64          `json:"status"`
	CreateTime string         `json:"createTime"`
	UpdateTime string         `json:"updateTime"`
	Children   []*SysDeptItem `json:"children,omitempty"`
}

type SysDictDataItem struct {
	Id         int64  `json:"id"`
	DictType   string `json:"dictType"`
	DictLabel  string `json:"dictLabel"`
	DictValue  string `json:"dictValue"`
	DictSort   int32  `json:"dictSort"`
	ListClass  string `json:"listClass"`
	IsDefault  int32  `json:"isDefault"`
	Status     int32  `json:"status"`
	Remark     string `json:"remark"`
	CreateTime string `json:"createTime"`
}

type SysDictTypeItem struct {
	Id         int64  `json:"id"`
	DictName   string `json:"dictName"`
	DictType   string `json:"dictType"`
	Status     int32  `json:"status"`
	Remark     string `json:"remark"`
	CreateTime string `json:"createTime"`
}

type SysEmptyResp struct {
	Success bool `json:"success"`
}

type SysIdReq struct {
	Id int64 `path:"id"`
}

type SysIdResp struct {
	Id int64 `json:"id"`
}

type SysLoginLogItem struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	LoginIp   string `json:"loginIp"`
	Browser   string `json:"browser"`
	Os        string `json:"os"`
	Status    int32  `json:"status"`
	Msg       string `json:"msg"`
	LoginTime string `json:"loginTime"`
}

type SysMenuItem struct {
	Id             int64          `json:"id"`
	ParentId       int64          `json:"parentId"`
	Title          string         `json:"title"`
	Type           int32          `json:"type"` // 1:目录 2:菜单 3:按钮
	Path           string         `json:"path"`
	Component      string         `json:"component"`
	PermissionCode string         `json:"permissionCode"`
	Icon           string         `json:"icon"`
	Sort           int32          `json:"sort"`
	Children       []*SysMenuItem `json:"children,omitempty"`
}

type SysNoticeItem struct {
	Id            int64  `json:"id"`            // 公告ID
	NoticeTitle   string `json:"noticeTitle"`   // 公告标题
	NoticeType    int64  `json:"noticeType"`    // 公告类型（1通知 2消息 3待办）
	NoticeContent string `json:"noticeContent"` // 公告内容
	Status        int64  `json:"status"`        // 公告状态（1正常 0关闭）
	CreateBy      string `json:"createBy"`      // 创建者
	Remark        string `json:"remark"`        // 备注
	CreateTime    string `json:"createTime"`    // 创建时间
	UpdateTime    string `json:"updateTime"`    // 更新时间
}

type SysOperLogItem struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`
	OperName   string `json:"operName"`
	OperUrl    string `json:"operUrl"`
	OperMethod string `json:"operMethod"`
	OperIp     string `json:"operIp"`
	Status     int32  `json:"status"`
	ErrorMsg   string `json:"errorMsg"`
	CostTime   int64  `json:"costTime"`
	CreateTime string `json:"createTime"`
}

type SysPostItem struct {
	Id         int64  `json:"id"`         // 岗位ID
	PostCode   string `json:"postCode"`   // 岗位编码
	PostName   string `json:"postName"`   // 岗位名称
	PostSort   int64  `json:"postSort"`   // 显示顺序
	Status     int64  `json:"status"`     // 状态（1正常 0停用）
	Remark     string `json:"remark"`     // 备注
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
}

type SysRoleItem struct {
	Id          int64   `json:"id"`
	Name        string  `json:"name"`
	Code        string  `json:"code"`
	Sort        int32   `json:"sort,optional"`
	DataScope   int32   `json:"dataScope,optional"`
	Status      int32   `json:"status"`
	Description string  `json:"description,optional"`
	MenuIds     []int64 `json:"menuIds,optional"`
	CreateTime  string  `json:"createTime"`
}

type SysUserItem struct {
	Id         int64    `json:"id"`
	DeptId     int64    `json:"deptId"`
	DeptName   string   `json:"deptName"`
	Username   string   `json:"username"`
	RealName   string   `json:"realName"`
	Mobile     string   `json:"mobile"`
	Email      string   `json:"email"`
	Avatar     string   `json:"avatar"`
	Status     int32    `json:"status"`
	RoleNames  []string `json:"roleNames"`
	RoleIds    []int64  `json:"roleIds"`
	CreateTime string   `json:"createTime"`
}

type UpdatePersonalProfileReq struct {
	RealName string `json:"realName"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UpdateSysDeptReq struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parentId"`
	DeptName string `json:"deptName"`
	Sort     int64  `json:"sort"`
	Leader   string `json:"leader,optional"`
	Phone    string `json:"phone,optional"`
	Status   int64  `json:"status"`
}

type UpdateSysDictDataReq struct {
	Id        int64  `json:"id"`
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	DictSort  int32  `json:"dictSort"`
	ListClass string `json:"listClass,optional"`
	IsDefault int32  `json:"isDefault"`
	Status    int32  `json:"status"`
	Remark    string `json:"remark,optional"`
}

type UpdateSysDictTypeReq struct {
	Id       int64  `json:"id"`
	DictName string `json:"dictName"`
	DictType string `json:"dictType"`
	Status   int32  `json:"status"`
	Remark   string `json:"remark,optional"`
}

type UpdateSysNoticeReq struct {
	Id            int64  `json:"id"`            // 公告ID
	NoticeTitle   string `json:"noticeTitle"`   // 公告标题
	NoticeType    int64  `json:"noticeType"`    // 公告类型（1通知 2消息 3待办）
	NoticeContent string `json:"noticeContent"` // 公告内容
	Status        int64  `json:"status"`        // 公告状态（1正常 0关闭）
	CreateBy      string `json:"createBy"`      // 创建者
	Remark        string `json:"remark"`        // 备注
}

type UpdateSysPostReq struct {
	Id       int64  `json:"id"`       // 岗位ID
	PostCode string `json:"postCode"` // 岗位编码
	PostName string `json:"postName"` // 岗位名称
	PostSort int64  `json:"postSort"` // 显示顺序
	Status   int64  `json:"status"`   // 状态（1正常 0停用）
	Remark   string `json:"remark"`   // 备注
}

type UpdateSysRoleReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Sort        int32  `json:"sort,optional"`
	DataScope   int32  `json:"dataScope,optional"`
	Description string `json:"description,optional"`
	Status      int32  `json:"status"`
}

type UpdateSysUserReq struct {
	Id       int64   `json:"id"`
	DeptId   int64   `json:"deptId,optional"`
	RealName string  `json:"realName"`
	Mobile   string  `json:"mobile,optional"`
	Email    string  `json:"email,optional"`
	Status   int32   `json:"status"`
	RoleIds  []int64 `json:"roleIds,optional"`
}

type UserInfoReq struct {
	Id int64 `form:"id,optional"`
}

type UserInfoResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
	Avatar string `json:"avatar"`
}
